### ISSUE TITLE
Add network support

### ISSUE THREAD

**Issue by ArtOfCode-** [codidact/qpixel#1]
We need qpixel to be able to support a network of sites, as opposed to the single site it currently supports. That's a fundamental change, so this is a lot of work and potentially pretty complex. Some concerns in no particular order:

 * We need to be able to keep our URL structure - we have writing.codidact.com that must keep working, so this must support setting community scope by Host header.
 * (relatedly) We will use 3rd-level domains (XXX.XXX.TLD) for sites, but we will not use a second-level for "instance scope" as with Core; this means that all 3LDs must also be able to run queries not scoped to a single community (for things like reporting).
 * We will need MANY tests for this. We have a decent test suite already, but we'll need to have plenty more to make sure this works.
 * Most database tables will need a `community` field added to them (integer FK to a Communities table). Users should be shared across communities.
 * Database seeds script will need to be updated to add seeds once for each community, rather than just once.

**Comment by pinnymz** [comment]
@ArtOfCode- Can you elaborate a bit on both the Host header and third level domains? Providing functional examples might help here.

**Comment by TheHelmar** [comment]
Why do we need this at all?
The only thing we'd need for a network is a shared identity. We don't need community fields for that...

**Comment by ArtOfCode-** [comment]
@TheHelmar One instance of qpixel must be able to support multiple communities. That's why we need this - we need more than just making them _look_ the same.

**Comment by ArtOfCode-** [comment]
@pinnymz So, for example, we might have `writing.codidact.com` and `programming.codidact.com` and `beer.codidact.com` - all three should be served by the same instance of qpixel. The app should find out which site we're on by looking at the URL (the Host header) and matching that to values in a `communities` table so that we can scope queries to the appropriate community.

**Comment by pinnymz** [comment]
@ArtOfCode understood.  Two questions - who should hold the mapping from host-name to community id?  Also, is it on the table to have http service config (are we using nginx?) hold the mapping and inject a community_id as a custom header?

**Comment by pinnymz** [comment]
TIL that @ArtOfCode- has a trailing hyphen for a reason ;)

**Comment by artofcode** [comment]
> TIL that @ArtOfCode- has a trailing hyphen for a reason ;)

Yeah tell me about it....

**Comment by ArtOfCode-** [comment]
@pinnymz The mapping will be in the communities table - it'll have fields for community name, URL, and ID. I'm not against nginx passing an `X-Community-Id` header, but the _default_ should be for the application to set it itself via the Host header, not to rely on that header being there.

**Comment by pinnymz** [comment]
@ArtOfCode- understood.  For testing purposes, I'm going to assume this lookup will be mocked, or we'll rely on an injected header.

**Comment by ArtOfCode-** [comment]
We'll have to figure out what the easiest way to do testing is - whether it's possible to inject headers, fake the URL, fake the lookup... I don't know.

**Comment by pinnymz** [comment]
Proposed plan of attack:
- Many data elements (e.g. Flag, Vote)`belong_to` a Post. Ideally, the Community for those elements should be interpreted as the parent Post community, rather than duplicating the data and running the risk of ambiguity/corruption.
- User is not scoped to a single community, nor are any related profile elements. However, with the introduction of Community, we'd need to break out some information for the User as related to the community (CommunityUser model?), such as `reputation` and mod/admin flags.
- The remaining models I'm seeing are currently: Notification, SiteSetting, Subscription, Tag, and possibly SuspiciousVote (depends on intended use).

Given the above, community_id fields would only need to be established for Post, CommunityUser, and the 4 (or 5) remaining models listed above.

@ArtOfCode- do you see anything missing with this approach?

**Comment by ArtOfCode-** [comment]
@pinnymz I'd disagree with the first of your points there, but otherwise that looks good. I think we should have a `community_id` on all tables that are specific to a community - you're right that it does introduce potential data integrity violations, but those can be dealt with using validations in the models and refusing to save if the community_id is incorrect. Having the community ID cached on each model will result in better performance.

Good call on the CommunityUser model - that's not one I'd thought of, but of course it does need to be done to separate contributions per site.

Remaining models:

 * Notification, Privilege, Subscription, and Tag all definitely need a `community_id`.
 * SiteSetting should have one as well, but you'll need to give some thought to the way SiteSettings are accessed. It's currently done via a helper, so that a SiteSetting can return a correctly-typed value by calling `SiteSetting['SelfVotesEnabled']` - you'll need to think about how to integrate community-specific settings into that. There'll also be some settings that should apply to all communities, so the `community_id` column should allow nulls.
 * SuspiciousVote you can ignore. It's not in use, and it's on my list as a thing I need to remove entirely.

**Comment by pinnymz** [comment]
@ArtOfCode- very well, proceeding as stated. 

Next question, are we 'for' or 'against' the usage of a `Thread.current` store as an alternative to passing contextual information about the community_id in use.  

Perfect example of this would be the SiteSetting helper method you mentioned above.  Using standard DI techniques, the above syntax would need to change to either use some instance of SiteSetting passed down via context (contexts on class objects are not thread safe), or explicitly pass the community_id which requires a revised class method syntax.  Using `Thread.current` would avoid these issues completely.  However, I am aware that many in the OO world are strongly against the use of `Thread.current` as they consider it an anti-pattern.

So... I'm asking if you have any requirements or guidance here.

**Comment by ArtOfCode-** [comment]
@pinnymz If it

 - works, and
 - is safe, and
 - performs well

then I don't really mind how it gets done. It crossed my mind to wonder whether it's possible to write the method such that it could be called like `SiteSetting[@community.id, 'SettingName']` - but I have yet to actually look into that.

**Comment by pinnymz** [comment]
@ArtOfCode- There's no question that `Thread.current` is much less invasive.  It's safe when used properly (initialization required at the start of each request, via before_action).  And there is no performance impact.  I'll run with it.

PS Yes, you can absolutely customize the call to `SiteSetting[]` if you modify the method signature like so:
`def self.[](community_id, name)`.
