### ISSUE TITLE
Inform user that 15 characters are required for some flag types

### ISSUE THREAD

**Issue by trichoplax** [codidact/qpixel#1000]
**Is your feature request related to a problem? Please describe.**
When flagging a post, some of the radio buttons result in the "Details" field being required to have at least 15 characters, but the user is only informed of this after trying to submit the flag.

![Flag modal for a question showing 5 radio buttons](https://meta.codidact.com/uploads/r1at8ztfdlzqtk3b9h9zoxthviai)

**Describe the solution you'd like**
When the details are optional, the field can remain as currently:

> Details?
> You might want to add some details to your flag.

When the details are required, drop the question mark and replace the second line with the character requirement:

> Details
> (minimum 15 characters)

**Describe alternatives you've considered**
We considered reducing or dropping the character requirement but that could cause problems for some flag types (specifically "needs author's attention" as that leads to a comment being created) so for now we can simply keep the user better informed.

**Additional context**
[Discussion on Discord](https://discord.com/channels/634104110131445811/668890340199235613/1070488182552002591)

**Comment by cellio** [comment]
Some reactions require comments which also must be at least 15 characters, and right now we fail with a 422 that the user might not see.  Is there a common path here?  That is, thing that requires comment -> enforce comment length -> proceed ?  Or do we have to check each case separately?

**Comment by cellio** [comment]
Now that minimum flag length is 1, reaction comments are handled, and the "needs author's attention" flag is gone, have we covered everything?
