### ISSUE TITLE
Flagging as duplicate does not require details

### ISSUE THREAD

**Issue by trichoplax** [codidact/qpixel#1001]
**Describe the bug**
It is possible to flag a question as a duplicate without specifying any details, which means there is no link to another post.

**To Reproduce**
1. Go to a specific question page
2. Click on Flag
3. Select the radio button "is a duplicate"
4. Enter no text in the "Details" field
5. Submit the flag successfully

**Expected behavior**
Selecting "is a duplicate" should result in the "Details" field being required, as it is for "needs author's attention" and "other reason".

**Screenshots**

![Flag modal for a question showing 5 radio buttons](https://meta.codidact.com/uploads/r1at8ztfdlzqtk3b9h9zoxthviai)

**Comment by cellio** [comment]
This feels like a regression; I have memories of testing this to make sure we required it at some point.  When?  No idea.

**Comment by MoshiKoi** [comment]
No longer able to reproduce, is this still an issue?

**Comment by trichoplax** [comment]
Just tested in production with one of my own posts - I get the same error message as you.
