### ISSUE TITLE
Question preview shows escaped HTML

### ISSUE THREAD

**Issue by cellio** [codidact/qpixel#1008]
https://meta.codidact.com/posts/287458  
https://meta.codidact.com/posts/287670

If the beginning of a post contains special characters like `&`, the post preview shows the HTML encoding (`&amp;`) instead.  The linked meta questions include screenshots; here's one of the questions shown in the screenshot in the first post: https://linux.codidact.com/posts/287409 .

**Comment by MoshiKoi** [comment]
This line is where the preview is rendered:

https://github.com/codidact/qpixel/blob/dd905a7504b204001d51ac50462d26e1a9adf52a/app/views/posts/_list.html.erb#L40

The call to `truncate` makes the string unsafe, and so Rails escapes us for us. We can just sanitize it again, e.g.

```erb
<%= sanitize(strip_tags(post.body).truncate(SiteSetting['PostBodyListTruncateLength'] || 200), scrubber: scrubber) %>
```

(Tested on my own dev instance and it does fix the issue)

**Comment by cellio** [comment]
Sounds good to me.  Any reason not to do it that way?

**Comment by Taeir** [comment]
Sounds like a good solution to me.

**Comment by cellio** [comment]
Sounds good.  @MoshiKoi do you want to prepare a PR?
