### ISSUE TITLE
Mathjax not rendered correctly in question previews on post lists

### ISSUE THREAD

**Issue by cellio** [codidact/qpixel#1022]
https://math.codidact.com/posts/287481

On Math, formulas are not being shown correctly in question previews, though they are fine in the question pages.  A comment there says:

> View Source shows that the raw HTML being sent to the browser is `A parabola is given by $y^2=2px$ with $p&gt;0$. The point $D$ is on the parabola in the first quadrant at a distance of $8$ from the $x$-a...` so the problem is a double-escaping.

**Comment by cellio** [comment]
We turned off previews on Math for now.

**Comment by trichoplax** [comment]
Discussion on Discord:
https://discord.com/channels/634104110131445811/634104110131445815/1115804745270038639

Summary:
This bug doesn't exist anymore, but we should still leave previews switched off on math.codidact.com until the very tall MathJax previews problem is fixed:
https://math.codidact.com/posts/287515/287516#answer-287516
