### ISSUE TITLE
Default filters for anonymous visitors

### ISSUE THREAD

**Issue by cellio** [codidact/qpixel#1043]
I'm not sure if this should be moderator-level or admin-level, but could we add a setting for a default filter for anonymous visitors (i.e. not logged in)?  This would allow communities to make a better first impression if they have lots of downvoted or closed questions.

We could then possibly extend this to apply for new users too (definition TBD), but we'd need 
 https://github.com/codidact/qpixel/issues/1042 first.

**Comment by trichoplax** [comment]
I'm not sure how much of a problem this would be, but something to weigh against the benefits:

Imagine I'm a new user who doesn't know anything about the site yet.
- I ask a question
- I close the page
- I come back the next day to see how my question is doing
- My question is gone, and I am very confused

In reality, my question was either closed or downvoted, with some helpful comments added to explain to me what I need to improve. However, it didn't occur to me to sign in so I can't see my question. Thinking my question is gone, I don't sign in, so I'll never know.

**Comment by trichoplax** [comment]
Another potential problem (I'm not sure how real new users would react, so this is just my initial thought):

Imagine I'm a new user who doesn't know anything about the site yet.
- I arrive at a community filled with happy upvoted questions and decide to ask one of my own
- I sign in, and am suddenly confronted with a wall of heavily downvoted and/or closed questions
- I wonder how to get back to the happy community I wanted to post my question in

Hopefully this one will be mostly mitigated by #1042 in combination with filters for new users, but it still leaves me feeling wary of non-explicit filtering.

As a new user, would I be put off more by seeing downvoted posts immediately, or by discovering shortly afterwards that they have been hidden from me? (I don't know the answer - perhaps worth asking around.)

As a new user, would I run away if I see downvoted posts, or would I read through the comments on them to learn what to avoid in my own posts? (Again, I don't know the answer.)
