### ISSUE TITLE
Add more information to "remember me" button on sign-in

### ISSUE THREAD

**Issue by cellio** [codidact/qpixel#1045]
https://meta.codidact.com/posts/287702

When you sign in you can check a box labelled "remember me".  This can mean a few different things across the web -- have the browser remember your username, stay signed in (for a period of time or "forever"), maybe other things.  Can we adjust the text to be more specific about what we mean?

I believe (based on my experience) that we mean "stay signed in (unless you lose your cookies)".  I've seen "stay signed in on this device" elsewhere.

Changing the text next to that box is presumably easy, but I do want to confirm what it does first.

**Comment by cellio** [comment]
Huh, I can't find this text, though I did find a reference to `Devise::Controllers::Rememberable` so it's possible it's baked into some library we're using?

**Comment by ArtOfCode-** [comment]
Text should be in app/views/devise/sessions, IIRC

**Comment by cellio** [comment]
> Text should be in app/views/devise/sessions, IIRC

It is, but it's indirect:

```
  <% if devise_mapping.rememberable? %>
    <div class="form-group">
      <%= f.label :remember_me, class: "form-element" %>
      <%= f.check_box :remember_me, class: "form-radio-element" %>
    </div>
  <% end %>
```
I haven't found where the string is set for `:remember_me`.

**Comment by cellio** [comment]
Ok, I _really_ don't know where to look for that string:

```
$ grep -R remember_me --exclude-dir=log
./app/controllers/users_controller.rb:      remember_me user
./app/controllers/users_controller.rb~:      remember_me user
./app/views/devise/sessions/new.html.erb:      <%= f.label :remember_me, class: "form-element" %>
./app/views/devise/sessions/new.html.erb:      <%= f.check_box :remember_me, class: "form-radio-element" %>
./config/initializers/devise_example.rb:  config.expire_all_remember_me_on_sign_out = true
./config/initializers/devise.rb:  config.expire_all_remember_me_on_sign_out = true

$ grep -R "Remember me" --exclude-dir=log
```
(That's right -- no matches.)

**Comment by ArtOfCode-** [comment]
It's implicit based on the checkbox name (i.e. the `:remember_me`). Rails by default just humanizes that and shows it. IIRC you can add an extra argument to customize the text:

```erb
<%= f.check_box :remember_me, 'Remember account on this browser', class: 'form-radio-element' %>
```
