### ISSUE TITLE
Sorting by age or score doesn't work in a search

### ISSUE THREAD

**Issue by sarahmccuan** [codidact/qpixel#105]
1. Go to (https://outdoors.codidact.com/posts/search)
2. Search for a common term and view results 
3. Click one of the sorting buttons (age or score)

**Expected behavior**
Posts and answers are sorted by their age or score 

**Actual behavior**
No sorting is applied 

**Screenshots**
![image](https://user-images.githubusercontent.com/35535105/86197992-9fa79c00-bb24-11ea-9d2f-9273bfd64156.png)

**Comment by galegosimpatico** [comment]
norepro - looks fixed - consider closing
