### ISSUE TITLE
Not allowed to save a blank tag wiki

### ISSUE THREAD

**Issue by MoshiKoi** [codidact/qpixel#1060]
If you type anything into the tag wiki textbox while editing, and then delete it, it will not allow you to save the tag, showing a greyed out Save button and a red text area.

![image](https://github.com/codidact/qpixel/assets/54333972/a979eb6c-7dc8-4cad-ab00-573bf756c6a0)

I believe this is caused by the same issue as #945, caused by it trying to apply post validation to the tag wiki.

**Comment by lorenzodonati** [comment]
I noticed it several times, too. 

Reloading the page displays a "draft loaded" message and the save button becomes active and you can save the blank wiki without problem. I use Firefox 113.0.2.
Hope this helps.

**Comment by Oaphi** [comment]
This is not a bug with applying validation, this is an issue of not passing correct values (like, at all) to character counter.
The default for `mdhint` is 30 and 30K chars for min and max boundaries respectively. We just need to pass the proper values (Easy to tackle for me as I've made char_count a proper partial).

**Comment by Oaphi** [comment]
On a related note, we should probably not allow to create tag wikis of 30K chars or _at the very least_ limit it to 30K chars as currently we only have the DB's restriction of 65 535 single-byte chars to work with, leading to things like in the attached 
![Screenshot from 2024-08-03 16-16-23](https://github.com/user-attachments/assets/75e2f70d-4ee9-42c7-88d7-414fb9576bbc)
screenshot.
