### ISSUE TITLE
Allow minimum title length to be lowered

### ISSUE THREAD

**Issue by cellio** [codidact/qpixel#1069]
https://proposals.codidact.com/posts/288369

*Most* of the time, 15 characters is a perfectly reasonable minimum length for titles -- most top-level posts are questions and it's really hard to meaningfully express a question in just a few characters.  However, for articles, blog posts, recipes, or -- as in this case -- site proposal names, we'd like to be able to set that limit lower.

I didn't find a knob for this in Site Settings.  Ideally the limit would be settable per post type or per category, but if that's too hard, a site-global setting with cautions around it would be ok.

**Comment by ArtOfCode-** [comment]
Closed by c371c75b
