### ISSUE TITLE
Two links to Meta Proposals category from codidact.com 404 when signed out

### ISSUE THREAD

**Issue by trichoplax** [codidact/qpixel#1076]
**Describe the bug**
The 2 links from codidact.com to https://meta.codidact.com/categories/10 (the Site Proposals category of Meta) now only work when signed in - otherwise they give a 404 page.

**To Reproduce**
1. Go to https://codidact.com/ while not signed in (for example, in a private browsing window)
2. Find one of the two links "Site Proposals" or "Site Suggestions" and click on it
3. See a 404 page at https://meta.codidact.com/categories/10

**Expected behavior**
These should probably now point to the new Proposals community at https://proposals.codidact.com/ which works whether signed in or not.

**Comment by cellio** [comment]
Whoops.  I knew we still had a link to update there but missed that it would now 404.  I'll fix that.

**Comment by cellio** [comment]
Fixed in https://github.com/codidact/community-list/commit/74ed9ecd0ba3e43e0ea5dafba20ea34e1bb6feff; needs to be deployed.

**Comment by cellio** [comment]
This has been deployed now.
