### ISSUE TITLE
Redundant filter fetches

### ISSUE THREAD

**Issue by trichoplax** [codidact/qpixel#1082]
**Describe the bug**
When there is no user signed in, we still try to fetch the user filters from the server. Raised following review notes on #1079.

**Expected behavior**
Before fetching the user filters, we check the user id stored in the HTML and only proceed if it exists (is not "none").

**Comment by trichoplax** [comment]
[Example of this same check for preferences](https://github.com/codidact/qpixel/blob/develop/app/assets/javascripts/qpixel_api.js#L208):

```js
    // Do not attempt to access preference if user is not signed in
    if (document.body.dataset.userId === 'none') {
      return null;
    }
```

**Comment by Oaphi** [comment]
Working on it, should be good to go around the end of the next work week. There is also a closely related issue I noticed of still trying to fetch default filters while logged off, so it will be amended too.

**Comment by cellio** [comment]
Resolved with https://github.com/codidact/qpixel/pull/1120.
