### ISSUE TITLE
Remove minimum length for custom flags

### ISSUE THREAD

**Issue by cellio** [codidact/qpixel#1103]
We require a minimum length for most textboxes and a larger discussion about that is happening on Meta.  One specific place where it causes friction is on flags where custom text is required, as noted here:

https://meta.codidact.com/posts/287837

Flags go to moderators, not the public, and moderators can accept or decline them.  Given that, I think it's ok to accept a terse flag; if the flagger can convey meaning in under 15 characters, go for it.   Let's set the minimum to 1 (so you have to type _something_ for a custom flag) - thanks to trichoplax for the suggestion in a comment.

If the check were in the client-side code I'd just submit a PR (it looks like the relevant code is in `app/views/posts/_expanded.html.erb`), but I don't know how to find that check/enforcement in the backend.  Education welcome!

**Comment by trichoplax** [comment]
How about changing the minimum from 15 characters to 1 character, so your custom flag can be as terse as you like but it still reminds you to write *something*?

**Comment by cellio** [comment]
Related: https://github.com/codidact/qpixel/issues/1000

**Comment by Taeir** [comment]
https://github.com/codidact/qpixel/blob/e1874749cb70df7dcb791880d4f2e4ab9d4f429b/app/views/posts/_expanded.html.erb#L318
is the creation html. Logic is in javascript, https://github.com/codidact/qpixel/blob/e1874749cb70df7dcb791880d4f2e4ab9d4f429b/app/assets/javascripts/flags.js#L31
Limit seems to be statically set there. 

There is no server side validation on this. It would be added as a validation in `app/models/flag.rb`
