### ISSUE TITLE
.ico missing in codidact.com, co-design docs, and the photography community

### ISSUE THREAD

**Issue by jcezarms** [codidact/qpixel#111]
**Is your feature request related to a problem? Please describe.**
This is a nitpick, but somewhat important design-wise.

**Describe the solution you'd like**
The [`.ico`](https://www.codidact.org/favicon.ico) that's already set in [codidact.org](https://codidact.org) (and most communities therein) should be reflected in:
- [codidact.com](https://codidact.com)
- [design.codidact.org](https://design.codidact.org)
- [photography.codidact.com](https://photography.codidact.com/)

**Describe alternatives you've considered**

--

**Additional context**
This is codidact.org on Chrome (v83.0.4103.116):
![image](https://user-images.githubusercontent.com/25608481/87463010-2b223200-c5e7-11ea-8cb3-bd2fb30e92b8.png)

This is codidact.com (and similarly, any member of the list up there):
![image](https://user-images.githubusercontent.com/25608481/87463320-9bc94e80-c5e7-11ea-8407-b054446885a0.png)

I haven't investigated Codidact's architecture enough to know where the icon should go for each site. Also, hopefully this is the appropriate repo for the issue.

**Comment by luap42** [comment]
This makes sense. FWIW, design.codidact.org is somehow different (not a Q&A-related thing, but our design system) and I think might not need the icon, because it is somehow independent. But that’s just my opinion. :)

**Comment by luap42** [comment]
(Fixed this for photography.codidact.com, at codidact.com I'll look later)

**Comment by ArtOfCode-** [comment]
Fixed
