### ISSUE TITLE
Inform the user of disallowed HTML

### ISSUE THREAD

**Issue by MoshiKoi** [codidact/qpixel#1140]
There have been a lot of question on Discord and Meta about posts being different from what was shown in the preview. Currently, due to the way we handle submissions, differences between the post preview and the actual post comes from sanitization.

Could we have something that automatically detects when the sanitizer would remove content, and inform the user? We could do this either client-side or server side.

On the client side, we could have a script to detect when the preview contains disallowed tags and attributes, in accordance with https://meta.codidact.com/posts/277420. This would give live feedback, but could suffer from any discrepancies between the "client sanitizer" and the true sanitizer.

On the server side, we check that the submitted HTML is the same before and after sanitization, and if different, we would inform the users similar to how we inform the user when they are submitting an image without alt text. This would be accurate, but only catchable when the user hits the submit button.

**Comment by cellio** [comment]
The image checker is an apt analogy: let's treat this as a validation step when the user is ready to submit the post, rather than trying to keep a client check in sync with the one the server's going to do.

We could also look for a place in the editor to add some guidance or a link to help or something.  I mean something static, not something dynamic that reacts to user input.

**Comment by MoshiKoi** [comment]
Interestingly, there already is a client-side list of allowed html and stuff used to try to synchronize client and server sanitization

https://github.com/codidact/qpixel/blob/ee95501112973ddc7b9470647df29222e972f22d/app/assets/javascripts/posts.js#L1-L6

This is then used here:

https://github.com/codidact/qpixel/blob/ee95501112973ddc7b9470647df29222e972f22d/app/assets/javascripts/posts.js#L148C1-L152
