### ISSUE TITLE
Minimum length requirements are not shown to the user

### ISSUE THREAD

**Issue by MoshiKoi** [codidact/qpixel#1145]
Re: https://proposals.codidact.com/posts/289061

Minimum length requirements are not shown to the user for post titles (and post content, comments, and probably everywhere else that has a requirement, though I haven't checked); it just makes the text box turn red.

Could we display this information somewhere? We already have a display for when the user has *more* characters than the limit, so there shouldn't be a UI problem in triggering a similar display for when the user has less.

**Comment by Oaphi** [comment]
Claiming this. I intend to add an abstraction for character counter that can work with both min & max values. Also, the current handling of minimum / maximum number of characters is overly simplistic, unfortunately, as it relies on `length` accessor, which is well-known to not work very well with surrogate pairs (the competing Stack Exchange network is plagued with it too, I even made a userscript fixing that, so it's just a matter of aligning the logic with it: https://stackapps.com/q/9100/78873).
