### ISSUE TITLE
Existing filters aren't available in a new browser until you create a new one

### ISSUE THREAD

**Issue by cellio** [codidact/qpixel#1215]
meta:288530

In the Meta report, the user created filters in a desktop browsers, tried to access them on a phone, and didn't see them until after creating a new one on the phone.  The filters are stored server-side, but weren't fetched on first use, only on first edit.

I think this is not specific to desktop source and phone destination, so I've written the title more generally, but I haven't verified that.  Can we sync when the user opens the filter expander, rather than waiting for a write?  Would that be too many server calls?

**Comment by MoshiKoi** [comment]
Huh, thought this was fixed by #1079. Is this still occurring?

**Comment by cellio** [comment]
Oh, that's the same meta post and I missed that we had fixed it.  Sorry, I'll treat this as a duplicate.

**Comment by MoshiKoi** [comment]
Closing since linked Meta issue is status-complete
