### ISSUE TITLE
Trust levels/abilities

### ISSUE THREAD

**Issue by ArtOfCode-** [codidact/qpixel#123]
## Giant Thread of Things To Think About

[Discord discussion](https://discord.com/channels/634104110131445811/676843271762214932/737478897876074496)

A broad overview of things that will need doing:

* remove rep DB fields, calculations, callbacks, site settings
* create abilities DB table, associations, definitions
* create site settings (or specific abilities settings? TBD) for thresholds
* figure out how and when to calculate ability grants, because that's going to be a super-heavy calculation if we have all the thresholds we've talked about
* new help documents (some of them might be written?) to be added in
* debugging for 6-8 weeks

If we're doing abilities rather than true trust levels as [suggested here](https://meta.codidact.com/a/276209/276675) then the calculations are different (cheaper?).

For flexibility, an abilities model design might work along these lines:
 * `id`, `community_id`, `name`
 * `related_type` i.e. `Post`, `Edit`/`SuggestedEdit`, `Flag` etc. Method `fields_for` returns the fields on the target table where you can find good/bad status (or score).
 * `threshold` - what value you have to hit before you get the ability
 * `parent_id` - points to a _lower_ ability, i.e. one you get _before_ this one - this way you don't have to run the calculation for this ability if the user doesn't already have `parent_id`.

Scheduling:
 * daily?
 * schedule a recalc on events that might affect it? (i.e. user edits post/suggests edit, their user ID is added to a redis-cached list of UIDs to recalc at the end of the day)
 * spread somehow?

Calculating:
 * cache historical counts, query counts since then? is this more or less expensive?
 * cache historical _scores_, query score since then? possible? more/less expensive?

**Comment by cellio** [comment]
Updated functional spec: https://github.com/codidact/docs/wiki/Functional-Spec:-Granting-Privileges-(Abilities)-(Take-2)

**Comment by cellio** [comment]
According to comments there, this feature will also fix https://meta.codidact.com/questions/278230.  We need to remember to check that and mark it complete when this lands (or file an issue if this doesn't fix it).

**Comment by cellio** [comment]
There was a big branch for abilities and it landed last month, so I'm closing this.  If there's anything left to do, please file new issues.
