### ISSUE TITLE
network-wide search

### ISSUE THREAD

**Issue by cellio** [codidact/qpixel#1255]
meta:289142

This request is for some form of network-wide search, to augment per-community search.  We'll need to flesh out what search options can and can't be supported globally; I suspect that tags and categories are out but users and votes are in (along with text of course).

We don't really have a "network" concept in the UI as distinct from individual communities, but the dashboard mimics network-wide behavior even though it's hosted on an individual community.  That might be confusing for search, though, since we already have community-specific search.  Global search might not be possible until we build out a real network view, which is also relevant to https://github.com/codidact/qpixel/issues/284 .

**Comment by peterelbert** [comment]
Interested in accepting this issue to work on @cellio

**Comment by cellio** [comment]
Thanks @peterelbert .  I think a good first step here would be to flesh out a functional design -- how would this work, where would it be plugged in, what restrictions on search language would be needed, etc.

**Comment by Oaphi** [comment]
Closing this in favor of #1372 as it's more fleshed out in terms of how it could work.
