### ISSUE TITLE
Counter on editing tag summaries is always 0

### ISSUE THREAD

**Issue by cellio** [codidact/qpixel#1261]
Most editing textboxes (posts, comments, etc) now show a counter so you know when you've reached a minimum length or exceeded a max.  However, the counter on tag summaries (the short description) doesn't work; it stays at 0/600 while I type.  The long tag description, on the other hand, correctly shows progress toward the 30,000-character max:

![screenshot](https://github.com/codidact/qpixel/assets/5557942/2d7abf7e-d291-44ea-9798-4092964ad78e)

I wonder if this has something to do with the backing element type -- I notice that the summary and description also use different font faces, so the UI apparently "thinks" they're different kinds of things.  I don't know if that's relevant.

Possibly related for a fix: https://github.com/codidact/qpixel/pull/1189  .  The bug predates that change.

**Comment by Oaphi** [comment]
huh. Assigning to myself as I've recently tackled #1189

**Comment by Oaphi** [comment]
@cellio yup, I do know how to address that — already done (and threw in a couple more improvements along the way), awaiting review.
