### ISSUE TITLE
Link to RSS Feed on Homepage is Confusing

### ISSUE THREAD

**Issue by ThomasOwens** [codidact/qpixel#129]
**Describe the bug**
There are no questions yet, so I cannot yet tell if this is a UX issue or a functional issue.

**To Reproduce**
1. Go to the Software Development Codidact: https://software.codidact.com
2. Observe the text of the RSS feed: "Category RSS feed"
3. View the URL that this link goes to: https://software.codidact.com/categories/38/feed.rss

**Expected behavior**
It is not clear what the "category RSS feed" is. I expect this to either be a feed of newly posted questions or recently active questions and the text of the link to be clear as to what the feed represents.

**Screenshots**
![RSS Link](https://user-images.githubusercontent.com/35041/89655907-c7fb8680-d898-11ea-860f-9d06aa65cff3.png)

**Additional context**
Please make it clear what this feed represents. I'm expecting a feed that includes only newly posted questions. If that is what it is, the link text should be clear about that. If it's not, I'd expect such a feed to be added and the text for both feeds to indicate exactly what they represent.

**Comment by ArtOfCode-** [comment]
Done, pending deploy
