### ISSUE TITLE
Edit Profile -> Website link incorrectly gets https protocol added to it, each time save is clicked

### ISSUE THREAD

**Issue by DoctaJonez** [codidact/qpixel#13]
**Describe the bug**
"https://" gets prepended to the Website link field every time you click save on the edit profile page. 
 If you start out with codidact.org, when you click save it will become https://codidact.org, but then when you click save again, it will become https://https://codidact.org, each time save is clicked it will continue to prepend another https://.

**To Reproduce**
1. Go to Edit Profile
2. Enter a value in the Website link field, e.g. https://codidact.org
3. Click save
4. The value is now https://https://codidact.org

**Expected behavior**
The URL will either be what the user entered, verbatim, or it will check if the protocol is already specified in the specified URL.

**Comment by archielecroy** [comment]
PR with proposed fix #14
