### ISSUE TITLE
iOS app

### ISSUE THREAD

**Issue by peterelbert** [codidact/qpixel#1305]
**Is your feature request related to a problem? Please describe.**

Apps with good mobile versions are far more usable, in my experience. Mobile interfaces, when excellent, are a game changer. It could be a big advantage over Stack Exchange.

**Describe the solution you'd like**
A well-designed iOS app with features like push notifications and possibly some degree of built-in chat. Not some kind of third party app based on an API, but a sort of official app, with the same format as the website.

**Describe alternatives you've considered**
A progressive web app, or an open API for third party apps. Not bad solutions, but I’d like to see a genuine, native, flagship app.

**Additional context**
Perhaps some good framework for developing iOS apps for Ruby on Rails web apps? https://thoughtbot.gumroad.com/l/ios-on-rails

**Comment by ArtOfCode-** [comment]
Declining at the moment. We don't have the resources or time to work on or maintain separate apps.
