### ISSUE TITLE
Rails error "wrong number of arguments"

### ISSUE THREAD

**Issue by trichoplax** [codidact/qpixel#1308]
**Describe the bug**
Trying to run Rails with either `rails s` or `rails c` gives an error `wrong number of arguments (given 3, expected 1..2)`.

This may be due to the change in [how positional arguments are handled in Ruby 3](https://www.ruby-lang.org/en/news/2019/12/12/separation-of-positional-and-keyword-arguments-in-ruby-3-0/).

**To Reproduce**
1. Install QPixel following the installation instructions, with Ruby 3.3.0 (I used RVM on Fedora Linux).
2. Try to use `rails c` and see the following error message:
```
/home/trichoplax/.rvm/gems/ruby-3.3.0/gems/css_parser-1.11.0/lib/css_parser/regexps.rb:11:in `initialize': wrong number of arguments (given 3, expected 1..2) (ArgumentError)
```

This appears to be fixable by upgrading the `css_parser` gem. I'm not sure why my previous installations of QPixel with Ruby 3 have worked without this error though.

**Comment by peterelbert** [comment]
Does rails c depend on the Qpixel installation? Or just the gemfile?
Im new to Ruby but was under the impression rails c would just launch a console but wouldn't necessarily run a lot of app-specific things before launching. https://guides.rubyonrails.org/command_line.html

**Comment by trichoplax** [comment]
I'm not sure why opening the console from the terminal would depend on css_parser, but it may not be QPixel related. If I enter `which rails` I get the same location regardless of whether I am in the QPixel directory, and that location is where the gems appear to be stored. So it appears that `rails c` depends only on the gem file.

**Comment by trichoplax** [comment]
I suppose the link to QPixel is that `Gemfile.lock` in the QPixel repository specifies the version of the `css_parser` gem that is then shared by anything that uses the gem. I don't understand how gems work but the pull request updating `css_parser` fixes the problem on my machine.

**Comment by ArtOfCode-** [comment]
I can't remember if we support 3.3 or not - last I recall we upgraded to 3.1, can't remember if we've gone beyond that. Are you able to check with 3.1 and see if that works (and vice-versa, if you can - if you upgrade the css_parser gem and use 3.1, does that work)?

**Comment by trichoplax** [comment]
I've converted the associated pull request to a draft now that I understand that it is not needed until we upgrade Ruby.

Out of interest, I've just tested that the newer version of `css_parser` (1.16.0) works fine with Ruby 3.1.0 so there doesn't seem any reason not to upgrade earlier if desired (it's just not necessary).

**Comment by ArtOfCode-** [comment]
In that case let's upgrade the gem if it works with both. Wider support in this case is not a bad thing.
