### ISSUE TITLE
Users can set empty user names, causing chaos

### ISSUE THREAD

**Issue by cellio** [codidact/qpixel#135]
A user (Moshi) set the user name to blank (or spaces?).  This caused comments and posts to appear to be unsigned, including not having any place to click to get to the user profile.  One example is the first comment here: https://software.codidact.com/questions/277429.  Another is this post: https://languages.codidact.com/questions/277352.  The user has now restored a username, but something odd is still going on there -- note the placement of the name *after* the "edit" and "delete" links on the comment and after the reputation number on the post.

We shouldn't let users set empty or space-only user names.  There should always be *something* to display and link.  Can we require at least one printing character?

Further clarification from the user:
> For the empty nick, I used zero-width joiners because most whitespace is actually detected

**Comment by galegosimpatico** [comment]
> [...]
> 
> [...]. Can we require at least one printing character?
> 
> [...]

Not sure if [non breaking space][0] is printing or not, but to be sure: must be forbidden too?

<sub>Some computer defaults allow for a trivial insertion of a non breaking space (e.g. my laptop running macOS) while many others don't have such thing (I think that in every other setup I've used, entering a non breaking space simply using the keyboard was nontrivial).</sub>

/me not familiar with zero-widht joiners

cheers

[0]: https://en.wikipedia.org/wiki/Non-breaking_space

**Comment by Rhoxio** [comment]
Hey, new contributor here looking to get in on the action. (Found you all on Reddit)

If you'd like to add this to Trello, I have already come up with a validation solution on my local branch for the current situation. If we decide to add stricter validation, I can make the needed changes as we see fit. Blacklisting isn't generally very maintainable, but this would fix the issue for now. 

So far I have exempted: 

> U+200B zero width space
> U+200C zero width non-joiner Unicode code point
> U+200D zero width joiner Unicode code point
> U+FEFF zero width no-break space Unicode code point

This should allow for a clickable character to be present all the time. There may be a security concern allowing other unicode to be input, but we can tackle that if we feel it's a paramount issue at this point in development.

**Comment by ArtOfCode-** [comment]
All yours, @Rhoxio - https://trello.com/c/gkvh7eEY/211-disallow-empty-user-names

**Comment by Rhoxio** [comment]
Checking to let you all know that the pull request is up: https://github.com/codidact/qpixel/pull/160

**Comment by cellio** [comment]
PR was merged so closing this issue.
