### ISSUE TITLE
Default mod warning message refers to old proposals category

### ISSUE THREAD

**Issue by trichoplax** [codidact/qpixel#1356]
**Describe the bug**
When issuing a moderator warning for "Many off-topic posts", there is a default wording that the moderator can modify or send as is. This contains a link to the category on Meta where proposed new sites were posted in the past, before this was replaced with a separate Proposals community.

There is also a link to chat, which does not contain a destination URL. This would be easy to overlook, resulting in a broken link that directs back to the page you are already on.

**To Reproduce**
1. As a moderator, go to a user page and click Moderator Tools, then "warn or suspend user".
2. Select the "Many off-topic posts" template.
3. Under "Review the message", notice the problems mentioned, in the third paragraph.

**Expected behavior**
- The out of date link could be updated to point to the new Proposals community.
- The chat link could either be changed to plain text so that forgetting to enter a destination doesn't lead to a confusing link back to the page you are already on, or a valid URL could be included in the default wording.

**Comment by cellio** [comment]
`db/seeds/warning_templates/off-topic.md`.
