### ISSUE TITLE
RTL directives in a username overflowed into the UI

### ISSUE THREAD

**Issue by cellio** [codidact/qpixel#136]
![Screen Shot 2020-08-22 at 9 44 05 PM](https://user-images.githubusercontent.com/5557942/90969106-a4eceb80-e4c2-11ea-841c-557d5812b243.png)

In this screenshot, the UI elements ("delete", "edit", and posting time) are reversed.  That is from a comment here: https://meta.codidact.com/questions/277420.  The user was playing with RTL directives in usernames:

> I simply added U+202E (right-to-left override) and ihsoM (the ltr override flips my nick, but i didn't expect it to flip everything else)

Since some languages require RTL directives we probably should allow these in usernames, *but* we ought to fence them so they can't leak out and cause shenanigans. :-)

**Comment by galegosimpatico** [comment]
Assignees read https://github.com/codidact/qpixel/pull/157.

**Comment by cellio** [comment]
What still needs to happen here?

**Comment by galegosimpatico** [comment]
[Coding the fix][0], unless it's somehow wired in already (if so, shouldn't be able to reproduce anymore).

Problem is also sighted in the `A quiet enigma. We don't know anything about USER yet.` placeholder of the profile page, where it can turn into `A quiet enigma. We don't know anything about .tey USER/RESU/ETC`.

[0]: https://github.com/codidact/qpixel/pull/157#issuecomment-683179647

**Comment by ArtOfCode-** [comment]
a624079f8cafce185a42bcf3e4f1a1ea8c9e80d8

**Comment by galegosimpatico** [comment]
Nope. https://github.com/codidact/qpixel/commit/a624079f8cafce185a42bcf3e4f1a1ea8c9e80d8 results in `A quiet enigma. We don't know anything about  tey.USER` instead of `A quiet enigma. We don't know anything about .tey RESU`. But you want `A quiet enigma. We don't know anything about USER yet.`. Similarly, comments don't get fixed.

**Comment by ArtOfCode-** [comment]
Not deployed yet

**Comment by galegosimpatico** [comment]
just witnessed, only in Safari Version 13.1.2 (15609.3.5.1.3)

[discovered by MathPhysics in older Safari on iOS](https://discord.com/channels/634104110131445811/634104110131445815/756084425401303050)

consider reopening?
