### ISSUE TITLE
Fix code scanning alert - storage of SE API secret

### ISSUE THREAD

**Issue by Oaphi** [codidact/qpixel#1374]
Tracking issue for:
- [ ] https://github.com/codidact/qpixel/security/code-scanning/46

Minor thing but yeah, we should probably not store the secret in plain text (although it's a bit way too much work for little benefit. Still, somebody might want to tackle it).

**Comment by ArtOfCode-** [comment]
False positive - this doesn't result in the secret being exposed anywhere.
