### ISSUE TITLE
When saving drafts for posts, we should also save the title and tags

### ISSUE THREAD

**Issue by Oaphi** [codidact/qpixel#1395]
meta:292446

When saving drafts, we only consider the post body. It's, indeed, a problem that users can lose some (although not much) work over an issue that causes them to reload the page.

**Comment by trichoplax** [comment]
Could we also save the licence while this change is being made? That's the only other field on a saved post that might be surprising if reset to default for a user who has previously changed it.

**Comment by Oaphi** [comment]
> Could we also save the licence while this change is being made

Yup, I believe we can - good idea, added to the list of fields to persist!
