### ISSUE TITLE
Support more "me" links

### ISSUE THREAD

**Issue by ArtOfCode-** [codidact/qpixel#1439]
meta:292843

Add "me" links for at least all the public user-profile tabs, ideally the private tabs as well.

**Comment by trichoplax** [comment]
I haven't looked into this, but some info from a first glance that I posted in a comment on the Meta post:

> For anyone thinking of working on this, the [routes file](https://github.com/codidact/qpixel/blob/develop/config/routes.rb#L179) already has routes containing `me` for at least some of the user page tabs mentioned. It's possible that this is already intended to work, and this feature request might actually be a bug.

**Comment by ArtOfCode-** [comment]
My thinking - the routes that have `me` should work already. For those that don't, there's a `set_user` handler in the controllers where this is relevant, which could be modified to substitute `me` for an ID if there's a user signed in.
