### ISSUE TITLE
Site crashes when no .git directory in qpixel root

### ISSUE THREAD

**Issue by katomaso** [codidact/qpixel#1472]
**Describe the bug**
The application expects to run from a git-cloned repository. Unfortunately, this is not always the case. Hence missing .git/ directory should not prevent the homepage from rendering.

**To Reproduce**
Simply delete the .git/ folder should suffice. I came across this when using git url directly in docker compose as following
```
services:
  qpixel:
    build:
      context: "https://github.com/codidact/qpixel.git"
      dockerfile: "docker/Dockerfile"
    ...
```
Now the server returns HTTP500. When I change the docker-compose build to a local folder that I manually cloned, the site works again.

**Expected behavior**
Should simply not display the commit/date information in footer of a homepage when no commit information was available?

**Additional context**
(This stacktrace should be relevant to the latest commit of now  92315f284cf51b4140ed50b2e22be75255e933c2)
**Date::Error: invalid date**
```
/code/app/helpers/application_helper.rb:201:in `parse'
/code/app/helpers/application_helper.rb:201:in `rescue in current_commit'
/code/app/helpers/application_helper.rb:198:in `current_commit'
/code/app/views/layouts/_footer.html.erb:18:in `_app_views_layouts__footer_html_erb__2126410167450275025_68440'
/code/app/views/layouts/application.html.erb:44:in `_app_views_layouts_application_html_erb__3284022082170505632_68280'
/code/app/controllers/categories_controller.rb:26:in `homepage'
```

**Comment by Oaphi** [comment]
Yeah, we should not crash if the latest commit is not available. We definitely haven't expected anyone to be using QPixel without having the repostiory checked out, so there isn't any error handing in the helper. Should be easy to fix, though

**Comment by katomaso** [comment]
🙏
