### ISSUE TITLE
Deleting a question does not mark answers as deleted

### ISSUE THREAD

**Issue by cellio** [codidact/qpixel#153]
A question with answers was deleted.  I had an answer there, and was surprised to see the answer still linked from my profile (and giving me reputation).  I followed the link and while the question was marked and styled as deleted, the answers were not.

I wondered if this were due to my admin status; maybe the software is showing me *precisely* what was deleted.  So I checked in an incognito window (not logged in).  The answer shows on my profile there but following the link returns a 403.

Since accessing the page via answers correctly returns a permission error, I think addressing this is low priority.  We don't care all that much about the rep effects.  The entries in the profile might confuse people sometimes, so I figure it's worth reporting.

For those who can see it, here's the question: https://judaism.codidact.com/questions/277460.

**Comment by cbortz** [comment]
It seems like this should be solvable via setting an association's `:dependent` option to `:destroy`, however the `answers` association is defined as an instance method rather than a true association. Any insight as to why this is? It looks like both `Question` and `Answer` inherit from `Post` and so I assume there's some STI magic happening, but I don't think that should prevent writing a proper association. Thoughts?

https://github.com/codidact/qpixel/blob/develop/app/models/question.rb#L14-L16

**Comment by galegosimpatico** [comment]
> [...] It looks like both `Question` and `Answer` inherit from `Post` and [...]

There are Posts:
https://github.com/codidact/qpixel/blob/d20f8a269e385011fd532ccca5d01430f4d7654e/db/schema.rb#L265-L316

There are post types:
https://github.com/codidact/qpixel/blob/d20f8a269e385011fd532ccca5d01430f4d7654e/db/schema.rb#L260-L263

For instance Articles, Questions... are titled Posts, Answers have no title but are Posts:
https://github.com/codidact/qpixel/blob/d20f8a269e385011fd532ccca5d01430f4d7654e/db/seeds/post_types.yml#L1-L5

Answers of a Question have it as `parent_id`, are of different `post_type_id`, have `NULL` `title`.

**Comment by galegosimpatico** [comment]
Remember not to push this unless having also `undelete` propagate un-deletion to child answers.

**Comment by cellio** [comment]
It's a little more complicated: undeleting a question should undelete answers *that were not separately deleted*.  It shouldn't automatically undelete all answers.  It'll need to check the pre-question-deletion state in the answer history.

**Comment by galegosimpatico** [comment]
DBA I'd favor depending on a direct boolean `post` field instead of in a known combination of values living in the histories tables, for simplicity, even considering how the field is going to be shared with the rest of post types.

**Comment by luap42** [comment]
Suggestion, how I would do this:

We add a helper function to the Post model named `deleted?` with this mock-code:

    def deleted?
      deleted || parent&.deleted || false
    end

Then we replace every other occurence of Post#deleted with Post#deleted?.

**Comment by galegosimpatico** [comment]
That's simple and expressive, it's really awesome, but unnecessarily query-intensive.

I would do that only on a budgeted instance, and having it being recorded in some list of easy pickings for "increase overall performance at the expense of larger schema complexity". I wouldn't do that in open source, specially when mission-declared not for profit. But that'd be just me.

**Comment by luap42** [comment]
Well AFAICT the Rails cache is quite good for that. We use that approach at various other places without disadvantages.

Maybe this becomes a problem with scaling, maybe it doesn't. If it does, we can change it later, too, can't we. We could also extra-cache it then, which improves the whole thing even more.

**Comment by cellio** [comment]
This hasn't been worked on in a while and it looks like the discussion took a tangent.  I'm closing this one in favor of https://github.com/codidact/qpixel/issues/342, where I have just copied @luap42's comment from here with the suggestion for how to fix it.
