### ISSUE TITLE
forbid listing answers

### ISSUE THREAD

**Issue by galegosimpatico** [codidact/qpixel#154]
**Describe the bug**
Answers can be set to be listed, breaking presentation of the category.

**To Reproduce**
**DON'T DO THIS IN PRODUCTION**
1. Go to category, e.g. http://localhost:3000/categories/5
2. Have at least a question answered in the category.
2. **DON'T DO THIS IN PRODUCTION** Edit category, set answers listable ('Listed post types'). Save.
3. Back to step 1, boom.
4. Havoc can be trivially solved by having answers unlistable back again.

**Expected behavior**
Save category failed somehow.
Or maybe save category didn't fail and answers were listed somehow.

**Screenshots**
Will add upon request.

**Server:**
- OS: macOS.

**Desktop:**
 - OS: N/A.
 - [...]

**Smartphone:**
 - Device: N/A.
 - OS: [...]

**Comment by luap42** [comment]
Hm... no repro. Please add a screenshot.

For me, it just shows all the answers, too:

![grafik](https://user-images.githubusercontent.com/21335202/91302544-f63cf980-e7a6-11ea-812b-3f06e0df8ba5.png)

(oops. Saw the Don't Do This in Prod too late :D)

**Comment by galegosimpatico** [comment]
> [...]
> 
> (oops. Saw the Don't Do This in Prod too late :D)

My mistake, didn't ship notice when first written. 
🤦🏿🤦🏿🤦🏿

**Comment by galegosimpatico** [comment]
It was being caused by several Answer which had `parent_id` set `NULL`.

On SQL removal of those posts, the error went away and the category is shown.

I don't know or remember what caused the data inconsistency, if it wasn't me. Probably was me.
