### ISSUE TITLE
Tag display is pushed to the right on post pages

### ISSUE THREAD

**Issue by cellio** [codidact/qpixel#161]
Tags used to display under the post, flush left.  Now I'm seeing this:

![Screen Shot 2020-08-31 at 11 47 20 AM](https://user-images.githubusercontent.com/5557942/91739488-f90d6500-eb7f-11ea-9188-9204ca7323d6.png)

The editor username also wraps, which it wouldn't do if the tags were on their own line.

This looks particularly odd when there have been no edits:

![Screen Shot 2020-08-31 at 11 47 42 AM](https://user-images.githubusercontent.com/5557942/91739542-10e4e900-eb80-11ea-81a2-d95a60efd53d.png)

**Comment by galegosimpatico** [comment]
Reproduced.

**Comment by galegosimpatico** [comment]
Bisected to 9100edf7d2a1116dce380ae496de9e2dd1493750.
