### ISSUE TITLE
[dev server] Flag modal doesn't offer a way to back out

### ISSUE THREAD

**Issue by cellio** [codidact/qpixel#163]
![screenshot of flag modal](https://user-images.githubusercontent.com/5557942/91782659-b83b3d80-ebcb-11ea-9158-4ad2a03adf3d.png)

If I start to flag something and then change my mind, there's no way to cancel the dialogue -- no "x", no "cancel" button.  I have to reload the page to get rid of it.

This is on the dev server; this flags UI isn't in prod yet.

**Comment by ArtOfCode-** [comment]
What happens if you click on Flag again?

**Comment by cellio** [comment]
Dev's down right now; will check when it's next up.  (Didn't think of that; it might have been out of view, by which I mean scrolling not necessarily overlap.)

**Comment by cellio** [comment]
Clicking on flag again dismisses the modal.  So that's unintuitive but not a blocker. We should give the modals "x"s or "cancel" buttons or something obvious like that, but it can be follow-on work.  Do not block abilities on this.

**Comment by cellio** [comment]
Actually, it's true in prod too; it's just that there there's just a one-liner, not the whole moadl blocking other content, so I guess I just scrolled past it if I decided not to flag.

**Comment by sau226** [comment]
Is this issue still active? It looks like your workaround of "just click the flag button again" is still working on dev.
