### ISSUE TITLE
Imported posts do not sort correctly in the user profile

### ISSUE THREAD

**Issue by cellio** [codidact/qpixel#165]
In the list of posts on [my profile on Judaism](https://judaism.codidact.com/users/8046), the first post is currently +0/-0, above the next one which is +12/-0.  The first post was imported from SE.  I suspect that the imported score from SE (which is larger than our max score) is to blame; we're suppressing imported scores in the display in general, but they're still there.  I suspect this will affect other score-ordered lists too, like search results.

Suggested fix (I am neither a Ruby developer nor a DBA so take that into account):
- move "score" to a new column, something like "imported-score", for imported posts
- then compute the real score based on local votes to set "score" correctly

It'd be nice if in the future we could import upvotes and downvotes rather than score, but I understand that's a larger change.  Sidelining the imported score seems like a smaller (more practical?) change, hence this suggestion.

**Comment by ArtOfCode-** [comment]
Fixed - I thought I'd fixed this originally, but it turns out I'd set scores to 1.0 where the score was out of bounds, as opposed to correctly setting it to 0.5.
