### ISSUE TITLE
Inaccurate/outdated help text for search function

### ISSUE THREAD

**Issue by MoshiKoi** [codidact/qpixel#166]
On the search page https://meta.codidact.com/posts/search it says this:

> To further refine your search, you can use additional qualifiers such as `core:>1`. For example, the search `score:>=2 created:<1y grammar` would return only posts mentioning "grammar" that have a score >= 2 and were created less than a year ago.

However, on the help page https://meta.codidact.com/help/search, it says something different:

> Every post has a score between 0.0 and 1.0. To use this in search, you can use `score:0.5` to filter your search to only include posts with a score of at least 0.5.

There is a clear discrepancy between these two texts. Also, I'm pretty sure `core `is supposed to be `score`

**Comment by superplane39** [comment]
Addressed in #134

**Comment by cellio** [comment]
Addressed and merged there but not yet live on the site, even though there have been deployments since.  What additional piece do we need?

**Comment by superplane39** [comment]
> Addressed and merged there but not yet live on the site, even though there have been deployments since. What additional piece do we need?

According to @ArtOfCode- in chat, it's a site setting that needs to be manually edited on each site. It's correct in the seeds, which means any new sites will have it correctly set up when they're launched, but older ones needs to be edited manually by a (global?) admin. (At least, Art said you or luap could do it.)

**Comment by cellio** [comment]
Oh!  Sorry, missed that.   And I just found the setting, thanks.
