### ISSUE TITLE
Drafts don't save, despite the "draft saved" notice popping up

### ISSUE THREAD

**Issue by MoshiKoi** [codidact/qpixel#167]
Basically the title. Neither draft answers nor questions are saved, even though the notice appears that says "draft saved"

Tested on Microsoft Edge (Chromium) and Firefox 
(I also tried with my adblocker turned off, didn't help)

**Comment by galegosimpatico** [comment]
I agree.

Let's disable the label!

**Comment by ArtOfCode-** [comment]
Fixed
