### ISSUE TITLE
Enforce restrictions on what characters can be in tags at tag-creation time

### ISSUE THREAD

**Issue by cellio** [codidact/qpixel#168]
Somebody created a tag with a space in it, but attempting to apply that tag (via suggested edits) didn't work -- the edit couldn't be approved.  (The tag was "software practice" on Software Development, if anybody needs to dig into what happened.)  I don't know what other characters, besides spaces, aren't valid in tag names.  Whatever they are, let's check before creating the tag.

**Comment by galegosimpatico** [comment]
You could go the SE way for this, at least temporarily, and forbid every whitespace, notably (1) standard space, (2) tab, (3) line feed & carriage return & etc, (4) non-breaking space.

For the `software practice` particular case, I read there's a `software-practice` around. Maybe you want to merge those two.

**Comment by cellio** [comment]
Since adding the tag (with the space) to questions broke things and I don't understand what went wrong, I've been hesitant to try the merge through the UI lest I cause more problems.

**Comment by MoshiKoi** [comment]
There are no questions using the `software practice` tag, it's safe to just delete the tag rather than try merging, if that seems safer

**Comment by cellio** [comment]
Can't delete through the UI.  I think we need @ArtOfCode- 's input on how to safely remove the bad tag.

**Comment by ArtOfCode-** [comment]
Merging the bad tag into the good tag should also delete it

**Comment by ArtOfCode-** [comment]
Fixed
