### ISSUE TITLE
Last edited notice on post and post history don't match

### ISSUE THREAD

**Issue by MoshiKoi** [codidact/qpixel#174]
On https://meta.codidact.com/questions/277015, it shows the last person to edit as Moshi, 6 days ago. However, in the post history, it shows that pnuts edited it 3 days ago. 

![post page](https://user-images.githubusercontent.com/54333972/92658709-ded43500-f2ab-11ea-8eae-1988bf4d4b49.png)
![post history](https://user-images.githubusercontent.com/54333972/92658729-eb588d80-f2ab-11ea-8d0f-335d90e5cca7.png)

**Comment by ArtOfCode-** [comment]
Already fixed & deployed a few hours ago. Won't apply retroactively, though.

**Comment by ArtOfCode-** [comment]
https://languages.codidact.com/articles/277357

**Comment by cellio** [comment]
Is the new case because it's an article?  (I seem to recall that there's some stuff that gets done explicitly for questions and answers because we don't have a parent Post object to do it to.)

**Comment by MoshiKoi** [comment]
@cellio It affects answers too: https://languages.codidact.com/questions/278191#answer-278400

**Comment by MoshiKoi** [comment]
Another case: https://meta.codidact.com/questions/276824#answer-276995

**Comment by galegosimpatico** [comment]
[priority: high](http://github.com/codidact/qpixel/labels/priority%3A%20high)?

**Comment by cellio** [comment]
See new comment on https://github.com/codidact/qpixel/issues/214.

**Comment by cellio** [comment]
It is possible that https://github.com/codidact/qpixel/issues/214, which has a more specific diagnosis, explains this case too.  Not marking as a dupe *yet*, but if we fix that we should check to see if there are any more cases of this one.

**Comment by ArtOfCode-** [comment]
I _think_ that with #214 fixed and with the change to posts architecture, this should be fixed. Won't be retroactive, but should be no more cases - reopen if there are.
