### ISSUE TITLE
Attempting to merge a tag into itself spits out a server fault

### ISSUE THREAD

**Issue by donielf** [codidact/qpixel#175]
In attempting to merge a tag into itself, I instead received an error 500 Server Fault, with the accompanying error ID `16e9af53-6e7e-45ea-bf67-ddf171f033c5`. The tag was left unchanged through this process, and I didn't crash the site in testing this.

In contrast, when trying to set a tag as its own parent, I received an error message just saying that "you can't do that."

**Comment by galegosimpatico** [comment]
Hopefully resolved in #176.
