### ISSUE TITLE
Warn against manually editing versioned object docs

### ISSUE THREAD

**Issue by galegosimpatico** [codidact/qpixel#179]
> **Is your feature request related to a problem? Please describe.**

autogenerated docs are not labeled as such

> **Describe the solution you'd like**

autogenerated docs get labeled as such

> **Describe alternatives you've considered**

[have scripts generating object docs prepend a header comment warning such thing](https://discord.com/channels/634104110131445811/644016067441721344/753867761259905085)

> **Additional context**

[Spawns from here](https://discord.com/channels/634104110131445811/644016067441721344/753826056808562788)

**Comment by ArtOfCode-** [comment]
Eh, help articles are intended to be manually editable on each site so that sites can customize them to their needs. Needs a little bit of better management of updates, but the editing itself is not a fundamental problem.
