### ISSUE TITLE
Allow moderators to directly create tags

### ISSUE THREAD

**Issue by cellio** [codidact/qpixel#180]
The usual way to create a tag is to add it to a post.  This is the path we usually want people to take -- create the tag when you need it, to avoid clutter from speculative tags that never get used.  However, there are two use cases I'd like us to support:

1. Up-front creation of "special" tags.  While the meta ones (bug, feature-request, etc) are now seeded, we support the idea of special tags more broadly.  If a community wants to have special tags in other categories, they have to first use them and only then add them to the category definition, which isn't always convenient.  (Also, older communities don't have the meta seed; I just manually created "support" on Writing and there are only two status- tags there so far.)

2. *Planned* tag organization.  The Software Development community wanted a set of language tags up front, as a way of channeling people to the right tags, and IIRC Art added them directly to the database.  Other communities might, after discussion on their metas and otherwise after due consideration, want to create certain key tags, especially when building out tag hierarchies.

Allowing moderators to create tags before use would address both of these cases.  An intuitive place to hook it in would be a (mod-only) "create tag" link on the tags list, though it's ok if it goes in mod tools if that's easier.

**Comment by galegosimpatico** [comment]
[priority: medium](https://github.com/codidact/qpixel/labels/priority%3A%20medium)?
[complexity: average](https://github.com/codidact/qpixel/labels/complexity%3A%20average)?

**Comment by luap42** [comment]
I concur with the assessment of @galegosimpatico here. It’s more important than “nice to have” but (right now) not a deal-breaker. Needs some careful thoughts with regards to UI, but otherwise not too hard. There is already an automatic tag creation tool under /admin/setup FWIW, but limited to admins and some special Meta category tags.
