### ISSUE TITLE
Clarify Windows users should use Docker

### ISSUE THREAD

**Issue by LionelBergen** [codidact/qpixel#186]
Majority of desktop users overall are Windows users and so majority of people wouldn't read past "but Windows is unlikely to [have the installation work].".

Instead, tell Windows users to use Docker and link to those instructions. One of the key features of Docker is being platform independent.

Edit: Referring to the `README.md` file

**Comment by cellio** [comment]
This text is in the README file.

**Comment by galegosimpatico** [comment]
> Majority of desktop users overall are Windows users and so majority of people wouldn't read past "but Windows is unlikely to [have the installation work].".
> 
> [...]

There document is not targeting the body of all desktop users but the body of desktop and laptop users who are likely to read that document. The sentence is probably true and so what.

> [...]
> 
> Instead, tell Windows users to use Docker and link to those instructions. One of the key features of Docker is being platform independent.
> 
> [...]

* Telling Windows users to do insert stuff is not free and open source software but quite the opposite.
* Software must aim for operating system agnosticism.
* Windows developers know of Docker features power and dividends.

Hence strong against.

**Comment by cellio** [comment]
I don't think we should *tell* people what to do in the repo README, but it wouldn't hurt to link to info we already have or a Docker config or whatever as an option.  (I'm being a little hand-wavy because I don't know Docker and don't remember what we have where, just that somebody made it work.  I assume that left artifacts.)

**Comment by LionelBergen** [comment]
> Telling Windows users to do insert stuff is not free and open source software but quite the opposite

Sorry if this is a joke going over my head, but in case it isn't I'll clarify:

The README mentions Docker at the bottom, but windows users may not see that. Windows users will probably leave seeing the second sentence, 'does not build on windows'.

Instead of "cannot build on windows", lets make it "Windows users should use Docker" and have a link to: https://github.com/codidact/qpixel/tree/develop/docker, or link to the Docker section in the Readme.

> Software must aim for operating system agnosticism.
Currently your software says "Probably won't work on Windows" as the second sentence of the README so this is a little ironic.

> There document is not targeting the body of all desktop users but the body of desktop and laptop users who are likely to read that document. The sentence is probably true and so what.
Sorry could you clarify this?

**Comment by galegosimpatico** [comment]
> > [...]
> 
> [...]
> 
> The README mentions Docker at the bottom, but windows users may not see that. Windows users will probably leave seeing the second sentence, 'does not build on windows'.
> 
> Instead of "cannot build on windows", lets make it "Windows users should use Docker" and have a link to: https://github.com/codidact/qpixel/tree/develop/docker, or link to the Docker section in the Readme.
> 
> [...]
> 
> [...]

Leaving away the exact words and hows aside, I think so, yes. Thank you.

**Comment by luap42** [comment]
My opinion:

Windows doesn’t work well with Ruby for some reasons. (It’s unreasonably slow)

To mitigate this, I use WSL and can confirm and ensure that QPixel works with WSL. However, AFAIK no member of the core dev team used Docker, so we —unfortunately— can’t safely support it. It might break at any time, although that shouldn’t happen in most cases. 

If someone continues to support Docker and checks, whether it still works, that’s fine and we can add a recommendation.  If not, I’d rather not redirect Windows users to a not actively maintained platform.

**Comment by ArtOfCode-** [comment]
> I’d rather not redirect Windows users to a not actively maintained platform.

This is a sensible position to take, I think. We're not actively maintaining Docker; if it works, great, but if not, it's up to the individual dev to fix it. I'd be more happy to add a suggestion of using WSL, because that's far more likely to work.

**Comment by manassehkatz** [comment]
I don't think referring people to Docker makes sense, unless one of the developers wants to take on the task of setting up a Docker image (or whatever it is called - I have used Docker minimally and never really understood it). The concept of Docker is very good, but without specific implementation details (i.e., a public Docker image) I don't see how it will be easier for a new person to implement (spin up an instance) than other methods of getting a Linux system running.

IMHO, any serious developer or implementer (e.g., if someone wants to spin up their own instance "as is" without any code changes, but just to have an instance under their own control) will figure out a way to run it in some flavor of Linux. There are a bunch of free or low cost ways to run a Linux VM inside Windows.

For any practical *hosting* (even for a small community, as opposed to development work), I have been telling everyone for years *not* to self-host but to either find a low-cost shared host (there are plenty, though finding one for Ruby is a bit harder than for some other languages) or (as we are currently doing) use an appropriately sized AWS instance. Except for Windows-specific things (e.g., MS SQL Server) Windows as a host is more expensive without any benefits.

I am not anti-Windows - my desktop & laptop run Windows. This is a practical consideration of development & hosting, as distinct from the typical (even for many Linux developers) user-facing system.

**Comment by LionelBergen** [comment]
> any serious developer or implementer

I'm thinking more of the passerby's such as myself, who saw the README and nearly closed it after seeing it can't be built on Windows. I saw 'Docker' lower down in the README, so I thought it was already setup when I suggested this.

Recommending WSL, Docker or something is a good idea. Any clue on getting it to work with Windows, for those first seeing the project and wanted to view it locally. IMO anything is better than saying "won't build on windows".

**Comment by Trilarion** [comment]
"I’d rather not redirect Windows users to a not actively maintained platform."

I like this a lot. We should concentrate on what we have tested and know for sure. Other possibilities we should just mention as such and state that there are no instructions available.

Unlikely is not a good phrase, because it's not very specific. Does it mean impossible? Or rather involved or maybe just untested?

Instead simply say: These are the instructions for XXX. On Windows it might be possible to use WSL or Docker to setup QPixel (currently untested).

And if somebody reports a success with WSL or Docker, the document can be updated accordingly. For example, I currently use Windows and WSL and got it running more or less.

**Comment by trichoplax** [comment]
Currently the top of the [installation guide](https://github.com/codidact/qpixel/blob/develop/INSTALLATION.md) (linked to from the [main readme](https://github.com/codidact/qpixel#readme)) says:

> These instructions are for setting up a development instance of QPixel. QPixel is built with Ruby on Rails.
> 
> In that guide it is assumed that you already have a Unix environment available with Ruby and Bundler installed. WSL works as well. Windows (core) has not been tested.
> 
> For an installation with Docker see the README.md in the [docker](https://github.com/codidact/qpixel/blob/develop/docker) folder for further instructions.

Does that cover everything discussed here? If no further changes are required to the installation guide, is this issue ready to be closed?
