### ISSUE TITLE
Comment notifications don't take you to the comment if it's collapsed

### ISSUE THREAD

**Issue by cellio** [codidact/qpixel#187]
https://meta.codidact.com/questions/277863

> Currently, comments past the fifth(?) comment are hidden for length purposes. However, this breaks the ability to automatically scroll to the comment when using a direct link.
>
> For example, I recently got a notification for this comment: https://meta.codidact.com/questions/277002#comment-3855
>
> It took me a while to find the comment I got mentioned in because it didn't scroll to it, and I had to manually check the comments on each post.
>
> I think that the relevant comment section should open up automatically when using a direct link so that the comment can be scrolled to.

I concur.  This happens to me a lot and it can be hard to find the new comment that generated the ping.

**Comment by cellio** [comment]
A lot of stuff about comments will change with the new design for threaded comments, but (a) we'll need to address this there and (b) if that's going to be a while yet and this would be a small change, let's consider doing it anyway.

**Comment by galegosimpatico** [comment]
I can't even generate such links.

So here is norepro because you write about a feature that doesn't exist to me.

**Comment by ArtOfCode-** [comment]
@galegosimpatico these kind of links appear in notifications - if someone pings you in a comment and that comment is more than 5 down the comment thread, it will be collapsed by default and the link won't take you straight to it.

**Comment by galegosimpatico** [comment]
oh, now I'm seeing it. :D

**Comment by galegosimpatico** [comment]
related: can't ever browse the extra comments unless JS is enabled

**Comment by galegosimpatico** [comment]
is this the reason the comment system has to be revamped? I see a (super dirty) way to (maybe) fix this, but feels like better wait to the new comments system:

* explode every "show next X comments" feat
* tell browser to go to the section requested - but making sure the page is not reloaded
* rebuild every "show next X comments" feat - but I wouldnt know how to, unless the DOM gets full of invislbe sh

**Comment by ArtOfCode-** [comment]
Comments are due for a bigger revamp than just this - adding a bunch of features as well as just fixing this. If it's not easy to fix, it may better to just leave it until then.

**Comment by cellio** [comment]
Comment notifications now take you to the comment on the thread page.
