### ISSUE TITLE
Clicking on an already-read notification toggles it to unread

### ISSUE THREAD

**Issue by cellio** [codidact/qpixel#188]
https://meta.codidact.com/questions/277175

> If I click on an already read notification in the inbox, it will go to the page I was notified about, but it will also change it from read to unread.

**Comment by galegosimpatico** [comment]
[complexity: easy](https://github.com/codidact/qpixel/labels/complexity%3A%20easy)

**Comment by galegosimpatico** [comment]
[meta: good first issue](http://github.com/codidact/qpixel/labels/meta%3A%20good%20first%20issue)

**Comment by cellio** [comment]
Just confirming this is still true; the changes for "mark as read" and "mark all as read" didn't affect this behavior.

**Comment by galegosimpatico** [comment]
Confirming it is still easy and good first issue as well.

**Comment by anthonyronda** [comment]
Not able to reproduce in Chrome or Firefox. My only notification types are "mentioned in a comment" and the tour notification, so I can't tell if this only happens with a certain notification type.

Further, this is tagged as status-completed in the above-linked Meta post: https://meta.codidact.com/questions/277175

**Comment by cellio** [comment]
Thanks for the ping Anthony!  This got fixed by some other change and we missed closing this issue.
