### ISSUE TITLE
User avatar image is stretched (image aspect ratio not maintained) in the top bar

### ISSUE THREAD

**Issue by cellio** [codidact/qpixel#190]
https://meta.codidact.com/questions/278377 reports, and proposes a fix for, a display issue with user avatars in the top bar.  What's needed is for someone to verify the fix and update the CSS.

**Comment by FarrenRE** [comment]
I believe this has been fixed: [link to commit](https://github.com/codidact/qpixel/commit/fa009b5663412f7346346c532bb5bfe5d6929b4d) by @luap42

**Comment by luap42** [comment]
Yup. Pretty sure I did fix this. Thanks for the reminder @FarrenRE.
