### ISSUE TITLE
Can't add tags in tour

### ISSUE THREAD

**Issue by cellio** [codidact/qpixel#192]
https://meta.codidact.com/questions/277092

A user taking the tour got stuck at the tags, getting the message "The results could not be loaded" when trying to add them.  The user eventually found out how to continue through the tour, but this error was confusing.

**Comment by sau226** [comment]
It looks like we query a tag set with id of -1 inside that aspect of the tour. We should probably double check any special casing we have for that tag set or create it in seeds if it does not already exist.

**Comment by Taeir** [comment]
Fixed by #841 / #856
