### ISSUE TITLE
Duplicate close notice is misleading if the target is newer (superseded-by case)

### ISSUE THREAD

**Issue by cellio** [codidact/qpixel#193]
https://meta.codidact.com/questions/277447 reports a case where a question was closed as a duplicate of a newer one, because the latter superseded the former.  The notice says:

> This question has been answered before. See: (link)

The "before" is misleading.  An answer there proposes that we have the concept of "superseded by", which would involve additional UI, but a simpler solution would be to change the notice to:

> This question is addressed at (link).

This would remove the temporal element entirely.  And by changing "answered" to "addressed", we can handle the case where the target doesn't have answers, perhaps because it isn't a conventional question.  (Maybe it's an announcement, for example.  Or maybe it doesn't have answers, but it's written better than the present question and so people want to make it the target anyway.)

**Comment by cellio** [comment]
Related: since a question can be a duplicate of an unanswered question, it's also not accurate to say it's been *answered* before.  Raised here: https://meta.codidact.com/questions/279198

**Comment by razetime** [comment]
Both the questions linked here have different wording now(`outdated/superseded` & `addressed`), so I *think* this issue has been solved.

**Comment by cellio** [comment]
It looks like it was addressed via custom edits on Meta.  I just checked on Software Development and the duplicate reason in the dialogue says "before".  I think there's a string in the code that needs to be edited -- presumably a one-line change if someone can find the line.

The language currently on Meta seems clear enough: "This question has been addressed elsewhere."
