### ISSUE TITLE
Adding a (non-existent?) parent to a tag returns 500

### ISSUE THREAD

**Issue by cellio** [codidact/qpixel#197]
https://meta.codidact.com/questions/278198

https://software.codidact.com/questions/278151

> If I try to provide a parent to a tag, it crashes with 500.
>
> Error Id = 6bd06f30-539d-4b88-8743-eca32a8465cd  
> Tag to edit = https://software.codidact.com/categories/38/tags/3338/edit  
> Added parent = office
>
> It seems that selecting a parent tag does not actually exists creates the issue. Also I cannot find a way to remove a tag's parent.

**Comment by ArtOfCode-** [comment]
Needs select config changed to disallow creating nonexistent entries from input on this select box only (add a data-* attribute, perhaps?)
