### ISSUE TITLE
MathJax config: newlines in eqnarray contexts

### ISSUE THREAD

**Issue by cellio** [codidact/qpixel#198]
https://math.codidact.com/questions/278270

> n my answer to https://math.codidact.com/questions/278268 I have a couple of eqnarray contexts which are being rendered by MathJax but aren't being broken into lines as they should. This works fine in other sites with MathJax which I used to use, so I suspect that it's a problem with the configuration here. If I'm wrong, how should I alter my markup to make it work?

See discussion in comments.  (I don't know enough about Mathjax to be able to distill it here.)

**Comment by MoshiKoi** [comment]
Should this issue be closed in favor of #435 ?

**Comment by ArtOfCode-** [comment]
Duplicate of #435
