### ISSUE TITLE
Add preview for editing profile "about" text

### ISSUE THREAD

**Issue by cellio** [codidact/qpixel#200]
https://meta.codidact.com/questions/277518

When editing the "about" text there's no preview, so to see if your Markdown worked as intended you have to first save and then edit again if you need to change something.  Can we add a preview like for other posts?

**Comment by kevinmmansour** [comment]
There is error in Console.

`Uncaught TypeError: window.markdownit is not a function`

And there is another error which I do not think it is related :

`Uncaught TypeError: this.element is null`.

And there is [line](https://github.com/codidact/qpixel/blob/0aff72a9d63b10c1d29b6eb03802e4aae29f04fd/app/views/users/edit_profile.erb#L36) which is likely that it preview the about text.
