### ISSUE TITLE
Live update for comment count?

### ISSUE THREAD

**Issue by cellio** [codidact/qpixel#204]
https://meta.codidact.com/questions/278059 reports that, after leaving a comment, the comment count ("N comments") doesn't update until the page is refreshed.  I don't know if that's intentional (performance) or an oversight, so this change request is to evaluate whether it makes sense to do "live updates" and, if so, do that.

**Comment by Istiakshovon** [comment]
I think the issue should be closed (It is not needed anymore).

**Comment by kevinmmansour** [comment]
> 
> 
> I think the issue should be closed (It is not needed anymore).

Why it is needed anymore? Did it get solved? I don't think it is solved.

**Comment by Istiakshovon** [comment]
@kevinmmansour  Actually, the problem was happening for normal comment. Now, we have thread comment. Even, thread comment doesn't work that way. So, it have to be closed
