### ISSUE TITLE
History for articles is missing the title/score/link block

### ISSUE THREAD

**Issue by cellio** [codidact/qpixel#206]
As reported here: https://meta.codidact.com/questions/278476

Post history for a question or answer shows the "block" with the title/link and score: 

![image](https://user-images.githubusercontent.com/5557942/95776647-b8caf780-0c92-11eb-9a06-079b73d5ac29.png)

But articles do not:

![image](https://user-images.githubusercontent.com/5557942/95776664-c1bbc900-0c92-11eb-8020-0e2433c87853.png)

I hope this is a simple matter of including the same element for articles as we do for questions.  (Not shown here, but it's also there for answers, with a smaller font.  Articles and questions are both top-level posts, so copy from questions not answers.)

**Comment by rileyradoll** [comment]
Hello @cellio I'd like to try tackling this issue. Can you assign this to me?

**Comment by cellio** [comment]
@rileyradoll all yours!  Thanks for tackling it.

**Comment by ArtOfCode-** [comment]
Thanks! Let us know if you need any help.

**Comment by rileyradoll** [comment]
Hi @cellio I think I've solved the issue. Can you check out my PR when you have a chance?
https://github.com/codidact/qpixel/pull/245 Thanks!

**Comment by cellio** [comment]
@ArtOfCode- or @luap42 can you review this?  Thanks.
