### ISSUE TITLE
Auto-save blocks on rendering update

### ISSUE THREAD

**Issue by cellio** [codidact/qpixel#213]
https://judaism.codidact.com/questions/278011

The linked post describes a problem on Judaism where, when a post auto-saves, it hangs for a long time because the Sefaria linker is running (slowly).  While there might be a problem with the Sefaria linker, and if so we can't do anything about it, the real problem is the dependency between auto-save and rendering. 

Update: also reported for Mathjax here: https://math.codidact.com/questions/278724  (Chrome on Android, Edge on Win 10, but not Chrome on Windows).

I can think of several approaches to solving this problem:

- (Best IMO) Auto-save just saves markdown; it shouldn't care about, or depend on, the *rendering* of that markdown.

- Auto-save could run in the background and not block the UI.

- There could be a way for the user to abort an auto-save that's running and taking too long.

- Frequency of auto-save, including "off", could be customizable per-community or per-user.

**Comment by cellio** [comment]
@ArtOfCode- what browser/OS were you not able to repro on?

**Comment by ArtOfCode-** [comment]
@cellio Chrome/Ubuntu

**Comment by cellio** [comment]
So it might still be a problem in the reported browsers, which we haven't tested.  A no-repro tag seems premature.

**Comment by ArtOfCode-** [comment]
no-repro is just me saying that I haven't been able to reproduce, not that the bug doesn't exist - it's just to say that I need more information/testing to be able to find the bug, if there is one.

With this one, I suspect that it's not actually a bug, but just down to available system resources. The bug report points out that it only happens on longer posts, which will naturally take longer for the linker to parse; Android platforms don't tend to have a huge amount of resources anyway, so I could easily see that becoming a choke point.

**Comment by cellio** [comment]
That makes sense.  Does auto-save need to depend on rendering at *all*?  Or can auto-save just say "oh hey you have some markdown updates; lemme stash those for you" and leave the main editor thread to do its rendering as usual?  That is, why does saving markdown add an extra rendering pass?  Or have I misunderstood what's going on?

**Comment by ArtOfCode-** [comment]
@cellio JS is single threaded; we can't just use another thread top solve this one. There's no dependency between linker and auto save, but if the linker ends up running first, then auto save can't run until the linker has cleared the thread. In a limited resources environment, that might take a while.

**Comment by cellio** [comment]
@ArtOfCode- oh.  I didn't realize it was single-threaded.  Thanks.  Does that mean we wouldn't be able to let a user abort an auto-save either (it would queue up behind the task that's taking all the time)?

It sounds like the only way to solve the user-frustration problem, then, would be to let users turn off auto-save and give them a "save draft" button instead?  (Default would remain what we're doing now, which works the vast majority of the time, but if you tend toward posts that use a lot of slow rendering, you might prefer to control the saves.)

**Comment by cellio** [comment]
Reporter says this happens in Safari more than Firefox (in a comment there).

**Comment by ArtOfCode-** [comment]
Closing this one - see comments above for JS-is-single-threaded, making this technically difficult to solve, and we now have the option to turn off auto-saving, which removes the frustration of having it block you in the middle of writing a post.

**Comment by cellio** [comment]
Sounds good.  Can we add a "save" button so people can manually save when auto-save is turned off?  (I'll file a separate issue for that.)
