### ISSUE TITLE
Approved suggested edits leave no indicator on the post AND clobber any previous last-edited notice there

### ISSUE THREAD

**Issue by cellio** [codidact/qpixel#214]
https://meta.codidact.com/questions/278039

This post reports one case of a question that shows new activity on the question list, but it's nowhere to be found on the question or answers.  I have seen this too, intermittently.  I know that tag-only edits have sometimes been (not) reported in this way, but I think there are other cases too.  I do not know if it is deterministic.

Can we compare the code that produces the "last edited" text on a post to the code that produces the "last activity" text on the question list?  Something is probably subtly different.

**Comment by galegosimpatico** [comment]
Could be related to https://github.com/codidact/qpixel/issues/174 (or not).

**Comment by cellio** [comment]
More reports and a hypothesis: https://meta.codidact.com/questions/279758

> Tentative characterization of the bug: this happens when a user who does not have the Edit ability makes a suggested edit and that suggestion is approved. Look at the edit history on this question. After Olin's edit the "last edited" indicator was correct. After I edited it was updated correctly (so not a problem with third-party edits). But when Monica's Sock edited it and I approved that edit, the "last edited" indicator disappeared entirely.

**Comment by cellio** [comment]
Here's a case on the dev server.  Is that because it doesn't have this fix?  https://a.dev.codidact.org/posts/37

**Comment by cellio** [comment]
Luap42 confirmed that the dev server doesn't have these latest fixes.  I tried to reproduce in prod and it behaved correctly now: https://meta.codidact.com/posts/39539.
