### ISSUE TITLE
Sign In / Sign Up buttons are shown twice on small viewports like mobile

### ISSUE THREAD

**Issue by cellio** [codidact/qpixel#216]
https://meta.codidact.com/questions/278714

When there isn't room to display all the header links, some of them move into the hamburger menu.  However, the Sign In and Sign Up buttons are in both that menu and the header, which is redundant.  Not a big deal, but logging it in case it's an easy fix.

**Comment by galegosimpatico** [comment]
Done in https://github.com/codidact/qpixel/issues/225.
