### ISSUE TITLE
Can't open hamburger menu on Meta when signed out

### ISSUE THREAD

**Issue by cellio** [codidact/qpixel#217]
https://meta.codidact.com/questions/278713

On Meta, but not other communities, when signed out the hamburger menu does not respond.  I reproduced this problem in Firefox on Android.  I note that Meta is the only community with the new-visitor popup enabled, and I can't dismiss that either.  These might be related but I'm not sure.

**Comment by sau226** [comment]
Is it cool if I take this issue? I think I might have a fix ready to go.

**Comment by ArtOfCode-** [comment]
Go for it, @sau226

**Comment by sau226** [comment]
PR submitted. Please see PR submission comments for details of fix, and why fox quality is not the best.
