### ISSUE TITLE
After tag merge, some posts do not show up when clicking the tag

### ISSUE THREAD

**Issue by cellio** [codidact/qpixel#226]
https://meta.codidact.com/questions/278626

Three similar tags were in use, one each on three different posts, and a moderator merged two of them into the third.  After the merge, only one post shows up in the tag search results.  Of the other two, one is a deleted question and the other is an article.  Tag searches normally do return articles too (I just tested), but not here after the merge.  All three posts show the correct (merged) tag.  (The meta post includes links to the three posts.)

**Comment by Taeir** [comment]
I think this is related to the tags cache. The system does not have a supported way of merging tags, right? So how were the tags merged?

**Comment by cellio** [comment]
Moderators can merge tags: 

![Screen Shot 2022-09-12 at 5 35 21 PM](https://user-images.githubusercontent.com/5557942/189762995-7c6fa684-9966-4334-a182-ad02ee29a97b.png)

**Comment by Taeir** [comment]
Ah I see. Then this is probably caused by the same issue as #268.

**Comment by cellio** [comment]
That seems plausible.

**Comment by cellio** [comment]
Duplicate of https://github.com/codidact/qpixel/issues/268.
