### ISSUE TITLE
In question title, mark duplicates as "duplicate" not "closed"

### ISSUE THREAD

**Issue by cellio** [codidact/qpixel#228]
"Closed" can sound negative.  It can also, sometimes, signal that a post could be reopened if it got a little help from an edit.  Duplicates, on the other hand, are wayfinding, pointers to where the answers really are, and not something anybody is going to invest time in editing (unless the author disagrees, and the author already gets notified).

We should label duplicates with "[duplicate]" in the titles on the question list, so they're easier to distinguish.  Further, we are planning to decouple "duplicate" from the "close" path; it's going to be a different workflow.  So we'd need to do this anyway; I'm suggesting that we do it earlier, because I *think* it's an easy change (check close reason, set text).

**Comment by luap42** [comment]
Closed in #551, thanks @kevinmmansour
