### ISSUE TITLE
"You were mentioned in a comment" notifications should show the title of the question

### ISSUE THREAD

**Issue by cellio** [codidact/qpixel#230]
https://meta.codidact.com/questions/277121

The notifications drop-down shows the question title at least for comments that don't specifically ping you, and for answers to your own questions.

However, if you're "mentioned" (pinged) in a comment, the notification only says "You were mentioned in a comment" and indicates which site that comment is on.

Can the notification text please show at least the title of the question where that comment exists?

**Comment by galegosimpatico** [comment]
[complexity: easy](https://github.com/codidact/qpixel/labels/complexity%3A%20easy)
https://github.com/codidact/qpixel/blob/88475cb3b7236df996c71e6f3b9bf6811ee6936d/app/controllers/comments_controller.rb#L23

**Comment by luap42** [comment]
This is easy, unless we want to do it right. If we revamp notifications one day, we’ll want to link to the post, so that title changes propagate, but for now we can ignore that use case.

**Comment by Istiakshovon** [comment]
It's showing now?
