### ISSUE TITLE
Support tables

### ISSUE THREAD

**Issue by cellio** [codidact/qpixel#235]
https://meta.codidact.com/questions/278300

Markdown doesn't support tables.  But we also don't support HTML tables (confirmed here: https://meta.codidact.com/questions/277420#answer-277424), which means people have no way short of "pre" blocks to create tables.  Can we do anything to solve that?  It's fine if people have to use HTML instead of Markdown to do it.  I'm unclear on why we support (and don't support) the elements we do/don't.

**Comment by luap42** [comment]
So, technology this is easy (adding three words to a list). However, we need to find a way to preserve tables on mobile, which is (quite) hard.

**Comment by cellio** [comment]
@luap42 do you mean that tables can be too wide for a mobile display, or is there some other problem with tables and mobile?  What do we do about wide math?

**Comment by ArtOfCode-** [comment]
Tables are almost always too wide for mobile display. I have some ideas that should work for a CSS fix, but what I'd really like to do is unify our Markdown processing so we use _one_ library rather than two - that'll solve a bunch of issues.

**Comment by ArtOfCode-** [comment]
...which was easier than I thought it would be.
