### ISSUE TITLE
Searches produce 500s on Judaism but work on other communities

### ISSUE THREAD

**Issue by cellio** [codidact/qpixel#236]
https://meta.codidact.com/questions/278330

The reporter searched for "why" on Judaism (a word that certainly appears in posts there) and got a 500.  I can reproduce.  The same search works on Meta, so it's not something about the input.  (I don't know if "why" is a stop word or what search is supposed to do if the query contains only stop words.  I tried searching for "and" -- failed on Judaism, worked on Meta.)

I wondered whether it had something to do with imported posts, since Judaism has some but Meta does not, so I tried these searches on Writing which also has imported posts.  They worked.

I then wondered if it had something to do with the age of the community; maybe something about the seeds changed over time.  So I tried on Math, our newest community.  Works there too.

I don't know what per-site configuration can affect search.  I'm tentatively labelling this as a configuration issue, but also a bug.  I don't know how to narrow this down.

**Comment by galegosimpatico** [comment]
Can't be sourced off the team while there is no shared server side message. :/

**Comment by cellio** [comment]
@galegosimpatico sorry, I don't understand your comment.  Are you saying you don't have enough information to reproduce?

**Comment by luap42** [comment]
Likely a data corruption error, which only @ArtOfCode- can fix.

Or *someone* found it funny to cause issues with the "Why?" question on a religion site... :P

**Comment by cellio** [comment]
@luap42 not just "why".  Searching for "and" also breaks (I was testing stop words), but a search for "adam" works (search isn't generally broken).

**Comment by galegosimpatico** [comment]
> [...] Are you saying you don't have enough information to reproduce?

Not really, I don't want to reproduce, only read the error and look the code a little bit.

> Likely a data corruption error, [...]

You say, an import error? What other corruption can be expected‽

**Comment by ArtOfCode-** [comment]
Data error; fixed.
