### ISSUE TITLE
after login, redirect to the original page

### ISSUE THREAD

**Issue by cellio** [codidact/qpixel#239]
https://meta.codidact.com/questions/276738
https://meta.codidact.com/posts/288196

If you are not logged in and are viewing, say, a question page, and then you click "sign in" to log in, after signing in you're directed to the front page.  Can we instead redirect you to the page you were on before signing in?  Yes you can get there via browser back buttons, but this redirection is common enough that not doing it stands out a bit.

**Comment by Taeir** [comment]
Devise has a mechanism of "after_login_path" which it uses automatically. What needs to happen is that before someone goes to the sign_in_page, the controller needs to call "store_after_login_path" (I don't remember the exact name) such that the user is redirected there. I've implemented this before, will see if I can do it relatively easily.
