### ISSUE TITLE
Move "close" and "delete" to Tools menu and show only if you have those abilities

### ISSUE THREAD

**Issue by cellio** [codidact/qpixel#240]
https://meta.codidact.com/questions/276505

I believe the abilities branch makes sure that you see "close" and "delete" options on posts only if you can perform those actions.  I can't remember if that branch *also* moves these actions to the Tools menu already.  Let's put these with the other "curation" tools on that menu; top-level action links are getting a little abundant and we *have* a Tools menu.

Flag should remain top-level for visibility; we want it to be obvious you can do that and even new users can flag stuff.  By the time you can vote to close or delete, you've probably gained enough experience to know to look at Tools.

**Comment by cellio** [comment]
Now that we've landed abilities, we should be able to do this without conflicting with anything else.

**Comment by cellio** [comment]
Oh, I guess since you can always delete your own posts, moving delete in there would mean everybody always sees tools.  We should decide if that's what we want.  But meanwhile, we should at least move close in there.

**Comment by Trilarion** [comment]
Just checked (on mobile). I do not see tools but I see flag, close and delete on my own questions. Should I be able to close also my own questions? If yes, should I have close and delete in the tools sub-menu or not?

**Comment by cellio** [comment]
Oh, hmm.  If you can close your own questions (I didn't realize you could), then this gets more complicated.  Maybe we should leave the placement of these links alone, at least for now.

**Comment by Trilarion** [comment]
Just checked that I can indeed close my own questions (but cannot reopen them, https://meta.codidact.com/posts/285540). 

I wonder if this is intended. Should I be able to close my own questions? I would assume that if I realize that something is wrong with my own content, I can either edit it in shape or remove it right away. In the same way also flagging your own posts (as spam for example) seems a bit strange.

**Comment by cellio** [comment]
I think you should be able to close your own question (particularly if it's a duplicate -- someday we will separate dupes from the close workflow but it's there now).  Closing your own question is, effectively, withdrawing it from requesting answers.  If you know your question is incomplete or unclear and you need time to work on it, that should be ok -- and we wouldn't want people trying to answer if you're going to change it.

You wouldn't (I presume) flag your own post as spam, but there are sometimes reasons to flag your own post, like to ask for mod help if there's been an edit war.

Given all this, I think I should withdraw this issue -- let's leave the controls alone until we have a more thoroughly thought-out proposal.

Meanwhile, I've just noticed that the original meta request linked here, which was to not show things you can't do, has been addressed.  It was my answer that proposed moving things.  I'm ok with saying no to that.
