### ISSUE TITLE
Add a way to cancel a comment edit

### ISSUE THREAD

**Issue by cellio** [codidact/qpixel#243]
https://meta.codidact.com/questions/278770

You can now discard a *new* comment (there are buttons for "post" and "discard"), but you can't cancel *editing* a comment -- the only button during an edit is "post", so it's either that or refresh the page.

Could we add the other option when editing a comment?  For clarity, it should probably say "discard edit" rather than just "discard" (which could be interpreted as "delete").

I'm marking this "easy" because I *think* the fix is to copy this code from "post comment" and adjust it for "edit comment".  If there's something that makes it more complicated, feel free to change the label or comment about it.

**Comment by rohitgeddam** [comment]
I would like to work on this.

**Comment by cellio** [comment]
All yours @rohitgeddam!
