### ISSUE TITLE
Add borders to tables (use CoDesign tables)

### ISSUE THREAD

**Issue by cellio** [codidact/qpixel#248]
https://meta.codidact.com/questions/278904

Could we have lines for the rows and columns (cell boundaries) and maybe a border around the outside of a table?

I started to file this against CoDesign, but the CoDesign [documentation](https://design.codidact.org/components/tables/) shows that its tables have the cell boundaries (though not the outer bound).  I think this means that QPixel isn't using CoDesign's tables in posts, though it does in other parts of the site layout.  Can we use consistent styling?

**Comment by ArtOfCode-** [comment]
f200846d89d03f6cc3cbc1f910e7c40374f2acbc
