### ISSUE TITLE
No diff in history

### ISSUE THREAD

**Issue by MoshiKoi** [codidact/qpixel#254]
See https://meta.codidact.com/posts/278765/history, https://meta.codidact.com/posts/278948/history, and https://software.codidact.com/posts/278958/history, 

From the timestamps, it seems that for some reason edit diffs stopped being tracked sometime in the past few days, as the edit four days ago on https://languages.codidact.com/posts/278906/history was unaffected, but everything since yesterday was affected.

**Comment by cellio** [comment]
@ArtOfCode- @luap42 can any sort of analysis be done on the set of changes that went into the last deploy, to try to find the source of the broken diffs?  Bisect (which I have heard of but never used)?

**Comment by galegosimpatico** [comment]
> Bisected to <http://github.com/codidact/qpixel/commit/b11c6e>

https://discord.com/channels/634104110131445811/676843271762214932/775758907167211591

**Comment by galegosimpatico** [comment]
https://github.com/codidact/qpixel/commit/7faf191d3699bffac116b1a0b8624a0ed1a77854
