### ISSUE TITLE
Misalignment in edit history (overlap or smushed text and some vertical skew)

### ISSUE THREAD

**Issue by cellio** [codidact/qpixel#255]
https://meta.codidact.com/questions/278949

> In the post history, the "by..." and edit reason are misaligned from the "Post edited" (more obvious when there is an edit reason)

> E.g. https://meta.codidact.com/posts/278406/history

**Comment by galegosimpatico** [comment]
https://github.com/codidact/qpixel/commit/9b9c49d2e6e21232717ef760c76c3612e111c28b#commitcomment-44049323
