### ISSUE TITLE
Post truncated in history; might be due to '<' in body (in a code block)

### ISSUE THREAD

**Issue by cellio** [codidact/qpixel#257]
https://meta.codidact.com/questions/278424

The history for [this question](https://software.codidact.com/questions/278335), for the initial revision, truncates the post in the code block right where a '<' character appears.  There are some later edits (which I can't quite tell from the diff what they did), so be sure to look at the initial revision.

**Comment by trichoplax** [comment]
This appears to have been fixed. The initial revisions for both the [question history](https://software.codidact.com/posts/278335/history) and the [answer history](https://software.codidact.com/posts/278336/history) now show the full text, no longer cut off after the `<` in the code block.
