### ISSUE TITLE
Tag-only edit where the tag is also being created fails

### ISSUE THREAD

**Issue by cellio** [codidact/qpixel#260]
https://meta.codidact.com/questions/278225

Right now you can create new tags (if you have the privilege) just by typing them into the tags list on a post.  Eventually we're going to change that UI, but probably not for a while.  If you edit a top-level post to *only* change tags, and if your tag change includes adding a new one, the edit fails ("no changes were saved because you didn't edit the post").  If you also edit the body, it succeeds.

**Comment by Taeir** [comment]
When I test this on the latest development, it works as expected: the new tag is created and added to the post.
Therefore, I think this can be closed.

**Comment by cellio** [comment]
Not only that, but it works on the Codidact instance that's running a version from several months ago.  Thanks for letting us know!
