### ISSUE TITLE
Notification gets created before post is validated, producing the occasional phantom notification

### ISSUE THREAD

**Issue by cellio** [codidact/qpixel#263]
https://software.codidact.com/questions/278892 reports getting a notification for something that doesn't exist.  The poster assumed, incorrectly as it turns out, that it was a notification for something that was then deleted.

@luap42 wrote in an answer there:

> That... looks like a funny bug.
>
> I started writing an answer, containing mostly the number "1", because that would be an (not really helpful, but correct) answer to your question.
>
> To test, whether there was an answer limit, I submitted my one-letter post. Correctly, I was rejected.
>
> But apparently the code enters the notification, before the checks on length/whatever are applied. As you can see [here](https://github.com/codidact/qpixel/blob/develop/app/controllers/answers_controller.rb), we add the notification in line 20, but save it (and run the validations) only in line 23.

I'm filing this issue so we don't lose track of it.  From this description it looks like a straightforward fix.

**Comment by sau226** [comment]
What's the status of this issue? Is it fixed, or is something else blocking this from being closed?

**Comment by cellio** [comment]
Missed it when the PR got merged.  Thanks for the catch; closing now.
