### ISSUE TITLE
Suggested-edit diff doesn't show change in code formatting

### ISSUE THREAD

**Issue by cellio** [codidact/qpixel#265]
https://software.codidact.com/questions/277410

The suggested edit was to code (adding code fences), but the change didn't show up in the diff.  The linked post shows a couple examples.

**Comment by Taeir** [comment]
When looking at such changes in the latest development version, it is displayed correctly:
![image](https://user-images.githubusercontent.com/668952/189763880-70d4c7af-4daa-4d9a-90f1-c3f152d8092f.png)

**Comment by cellio** [comment]
It looks like that was fixed even before the latest batch of changes; on our production instance, which is several months behind currently, I no longer see the problem in the edit here: https://software.codidact.com/posts/277331/history . (The second post linked there still doesn't show a clear diff, but if we haven't seen the problem in recent edits, that could be a data error of some sort.)
