### ISSUE TITLE
Can we improve how we use space on the user profile?

### ISSUE THREAD

**Issue by cellio** [codidact/qpixel#27]
This is a screenshot of (part of) my user profile in a browser that's currently 1168px wide:

![Screen Shot 2020-04-06 at 11 12 30 PM](https://user-images.githubusercontent.com/5557942/78626321-709ec880-785c-11ea-97b4-5402b11a5b40.png)

The "user" part is laid out in three (uneven) columns:

- avatar plus rep
- name and "about"
- external links and two site tools

This section of the page is further compressed by the presence of the right column that also appears on other pages on the site.

To me, the "about" column looks very squished, and there's a lot of empty space in the other two columns.  The right column is also more oriented toward questions than profiles, though perhaps we'll fill it with more user-focused stuff later.

I don't want to ask for big changes when we'll probably be redesigning this page later anyway, but it seems that if we could combine the two sparse columns, we could have more room for the "about" text while still having everything on the page.  Could we move the links and tools under the avatar (adjusting the width some), or move the avatar to the top of the column with the links/tools, or put the links/tools below the "about" text somewhere, or... something?

**Comment by luap42** [comment]
I don't know exactly, how much effort it would be, but it's probably possible to hide the sidebar on these pages: I think it's possible to define multiple "layouts", but OTOH it might lead to unwanted code-duplication and therefore error sources we don't want.

**Comment by ArtOfCode-** [comment]
Feels like the easiest thing to do would be to move the content of the rightmost column of the three under the avatar+rep.

**Comment by cellio** [comment]
Seems like.  What happens (either now or with that change) if a blog URL is really long?

Later I want to revisit the (far) right column on user profiles; it seems like it should either go away (like it does on SE) or be contextual (so it has links about user stuff, not hot questions etc).  But since we don't know what we're going to want to do with it, we should probably leave it alone for now and work around its existence -- assume that *something* will be using that chunk of real-estate and the profile can't.

**Comment by ArtOfCode-** [comment]
At the moment, this is what happens with a long URL:

![image](https://user-images.githubusercontent.com/10406565/78804908-a48f0080-79b8-11ea-8ff0-ef7c1f1c9c65.png)

Not exactly optimal... but should be relatively easy to fix.

Moving the stuff over:

![image](https://user-images.githubusercontent.com/10406565/78805189-03ed1080-79b9-11ea-9401-3f9e4b96af55.png)

That also breaks with a long URL:

![image](https://user-images.githubusercontent.com/10406565/78805239-149d8680-79b9-11ea-8400-149a84828d67.png)

But likewise, that should be relatively easy to fix:

![image](https://user-images.githubusercontent.com/10406565/78805457-56c6c800-79b9-11ea-88c0-4dc6c97bc21c.png)

**Comment by cellio** [comment]
Yeah, either way you need to either wrap or truncate; truncate is easier, and maybe put the full link in a tooltip?  (I know the browser would also provide it, but this seems easy and friendly.)

**Comment by ArtOfCode-** [comment]
Aye, certainly could do. That example is a pure CSS cutoff, so the server has no idea whether it's been cut or not, but we could add a tooltip for the blanket case where the URL is longer than X characters.

**Comment by cellio** [comment]
Or just add it everywhere for consistency and (presumably) easier implementation.

**Comment by ArtOfCode-** [comment]
Very true. Aye, this isn't a difficult one, lemme throw it on the TODO list.
