### ISSUE TITLE
Editing font reverses certain characters (edit box and render are different)

### ISSUE THREAD

**Issue by cellio** [codidact/qpixel#271]
https://languages.codidact.com/questions/277095

One particular character (U+02BE) is being swapped with another (U+02BF) in the editor.  The preview is right; the edit area is backwards.  There's some discussion in comments there about where the font problem is, so I don't know if it's under our control or something at the client end.  This was reported a while ago, but I just verified that it's still happening.

**Comment by ArtOfCode-** [comment]
Comment on this one is correct: this is a local fonts issue, not a site issue
