### ISSUE TITLE
Link back to mod dashboard from individual mod pages

### ISSUE THREAD

**Issue by cellio** [codidact/qpixel#272]
https://meta.codidact.com/questions/278995

> Right now the moderator dashboard has a bunch of links to different moderator tools like Flag Queue and Featured Links. However from those tools, there is not a link back to the dashboard, you either have to click the link in the sidebar or go back.
>
> Could we get a link to /mod at the top of the different moderator tool pages?

Seems like this should be pretty easy and I agree it would be helpful.

**Comment by cellio** [comment]
Ok, most pages do have it in the right column; I just happened to pick the one that doesn't (featured posts) when looking at the report.  Lowering priority.

**Comment by luap42** [comment]
Moderator pages could probably need some "unification in theme", in which this issue could be resolved too.

**Comment by cellio** [comment]
I think we want to put the following on each of the nine pages under app/views:

```
<%= link_to moderator_path, class: "has-font-size-small" do %>
  All Moderator Tools
<% end %>
```

(I pattern-matched that from app/views/admin/index.html.erb)

Some of the mod tools are under app/views/moderator; some (like flags) are elsewhere.

I am a Ruby newbie.  Rather than cut/pasting that nine times, should I do something with includes or inheritance or something? 

We could also make the analogous change for the 13 pages under "admin", but there are way fewer admins than mods, so that'd be lower priority.
