### ISSUE TITLE
Avatar overflow: user avatars can exceed intended space and affect spacing

### ISSUE THREAD

**Issue by cellio** [codidact/qpixel#291]
See the overly-tall avatar in the second row:

![screenshot](https://user-images.githubusercontent.com/5557942/99174774-b23bff80-26d8-11eb-94a9-05357ab67073.png)
 
I don't know what causes *this* one to be tall, where most others are (I think) resized.  I think I've seen some others that were either wider or taller than the intended space.  

I don't think we want avatars that are "too tall" or "too wide" for our intended design.  Ideally we would catch this at image-upload time and either resize or crop, but that's more complex.  When *displaying* avatars, should we enforce the bounding box we want somehow?

**Comment by Technohacker** [comment]
Mind if I make a PR for this? I've solved it with a fixed width/height and `object-fit`
![image](https://user-images.githubusercontent.com/11648300/99674003-74095c00-2a9b-11eb-989e-c53ffd8730d9.png)

**Comment by luap42** [comment]
Not at all.

**Comment by razetime** [comment]
Similar issue on the profile page can probably be fixed the same way: [User Razetime](https://codegolf.codidact.com/users/53310)
