### ISSUE TITLE
In user list, reported number of posts includes deleted posts

### ISSUE THREAD

**Issue by cellio** [codidact/qpixel#293]
I just noticed this entry in the user list on Code Golf:

![msh210, 11 rep, 3 posts](https://user-images.githubusercontent.com/5557942/99203389-66449580-2780-11eb-81f5-aad1ae62503d.png)

I clicked through to see the three posts, but there was only one:

![screenshot](https://user-images.githubusercontent.com/5557942/99203404-79576580-2780-11eb-9e4e-a920e613d7fe.png)

Using the mod tools, I can see that there are two others, which are deleted.  We shouldn't be counting those.

While I'm tempted to set the priority for a minor data mismatch at low, this particular one can be confusing and, more importantly, it kind of broadcasts that people have deleted posts, which I don't think we should be rubbing in people's faces.  In this case they were self-deleted, but that won't always be the case.

**Comment by Taeir** [comment]
This was fixed with the introduction of detailed user cards in 88307f6e.
