### ISSUE TITLE
Keyboard shortcuts for navigating categories don't work

### ISSUE THREAD

**Issue by cellio** [codidact/qpixel#294]
https://meta.codidact.com/questions/279094

> The keyboard shortcuts for going to individual categories (like g c 1) don't do anything for me.
>
> Note that the shortcut for the category page (g c c) works fine, and so do the shortcuts for the category specific tags (like g t 1), so it's not specifically the number keys not working.

Reproduced by Moshi.

**Comment by MoshiKoi** [comment]
No repro now; Meta post has also been marked complete.

**Comment by cellio** [comment]
Comment from luap42 reporting a fix: https://meta.codidact.com/comments/thread/1904#comment-8071
