### ISSUE TITLE
Mark all notifications as read

### ISSUE THREAD

**Issue by razetime** [codidact/qpixel#298]
It is sometimes annoying to click my notifications one-by-one to mark all of them as read. 

**Describe the solution you'd like**
I'd like a single button to mark all my notifications as read.

**Comment by cellio** [comment]
Closing the notifications dropdown has this effect, but I think that's counterintuitive and undesirable.  (I would prefer that closing the notifications dropdown leave individual notifications in their current read/unread state.)  A "mark all as read" link would be clearer.
