### ISSUE TITLE
Don't show "close" (or "delete") links to people who can't use them

### ISSUE THREAD

**Issue by cellio** [codidact/qpixel#299]
https://meta.codidact.com/questions/279268

I can't remember if this is already covered on the abilities branch, but I don't think so -- I think that's about *who can use those privs* but didn't change the UI.  If I'm wrong, let me know.

We currently show the "close" link to all users, and users who can't vote to close get a 403 if they try.  That's not good, especially since we don't even give a meaningful message like "Sorry, but you don't have the 'close' privilege yet" -- we just say "failed", leading the user to think it could be a transient problem.

We shouldn't show close and delete options to people who can't use them.  If we move them onto the Tools menu (which I've proposed elsewhere), we could plug into the same logic that governs which options are shown on that menu -- I think that's already sensitive to privileges (correct me if I'm wrong).

**Comment by galegosimpatico** [comment]
[complexity: easy][0], I guess.

Maybe even [meta: good first issue][1], I can't have such a deep look to know for sure.

[0]: https://github.com/codidact/qpixel/labels/complexity%3A%20easy
[1]: https://github.com/codidact/qpixel/issues?q=is%3Aissue+is%3Aopen+label%3A"meta%3A+good+first+issue"

**Comment by luap42** [comment]
The User Abilities PR #132 should resolve this or at least drastically improve the current situation,

**Comment by galegosimpatico** [comment]
> The User Abilities PR #132 should resolve this or at least drastically improve the current situation,

Additionally, I didn't tell but I was _hoping_ that fixing this now _maybe_ can be more or less frictionless with the User Abilities PR. Yet even so, I would suggest postponing this. :)
