### ISSUE TITLE
Clicking the close link under a question brings up the list of close reasons 3 times

### ISSUE THREAD

**Issue by CharlieBrumbaugh** [codidact/qpixel#30]
**To Reproduce**
1. Go to https://meta.codidact.com/questions/39447
2. Click on "close"
3. See the possible close options 3 repeated 3 times.
**Expected behavior**
All options only show once.

![image](https://user-images.githubusercontent.com/12149031/79624694-b96a4300-80e0-11ea-9f64-56e2daf4f449.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome

**Comment by ArtOfCode-** [comment]
Data issue rather than a software bug, fixed now. Thanks for the report!
