### ISSUE TITLE
Categories page should use same order as nav bar

### ISSUE THREAD

**Issue by cellio** [codidact/qpixel#300]
https://meta.codidact.com/questions/279295

Categories for a community are shown in the "nav bar" at the top in a certain order.  (There are defaults, or the order can be specified when configuring categories.)  There is also a list of categories behind the "Categories" link at the top.  The orders don't match.  Can the category list show categories in the same order as the nav bar?

**Comment by cellio** [comment]
Assigning to @luap42 because I believe the communities branch fixes this indirectly.

**Comment by Trilarion** [comment]
- "the order can be specified when configuring categories." Cannot find the location to specify a custom category order. Where is it?
- "the "Categories" link at the top" Cannot find that either. There does not seem to be a link to /categories anymore, even though the URL still gets routed to some output. And the order is indeed different (alphabetically on /categories).

Just posted a PR that would fix the sorting order (#774), but I'm not sure if the categories page is in use anymore.

**Comment by cellio** [comment]
Category order can be set by an admin at (url)/cat#/edit, e.g. https://meta.codidact.com/categories/30/edit and then in the Display section set Sequence.

I don't know if the categories page is still linked anywhere in the UI, but the link in the meta post reporting the issue still works: https://meta.codidact.com/categories . I think this used to be linked in the header?

**Comment by Trilarion** [comment]
It might be what the community logo leads to if no category is set as homepage. One would need to think carefully about the usefulness of it and where to put a link and about delineation to the dashboard. Probably something for a meta discussion.
