### ISSUE TITLE
Edit suggestion accepts more than five tags, but that can't be approved

### ISSUE THREAD

**Issue by cellio** [codidact/qpixel#301]
https://meta.codidact.com/questions/279303

> See suggested edit https://languages.codidact.com/posts/suggested-edit/221.  Though it doesn't appear on it, my suggested edit apparently included more than five tags, which isn't allowed. However, this was not caught when I suggested it, but only when the poster tried to approve it.

Whether editing or suggesting an edit, we should do the same validation checks that we do when creating a post, in the front end, and if there's a problem, prompt the user to fix it.  This would include too many tags, missing title, and body too short.

**Comment by trichoplax** [comment]
Confirmed that this still happens.

Sorry for the pending edit on your question Monica - please reject. It was only after I pressed save that I realised I should have tested this in development, now that I have QPixel running locally.
