### ISSUE TITLE
Allow category to give non-standard reputation

### ISSUE THREAD

**Issue by cellio** [codidact/qpixel#303]
Prompted most immediately by https://codegolf.codidact.com/questions/279258, but I've been anticipating this issue for a while.

We're probably going to have reputation for a while, even if it's nerfed by abilities.  (It does little harm, once abilities take over, and some people strongly want it.)  And even if reputation itself goes away, we're going to eventually have some sort of "user stats" that convey information about participation/contributions.  So whatever those stats end up being, they're largely based on posts.

A community might want to base these stats only on "primary function" categories -- Q&A, challenges, resources, but not a sandbox and some might not want to count meta.  On the flip side, there was some discussion on EE (https://electrical.codidact.com/questions/276570) about wanting posts in the Papers category to give *more* rep for upvotes.

The request here is to add, to the configuration of a category, a way to set an upvote multiplier:
- 0: disable rep (up or down)
- 1: standard rep levels  (default setting)
- 2: double rep for upvotes (downvotes unchanged)

This should enable both of the scenarios that have been raised without letting things run wild.

**Comment by cellio** [comment]
An alternative approach suggested at https://codegolf.codidact.com/a/279258/279366 is to allow per-category changes to the rep values for different post types.  We have this now as a site-wide setting.  Would supporting category overrides be easier?  A good idea, or too complicated?

**Comment by ArtOfCode-** [comment]
Closing this with #391. The fix there only provides for changing rep per-post-type, but making that per-post-type-per-category is significant complexity that's likely to make things fragile and prone to breaking. Rep can still be changed per-category: just create a post type to use only in that category.
