### ISSUE TITLE
500 Server Error when trying to access a user's flags

### ISSUE THREAD

**Issue by MoshiKoi** [codidact/qpixel#306]
As a mod, I tried to access a user's flags by clicking on the flags link on their profile page (the one that says "0 flags", "1 flag" etc.). However, it returned a 500 server error.

I can access my own flags fine.

Error ID: 4343f340-ecc4-4e29-a1f8-b1794115e435

**Comment by cellio** [comment]
FWIW, as an admin I don't see this behavior.  I would have expected mods and admins to go through the same path (admins have the mod flag, but also other things).
