### ISSUE TITLE
Add handled flags to mod flags list (separate from active ones)

### ISSUE THREAD

**Issue by cellio** [codidact/qpixel#307]
Two use cases:

1. Occasionally I see a flag but don't handle it immediately (like, maybe I need to consult someone else first, or investigate something).  Later, I see the flag is gone and am curious what happened to it.  That info isn't available through the mod tools.  If I remember who raised it I can look for it in that user's flag history, but that's cumbersome.

2. This doesn't happen much on our communities *now* because they're smaller and have lighter activity, but this happened Somewhere Else all the time so we should anticipate it.  Each moderator has only a partial view of what's going on -- in our case, the flags you personally handled, plus whatever conversations you have or other bits of information you see.  It can be very useful to get an overview of recent activity -- this many recent handled flags, link to details.

The flag view that shows up in the user history should be fine for this -- show the flag, who raised it (ok that's a small difference), and what the dispensation was including any custom message the moderator sent back.  This could be a separate "tab" on the flags page in the mod tools.

**Comment by ArtOfCode-** [comment]
https://github.com/codidact/qpixel/commit/aa62be3af4cc5c49c770a581412efec212d8030c
