### ISSUE TITLE
"Email moderators" (admin tool) consistently emits a 500 error

### ISSUE THREAD

**Issue by cellio** [codidact/qpixel#316]
I tried to send email to moderators using the admin tool, from Meta, a few days ago and got a 500 error, which I reported in chat.  Since then we've bounced the server a couple times, so I just tried again.  It's still happening.  I tried on another community too, in case it was something about Meta, but no luck.

Meta error code: 03fdbd73-cf8a-4354-bd2b-c2bb520109c1
Judaism error code: 66fc0fcd-2fef-4874-8a29-1768f433fde7

I'm marking the priority as medium as a compromise.  We rarely need to email moderators, but when we do it's pretty important.

Here's the console from a different attempt on Meta:

![screenshot](https://user-images.githubusercontent.com/5557942/100411555-1c8d6200-3040-11eb-88be-f67334ca0d78.png)

**Comment by ArtOfCode-** [comment]
That's an... interesting trace. Hopefully not too difficult.

**Comment by cellio** [comment]
Fixed now, but I don't have a PR link.
