### ISSUE TITLE
No posts are created during the seed

### ISSUE THREAD

**Issue by CharlieBrumbaugh** [codidact/qpixel#32]
Currently when trying to seed the posts table it will fail because the post_type_id is not set.

Changing 

`- post_type_id: <%= PolicyDoc.post_type_id %>`
to
`- post_type_id: 3`

in db/seeds/posts.yml

fixes the problem, but I don't know if that's the way it should be fixed.

**Comment by ArtOfCode-** [comment]
Hm. This has caused problems before, but I don't like making it a static number because the ID might not always be 3. I'll have a look - I suspect there's a longer but more reliable way of putting it.
