### ISSUE TITLE
History diff does not show retagging

### ISSUE THREAD

**Issue by cellio** [codidact/qpixel#326]
https://meta.codidact.com/questions/279624

In the revision history, the diff for a revision that changed tags shows the resulting tags on both sides of the diff, instead of the difference.  I haven't yet seen a proposed edit with these conditions, so don't know if it occurs there too.  I'm pretty sure we had before-and-after tags properly showing before the latest updates, so this is probably a regression.

Example post where this happens: https://meta.codidact.com/questions/279268

Priority medium if it only affects histories, but high if it affects suggested edits too.  Setting to high initially for visibility.

**Comment by cellio** [comment]
Another case: I approved one edit (which came through as two?) here, to add the status tag: https://meta.codidact.com/posts/279669/history.  When reviewing the edit I saw the tag diff.  The history does not show it.

**Comment by cellio** [comment]
And I saw the tag in the edit review, so lowering the priority as previously stated.

**Comment by cellio** [comment]
More cases:
https://judaism.codidact.com/posts/280935/history
https://judaism.codidact.com/posts/280934/history

This bug is making it difficult for communities to audit edits.  The inability to see tag edits has already caused friction on another community.  How hard is this to fix?

**Comment by cellio** [comment]
I'm not seeing any diff at all now for the questions I linked, for example:

![Screen Shot 2021-03-20 at 10 34 20 PM](https://user-images.githubusercontent.com/5557942/111891875-8b664080-89cc-11eb-98a4-e5cf0213d063.png)

That was almost certainly a tag-only edit.

**Comment by ArtOfCode-** [comment]
As with a lot of things, this isn't retroactive - we don't have the data for what those edits were, the database thinks the before and after tags are the same, so it doesn't show the unchanged state.

**Comment by cellio** [comment]
Oh, gotcha -- so shouldn't happen again, but history is what it is.  Thanks.

**Comment by cellio** [comment]
New case (edit 2021-06-01): https://meta.codidact.com/posts/280367/history

Reported in a comment here: https://meta.codidact.com/posts/281137#answer-281137

**Comment by cellio** [comment]
Looks like's showing the correct history now, so I'll close.  If we see a new case we can look at it then.

**Comment by MoshiKoi** [comment]
Apparently this has happened *again*

https://meta.codidact.com/posts/288657

**Comment by Taeir** [comment]
Looks like a classic case of Object Oriented issues with multiple things pointing to the same array when they should have been pointing to different but initially equal arrays.
