### ISSUE TITLE
Add a list of suggested edits awaiting review

### ISSUE THREAD

**Issue by cellio** [codidact/qpixel#328]
https://meta.codidact.com/questions/279637

Now that most people can't edit directly and getting edits approved is important for gaining abilities, we should make it easier for people who can review edits to see edits that are awaiting review.  I propose a simple page of links.

We might want to separate posts and tags, since their formatting needs are different.  For posts, we should show the title, the post type  (e.g. "answer", or if we can do "answer by Moshi" that's even better for disambiguation), and a link to the suggested edit.  For a tag, we should show the tag name and the link to the suggested edit.  The suggested-edit page shows the diff, who proposed it, and when, so we don't need to duplicate any of that on the main list.

I propose that we add a link to this list, called "Suggested Edits", in this box:

![widget screenshot](https://user-images.githubusercontent.com/5557942/100672471-fca3ba00-332f-11eb-858b-8dd05c85b0c1.png)

As part of that, we should rename the widget from "Moderator Tools" to something like "Community Tools" and show it to anybody who has any applicable ability.  Right now moderators and admins see it; moderators see only the first link and admins see both.  So to this we'll add a third group, who can see only the new link and not the other two, and mods and admins will get an additional link.

(Please put the link first in the list, so restrictiveness increases as you go down the list.)

Related: https://github.com/codidact/qpixel/issues/325

**Comment by MoshiKoi** [comment]
> if we can do "answer by Moshi" that's even better for disambiguation

Is there really a point in disambiguating like that? If you have the link to the post the suggested edit is on, that's already about as specific as it gets.

**Comment by luap42** [comment]
Marking as average complexity, but it should be at the lower end of average.

----

What needs to be done (with a topical area and estimated complexity)

* **[Design 2/10]** Find how to link to the feature (for example, I'd rather have it as a new link in the category-specific header, next to "Posts" and "Tags" as "Suggested Edits", but that's just my humble opinion)

* **[Config 1/10]** Add a new route for the feature (either per-category as above or per-community)

* **[View 3/10]** Add a template listing all pending suggestions and link to them. Bonus points for nice design.

* **[Bonus 2/5]** Add nice filtering options for the view, possibly allow mods to see completed reviews.

**Sum: 8/35, Average: 2.3/10**

**Comment by cellio** [comment]
I like your idea of putting it in the category header.  That also makes it more visible on a phone (where the right column...isn't).  I also like the idea of it being suggested edits *in this category* (or on tags used in this category); context is good.

Having a tab for completed reviews sounds like a nice improvement.  I don't think we need to limit it to mods, though; if the review is public once handled (I think it is but haven't checked), then it's already publicly available, so in the interest of giving communities tools to manage themselves, why not expose it here?

**Comment by cellio** [comment]
Fixed by luap42 (who has already tagged the meta question).
