### ISSUE TITLE
Favicon overflow: several in different places; which is the one true favicon?

### ISSUE THREAD

**Issue by cellio** [codidact/qpixel#329]
Actual problem: there are several favicon ico files in various places in the repo, with varying names.  Can we please try to identify the one true favicon, have it live in a logical place, and remove the others so we don't trip over them next time a favicon goes missing and needs to be configured?

----

Original bug report:

Visit a community where the favicon (blue logo) shows up as expected in the browser tab.  Visit a question.  Visit its history link.  The favicon disappears and cannot be recovered -- all pages on that community now show the "missing favicon" graphic in the browser.

Things that did not fix it: flushing the browser cache, restarting the browser (which also applied an update), restarting the machine.

Someone in chat reported the following:

> there seems to be a <link rel="icon" href="/assets/favicon.ico"> defined but e.g. https://codegolf.codidact.com/assets/favicon.ico doesn't seem to exist

I don't know whether the problem here is the presence of the link or the absence of the file, but we should make them match.  Some people are reporting this mismatch on other pages (like  https://codegolf.codidact.com/assets/favicon.ico and https://meta.codidact.com/assets/favicon.ico.  Sounds like the easiest fix is to put favicon.ico in the right place?

The immediate problem was that site settings for the icon had been nulled out by the recent DB update.  I've edited the settings on all communities and favicons are now back.  But I am leaving this open because there is still some confusion/mismatch; the link above is looking for favicon.ico but the value @luap42 had me edit into the site settings is /assets/square.ico.  And while trying to debug this we found several ico files in different locations in the source repo.  Let's tidy this up please.

**Comment by Quintec** [comment]
My guess is a favicon.ico https://github.com/codidact/qpixel/tree/develop/public/assets would fix it

**Comment by ArtOfCode-** [comment]
Correct favicon added to public/favicon.ico
