### ISSUE TITLE
Weird wrap in the bottom "Are you sure link" when asking a meta question at full width

### ISSUE THREAD

**Issue by CharlieBrumbaugh** [codidact/qpixel#33]
Here https://outdoors.codidact.com/meta/ask

![image](https://user-images.githubusercontent.com/12149031/80160995-494e3800-858c-11ea-8155-515c92273f5b.png)

the word wrap looks weird because of the split when the div is at full size. It caused by `notice a{` rule in application.css

Also the notices above and below the question have different text, not sure if that is a bug or done that way on purpose.

**Comment by CharlieBrumbaugh** [comment]
@ArtOfCode-  This bug seems to have disappeared with the switch to the categories.
 https://outdoors.codidact.com/categories/5/posts/new/1

**Comment by ArtOfCode-** [comment]
Yup, different view. It's still lurking in the background in the old view, but since nothing uses that any more, it's functionally gone, just waiting for me to remove the old code.
