### ISSUE TITLE
Abilities page has broken link

### ISSUE THREAD

**Issue by cellio** [codidact/qpixel#331]
https://meta.codidact.com/questions/279670

The abilities page has a link to https://meta.codidact.com/abilities/edit_tagd.  That doesn't exist.  The correct link is https://meta.codidact.com/abilities/edit_tags  (tag*s*, not tag*d*).

I didn't find a "seed" page in the doc repo; I think this bug is directly in the code, hence filing here.  If there's something that needs to be done in the doc repo too, please speak up.

**Comment by sau226** [comment]
I'm happy to take this issue and will be offering a PR soon
