### ISSUE TITLE
Help for close ability has unrendered markdown (doesn't appear to be a problem in the doc source)

### ISSUE THREAD

**Issue by cellio** [codidact/qpixel#332]
https://meta.codidact.com/questions/279669

The page on hold votes (https://meta.codidact.com/abilities/flag_close) has the following rendered text:

     The reasons for placing a post on hold vary from site to site; the guidance for posts on this site is available in the [Help Center](/help/faq).

This markdown didn't get properly translated/rendered, but this, elsewhere in the abilities help, did (from the source in codidact/docs):

    This ability allows you to post questions, articles, and answers without limit, as well as being able to vote on content and leave comments on any post. You can see guidance on [asking questions](/help/how-to-ask) and [how to vote](/help/voting) in the Help Center.  

I started to file this bug against the docs repo, but I don't see anything there to change.  I also checked the FAQ slug on Meta (looking for a case problem) and it's as linked here.

**Comment by sau226** [comment]
I'm happy to take this issue and will be offering a PR soon

**Comment by cellio** [comment]
Thanks for the explanation of how the seeds are structured. We should find a place in the developer docs to add it.
