### ISSUE TITLE
Diff on edit history is hidden underneath the sidebar

### ISSUE THREAD

**Issue by CharlieBrumbaugh** [codidact/qpixel#34]
After navigating here https://outdoors.codidact.com/posts/74762/history
and opening the first history option it looks like this,

![image](https://user-images.githubusercontent.com/12149031/80291915-ffda2600-870e-11ea-9db1-2946abc9651b.png)

The top of the history diff is getting hidden underneath the sidebar.

**Comment by ArtOfCode-** [comment]
Fixed by a Co-Design and layout update.
