### ISSUE TITLE
Deleting a question doesn't delete its answers

### ISSUE THREAD

**Issue by cellio** [codidact/qpixel#342]
The question https://outdoors.codidact.com/questions/279265#answer-279298 was deleted by its author.  It had one answer.  That answer does not show as deleted, and, further, it is linked from the author's profile.  A user who can't see deleted questions, when following that profile link, gets a 403.  That's confusing.

Deleting a question should delete its answers too.  However, we can't just run through the answers and delete them, because if the question is later *undeleted*, the answers should be in their original states.  (An answer that was deleted before the question was deleted should stay deleted.)  For the question page this means apply the styling from the question to answers too, but something else needs to keep it out of the profile.  I'm not sure how we handle that now, like what happens if you delete an answer directly, but we should do the same thing for "deleted because parent was deleted" cases.

We've seen this problem before, and then it got fixed, and now it's happening again.  But I don't remember enough about the previous case to know how we fixed it.

I'm marking this high priority because of the profile links; if it were merely that the question page looks funny, that'd be lower.

**Comment by cellio** [comment]
Apparently my memory is only half-right: we found this a few months ago and *didn't* fix it.  https://github.com/codidact/qpixel/issues/153

**Comment by cellio** [comment]
@luap42 made the following suggestion on the older bug (which I am going to close in favor of this one):

----

Suggestion, how I would do this:

We add a helper function to the Post model named `deleted?` with this mock-code:

    def deleted?
      deleted || parent&.deleted || false
    end

Then we replace every other occurence of Post#deleted with Post#deleted?.

This has the advantage, that deletion "propagates" immediately and doesn't care, whether a post has been deleted specifically or per the parent post being deleted.

**Comment by cellio** [comment]
@ArtOfCode- I take it that this won't happen again (you modified the code that deletes top-level posts, I assume?).  But there are extant cases that still have 404-ing links on people's profiles.  Is there a way to do a one-time cleanup on these, or at least get a report of them for manual review?  I assume there aren't many but I've seen two and don't know how many more are out there.

**Comment by ArtOfCode-** [comment]
Aye, I can run cleanup when I've got some time spare
