### ISSUE TITLE
Tags on imported questions don't link correctly.

### ISSUE THREAD

**Issue by CharlieBrumbaugh** [codidact/qpixel#35]
Tags that were imported,

https://outdoors.codidact.com/questions/tagged/5/paragliding
https://outdoors.codidact.com/questions/tagged/5/bears

are not showing up correctly when you click on them, while tags on questions that have been created since, do show up with a tag page and link to those questions, but not to questions that were tagged with the same tag in the imported content.

This shows correctly for the new question,
 - https://outdoors.codidact.com/questions/tagged/5/bats
But does not link to these questions
- https://outdoors.codidact.com/posts/search?utf8=%E2%9C%93&search=bats

**Comment by ArtOfCode-** [comment]
Should be fixed now - this was (another) bug with the import process.
