### ISSUE TITLE
Community ads use the wrong URL

### ISSUE THREAD

**Issue by cellio** [codidact/qpixel#355]
I saw the following ad on Meta:

![screenshot](https://user-images.githubusercontent.com/5557942/102703308-3b47d880-423b-11eb-8e86-c12e016ac41d.png)

When I clicked on it, I got a 404 because the URL used meta, not photography, in the URL.  When I replaced the "meta" part of the URL and made no other changes, it worked.

**Comment by ArtOfCode-** [comment]
Fixed

**Comment by cellio** [comment]
Still happening on Meta (at least).  Reopening.
