### ISSUE TITLE
Inline search is not dismissable

### ISSUE THREAD

**Issue by cellio** [codidact/qpixel#356]
When I saw the announcement I checked out the nice new inline search:

![screenshot](https://user-images.githubusercontent.com/5557942/102703446-c6759e00-423c-11eb-9b8f-f11feeed20df.png)

I didn't actually want to search for anything at the time, though; I was just curious.  So I tried to dismiss it, because of course a pop-out search box covers other things on the page.  I couldn't figure out how to do that without reloading the page.

There's no "x".  "Escape" didn't dismiss it.  Clicking elsewhere on the page didn't dismiss it (I didn't think it would, but just being thorough).

Can we add some obvious way to dismiss the pop-out?

**Comment by ArtOfCode-** [comment]
Same as most of our other modals or popouts - clicking on Search a second time will close it.

**Comment by cellio** [comment]
Oh, ok.  I didn't think of that.  Verified that that works.
