### ISSUE TITLE
User list no longer shows moderator/staff status

### ISSUE THREAD

**Issue by cellio** [codidact/qpixel#358]
When we added the new usercards, we lost the moderator and staff indicators on the users list.  We want to make it easy for people to identify who those people are -- yes it's on the individual profile pages, but you have to know or suspect first in order to find it there.  We want people to be able to scan or filter the user list to find out who's in charge around here.

Adding a "moderators & staff" tab on the users page would accomplish this, and would also make it easier for people to find those people in larger user lists.  It would be nice to *also* have an indicator with the usercard on those lists, like we did, if that's not hard.  It doesn't have to be as large as it was.

**Comment by ArtOfCode-** [comment]
Closed by #364
