### ISSUE TITLE
Question lists are missing pagination

### ISSUE THREAD

**Issue by cellio** [codidact/qpixel#36]
With the rollout of categories, the question list is missing the pagination controls at the bottom, so only one screenful of questions is available there.  This is true for all tabs (questions, age, score, lottery -- though I don't think lottery ever offered more than one page), on both Writing and Outdoors.  (Meta doesn't have enough questions to trigger pagination.)

**Comment by ArtOfCode-** [comment]
Fixed by `art/categories` 1b00c71.
