### ISSUE TITLE
Can't approve suggested edit because of required tags, even though the existing tag is required

### ISSUE THREAD

**Issue by cellio** [codidact/qpixel#360]
This is going to be a little convoluted.

Several months ago, [this edit suggestion](https://meta.codidact.com/posts/suggested-edit/56) was submitted on Meta, where it went unnoticed.

Now that we have the Suggested Edits link, people can see it.  Great!

It's a good edit.  Several people tried to approve it.  But the approval is rejected because the post only has the "announcement" tag, which is not one of the required Meta tags.  We don't have a way to modify a suggested edit, and I don't want to decline it (because I would then have to recreate it, and because it would ding the suggestor and it's not that person's fault).

Someone suggested a clever workaround: add that tag to the required list and then approve the edit.  I added the tag; you can see its status in the following screenshot.  But the edit is still rejected.

![screenshot of rejection](https://user-images.githubusercontent.com/5557942/102705042-fdee4580-4250-11eb-931f-09d1d76df9a7.png)

You can even see "announcement" in the "must be one of these" list in the error message.

Two issues, then:

1. The tag's status *at the time of the edit approval* doesn't seem to be being checked.
2. There's no way for a reviewer to correct a problem of required tags.  Even if this hack had worked, it would have only worked because I have the admin privileges to edit the category.  In the case where a required tag is missing from an edit that's being approved, is there a way to enable the reviewer to add one of the tags so the edit can go through?

**Comment by MoshiKoi** [comment]
>  In the case where a required tag is missing from an edit that's being approved, is there a way to enable the reviewer to add one of the tags so the edit can go through?

Alternative suggestion: Just disable validity checking at the time of approval, and validate it *only* when the edit is suggested. That would fix #301 as well

**Comment by cellio** [comment]
What if the requirements change between when the edit is suggested and when it's approved?  We should check on the way in, but that won't necessarily prevent problems.  It's possible that this is what happened here; the edit is old enough that maybe we didn't yet have required tags.  (I don't remember.)

**Comment by MoshiKoi** [comment]
> What if the requirements change between when the edit is suggested and when it's approved?

IMO, if it's valid at the time of suggestion, it should be considered valid for the purposes of approval. In this case, the reviewer could always just add a required tag as another edit, there's no need to "fix" the existing suggestion.

**Comment by luap42** [comment]
This has been fixed in the specific instance.

There might still be some old suggestions with similiar problems, but Art or me can fix them without rejecting them by making the neccessary updates in the rails console.

There shouldn't be new suggested edits with these problems, because we implemented validation also  on the time of the edit suggestion now, which would have prevented such issues if we had done so earlier.

@MoshiKoi's suggestion likely won't work, because the validation is done on the model and not on the controller side. This means, that even if we'd make the change via a special Ruby script, we'd need to abide to the validation rules. It's not possible to circumvent this (easily) just for suggested edits.

**Comment by cellio** [comment]
Thanks for the specific fix (and now I know to just ask you if it comes up again).

There could be new suggested edits with this problem, if the rules change between when the edit is suggested and when it is reviewed (like if the list of required tags changes and the post had one but doesn't now).  This is a very unlikely case now -- suggested edits are more visible, and changes to required tags are rare.
