### ISSUE TITLE
Logo becomes huge on small viewports

### ISSUE THREAD

**Issue by cellio** [codidact/qpixel#361]
This browser window is 521px wide:

![screenshot](https://user-images.githubusercontent.com/5557942/102705313-3cd1ca80-4254-11eb-89e2-81e402f33998.png)

The Meta logo looks about like you'd expect.  Some UI elements have dropped out (responsive design), but this works.

This window is a little narrower, 507px:

![screenshot](https://user-images.githubusercontent.com/5557942/102705319-5ecb4d00-4254-11eb-92b2-b0d3b233eb23.png)

Holy logo, Batman!  It's suddenly much bigger, when things should instead be getting smaller or dropping out.

In chat, @MoshiKoi reported the huge logo on a phone.  I couldn't reproduce that on my phone (which is probably a little bigger), but I was able to make it happen in a small-enough desktop window.

**Comment by ArtOfCode-** [comment]
Fixed
