### ISSUE TITLE
Fat navbar

### ISSUE THREAD

**Issue by MoshiKoi** [codidact/qpixel#362]
Yes.

![Screenshot](https://user-images.githubusercontent.com/54333972/102705316-2d925300-423b-11eb-9b63-d351749d11a0.png)

Essentially, the button text word wraps, which along with the oversized logo means the navbar takes up about a third of the available screen area (YMMV)

On discord, Cellio suggested only taking the first word of the button text when on mobile view to remedy this.

**Comment by cellio** [comment]
When viewport size causes line wrap to kick in, I suggest that "suggested edits" become "edits" and the post button use the first word (which should always be a verb, like "ask" here).  That should prevent the line wrap that pushes the main content farther down.

Especially consider that on some communities, category names already wrap on small viewports.  So a phone user gets a double whammy here.

For the logo specifically, see https://github.com/codidact/qpixel/issues/361.

**Comment by ArtOfCode-** [comment]
Fixed

**Comment by cellio** [comment]
@ArtOfCode- , I think it would be better to rename Suggested Edits to Edits only in small viewports where there's not enough room.  The extra clarity on desktop views is helpful.  Can we do that?

**Comment by ArtOfCode-** [comment]
Not easily, no, it would require excessive complexity to add

**Comment by cellio** [comment]
Ok, understood.
