### ISSUE TITLE
Usercard not displaying correct post totals

### ISSUE THREAD

**Issue by Mithrandir24601** [codidact/qpixel#365]
See https://meta.codidact.com/posts/280017#answer-280017

Some usercards display post totals of 0 for users who've made >0 posts, but not for every user, or all the time.

Reproduced on meta - visiting random posts gives this behaviour. Not confirmed on other communities/sites.

(Using the latest version of Firefox on Windows 10)

**Comment by cellio** [comment]
I'm marking the priority as high because we're trying to promote this new display in favor of pure rep, which will be more convincing to the community if it's correct.

**Comment by sau226** [comment]
Just so this is clear: I am not working on this issue at present and am merely providing the details below as a pointer for anyone who is looking to help out here.

The buggy post totals are rendered by `app/views/users/_common_card.html.erb` in this repo, which fetches the metrics from lines 65-85 of `app/models/user.rb`.

My guess is that the best place for you to look for a place to start would be to check if the metrics systems are really returning the results they should be.

**Comment by ArtOfCode-** [comment]
_Should_ be fixed, I've made the cache time longer for these values but added cache-busters so that they update immediately when we know there's been a change. Reopen if not, once deployed.
