### ISSUE TITLE
Hot questions (really hot posts) from other categories should indicate the other category

### ISSUE THREAD

**Issue by cellio** [codidact/qpixel#37]
The "hot questions" section of the main page on Writing currently shows:

![Screen Shot 2020-04-26 at 3 16 40 PM](https://user-images.githubusercontent.com/5557942/80317321-206ab480-87d1-11ea-9e5e-1cd7a1d97f18.png)

The first and last of these entries are meta posts, but you can't tell by looking at them.  In the future there could be hot posts from other categories (like a blog), and some of those might have titles that resemble those on main Q&A, so going by titles isn't a long-term fix.

Could this list indicate the category if it's something other than the current one?  Or, if that would be too weird on meta where things would logically be tagged Q&A, maybe we should just show the category for everything?

Also, the section is currently titled "Hot Questions", but soon we will have things -- that I hope might become hot -- that are not questions.  How about "Hot Posts"? 

If we can get away from "hot", which is kind of SE-insider jargon, then that's even better, but the obvious label includes "active" and that could cause confusion with the "activity" tab on the question list.  So if anybody has any ideas then let's consider them, but in the meantime let's de-questionize it.

**Comment by ArtOfCode-** [comment]
Fixed in `art/categories` a504a971ddfb268a7ad2b1d401dac9a76b035e74.
