### ISSUE TITLE
Notification for suggested edit uses local community's URL slug, not where the edit is

### ISSUE THREAD

**Issue by cellio** [codidact/qpixel#373]
https://meta.codidact.com/posts/280086

If you click on the notification for a suggested edit, and that suggested edit is on a different community than the one you're presently on, the link is wrong (usually 404) because it uses the local slug instead of the one for the correct community.

I'm pretty sure this is a recent regression; I'm usually parked on meta and approved an edit on Judaism a few days ago because I was notified.  I could be misremembering where I saw the notification, but we also haven't gotten reports of bad links before now.  I just found that notification and followed the link from meta, reproducing this bug.

**Comment by sau226** [comment]
Fix PR submitted as per PR link above - you were right, it was a 1 line code fix
