### ISSUE TITLE
On mobile, if a category name is too long it line-wraps -- but at every token, not just when needed

### ISSUE THREAD

**Issue by cellio** [codidact/qpixel#374]
Photography has a category that was, until a few minutes ago, named "Contests/Critique".  This made the title wide on a phone, so to try to improve the spacing there without hurting the intent behind it, I changed it to "Contest / Critique".

This rendered on my phone as:
> Contests
> /
> Critique

I was expecting the '/' to go with one word or the other, not claim a line of its own.

I then tried to set it to "Contests /\&nbsp;Critique", but the nonbreaking space wasn't interpreted; it showed literally in the header.  So that's no good.

The name is currently "Contests, Critique" so it will consume two lines but not three on a phone.  I don't know if that's actually an improvement.

Can we do better flow layout of multi-token names in cramped quarters?

**Comment by ArtOfCode-** [comment]
Try using the literal character for an NBSP instead of the HTML entity. Copy everything inside the code markup: ` `

**Comment by cellio** [comment]
That didn't work, alas -- I still got the '/' on its own line, even with that + this character + the second word mushed together.

**Comment by ArtOfCode-** [comment]
We don't have a great deal of control over the wrapping. Since the `/` is separated by a space either side, it counts as its own word, so is eligible for word-based wrapping. I could change it so that the names _don't_ wrap, though that will trigger horizontal scrolling faster.

**Comment by cellio** [comment]
No, I don't think we want that -- on a phone it's ok to wrap *once* (spill onto a second line), and we have some of that.  If we can't control which spaces can break and which can't, then we'll just have to take that into account in names -- while it'd be nice to fix, it's an edge case not worth spending developer time on.  Thanks for looking into it.

**Comment by fedorqui** [comment]
and what about using non-breaking spaces in such cases?
