### ISSUE TITLE
Some suggested edits and history entries lack diffs

### ISSUE THREAD

**Issue by cellio** [codidact/qpixel#379]
Some suggested edits show the diffs just fine and some don't.  Here are some that don't:

https://judaism.codidact.com/posts/suggested-edit/278
https://judaism.codidact.com/posts/suggested-edit/279
https://judaism.codidact.com/posts/suggested-edit/280

And here are some with history that doesn't show diffs either:
https://judaism.codidact.com/posts/279028/history
https://languages.codidact.com/posts/277357/history (look at Moshi's edit 2020-10-02T03:09:16Z)

But here are ones that do show the diff:
https://meta.codidact.com/posts/280081/history
Sigma's edit in the languages example

What these have in common is that they are the article post types with third-party (suggested) edits, either current or in the past.  The example with the correct diff is an edit made by the author.

Is it specific to articles?  Let's have some more test cases of third-party edits:
Diff, answer: https://meta.codidact.com/posts/suggested-edit/276
Diff, question: https://meta.codidact.com/posts/suggested-edit/261
Diff, question, tag edits: all of these that I've looked at: https://meta.codidact.com/categories/3/suggested-edits?show_decided=1
Diff, question, tag edit: https://judaism.codidact.com/posts/suggested-edit/260 (just to establish on a different community)
Diff, answer: https://judaism.codidact.com/posts/suggested-edit/181

Tentative diagnosis: something is messed up with suggested edits, whether pending or approved, for the article post type.

I believe, but cannot prove, that this is a recent change.  The first thing I would check is: did something get missed for articles in the unification of post types?

**Comment by ArtOfCode-** [comment]
[status-norepro] on local dev - a third party suggested edit on an article shows a diff as expected. Is this still an active issue, or is this just a few edits but not an ongoing issue?

**Comment by cellio** [comment]
@ArtOfCode- the ones linked here show no diff.  Do you mean there shouldn't be *new* cases of it?  (I haven't reproduced yet on dev, so that might be correct -- just checking if you think extant cases should be fixed.)

**Comment by ArtOfCode-** [comment]
Just that I can't reproduce locally - it's impractical to fix old diffs, but I wouldn't expect to see new cases.
