### ISSUE TITLE
Add a link to the dashboard somewhere

### ISSUE THREAD

**Issue by cellio** [codidact/qpixel#382]
https://meta.codidact.com/posts/280115

The dashboard (https://meta.codidact.com/dashboard) is a well-kept secret.  We should expose a link to it somewhere.  Somewhere in the site switcher might be one place, and/or in the page footer.

**Comment by razetime** [comment]
Since it links to all the sites, why not keep it on the right side of the navigation bar?

**Comment by cellio** [comment]
The site switcher is there, and from there you can get to any community (handy!).  The dashboard shows you all communities, and all categories in each, on one page, showing you which ones have new posts.  It complements the site switcher for people who are active on several communities, but people learn about it only by word of mouth.  It's more of a power-user tool, not something everybody will use, so maybe the best place for it is in the list in the footer.
