### ISSUE TITLE
Make it easier or more obvious how to close drop-down widgets

### ISSUE THREAD

**Issue by cellio** [codidact/qpixel#383]
Most recently: https://meta.codidact.com/posts/280108

People come to Codidact and aren't clear on how to dismiss things like the inbox.  If they came from SE they expect clicking elsewhere in the page to dismiss a drop-down, but even if they don't come from SE, they're sometimes looking for an "x" or other dismissal path.  Even I, an experienced Codidact user, couldn't figure out how to close the new search pop-out, because I didn't interpret it as "a drop-down like the inbox you learned how to use".

Let's make this easier.  I don't know if "click elsewhere on the page" or "dismiss explicitly via an 'x'" is the better pattern.  My gut feeling is that an "x" is recognizable and doesn't get in the way, but there might be places where it doesn't fit right.  If we want to keep the current behavior (click again, no 'x'), then let's figure out where to put a hint -- maybe one of those "tips" when you open one with a "got it" button to dismiss?  We don't really do just-in-time hints yet, but we aspire to provide some sort of contextual guidance, and maybe this is one of those.

This applies to at least: inbox, search, flags, close.  But Tools is a different kind of widget -- overlay and has an "x".

**Comment by mattjbrent** [comment]
The fix for this issue is addressed by a PR in https://github.com/codidact/co-design/issues/51

**Comment by Istiakshovon** [comment]
Fixed! According to @mattjbrent's PR. But, seems like not working for me. :thinking: Could you reproduce? I had tried by clicking on Esc also.

**Comment by ArtOfCode-** [comment]
Pretty sure that change isn't deployed to production yet.

**Comment by cellio** [comment]
It got deployed at some point since then.  Closing.
