### ISSUE TITLE
For search, allow user to choose current category only or all categories

### ISSUE THREAD

**Issue by cellio** [codidact/qpixel#384]
https://software.codidact.com/posts/279713

This has been on our roadmap for a while; creating an issue to better track it.  When searching, a user should be able to either limit the search to the current category or search the entire community.  Right now it's supposed to do the latter, though because of a bug (https://github.com/codidact/qpixel/issues/249) it might not always produce correct results.

It would be sufficient to allow search parameters like "category:current" or "category:all".  We want to eventually give search a nicer UI where you could just select things (post types, categories, date ranges, etc), but so long as you also have to type search parameters for other things, it's fine to have to do it here too.

**Comment by ArtOfCode-** [comment]
Closed by #554
