### ISSUE TITLE
After posting a comment, another comment box appears and needs to be dismissed or ignored

### ISSUE THREAD

**Issue by cellio** [codidact/qpixel#388]
https://meta.codidact.com/posts/280143

>When I click on "Add a comment" at the end of a post, a box appears where I can type my comment, along with the buttons "Post" and "Discard" below it. But, after I type my comment and click on "Post" another box appears below it for me to type another comment, so I have to click on "Discard" to dismiss the new box.

Reproduced.  After posting a comment, you should see the comments with the "add comment" link, not the textbox as if you had clicked "add comment" again.  Looks like an action is firing that shouldn't.

**Comment by razetime** [comment]
Is this specific to Edge on Win10 as in the post, or is it reproducible on other browsers?

**Comment by cellio** [comment]
I see this behavior in Chrome too (on a Mac).
