### ISSUE TITLE
"Copy link" does not work in Safari

### ISSUE THREAD

**Issue by cellio** [codidact/qpixel#389]
https://meta.codidact.com/posts/280151

In Safari, "copy link" doesn't copy the link and emits a console error.  I reproduced the lack of copying but didn't investigate the console.

**Comment by mattjbrent** [comment]
I think we can close this out. Ive tested in Safari 14 and it's not an issue.

**Comment by cellio** [comment]
Still happens in the originally-reported browser.  What *is* our story on supported browsers?  Is 12.1.1 too old?  Do we support only latest stable of each browser?  We should figure it out and document it.  (I don't normally use Safari and don't know what it's reasonable to expect of people who do.)

**Comment by ArtOfCode-** [comment]
Latest plus previous major version of major browsers (Chrome + mobile, Firefox, Edge, Safari + mobile) is a reasonable assumption for supported browsers. I'll try to have a brief look anyway to rule out any underlying issues, but absent any major issues I'll close this as unsupported.

**Comment by ArtOfCode-** [comment]
Declined on site.
