### ISSUE TITLE
Notifications: "mark all as read" can be cut off or pushed way down; move to top

### ISSUE THREAD

**Issue by cellio** [codidact/qpixel#393]
https://meta.codidact.com/posts/280174

On desktop, the notifications dropdown has a fixed height, which produces a confusing experience if your viewport is shorter than that.  The notifications scroll, but you have to scroll the *page*, not the *notifications*, to get to the "mark all as read" line at the bottom.  On a phone it's even worse; the notifications dropdown doesn't seem to have a max height like on desktop, so you have to scroll past *all* your notifications to get to the bottom.

Why do you care about getting to the bottom? Because that's where "mark all as read" is.

Maybe the notifications control shouldn't be taller than the viewport, but regardless, can we move "mark all" to the top so it's always available?  It looks like there's room on the same line as "notifications", flush right.

Moving it to the top (in addition to or instead of adjusting the height to fit the viewport) would solve a second problem: I have occasionally seen slow rendering of notifications, maybe a bad network connection or something, and it's a little disorienting to see "mark all" show up at the top and then get pushed down as notifications fill in.

**Comment by razetime** [comment]
> I have occasionally seen slow rendering of notifications, maybe a bad network connection or something, and it's a little disorienting to see "mark all" show up at the top and then get pushed down as notifications fill in.
This is just something that generally happens when webpages load. A general solution would be to put a loading symbol as a placeholder till the dropdown is filled in.

**Comment by ArtOfCode-** [comment]
Completed with a patch from @sau226
