### ISSUE TITLE
Show tag descriptions on hover

### ISSUE THREAD

**Issue by cellio** [codidact/qpixel#394]
https://meta.codidact.com/posts/280176

If a tag has a short description, can we show it when hovering over the tag on a post or in a post list?  If there is no description, let's show something like "no description yet" so people don't think it's a bug that we're showing nothing.

While, in the latter case, it would be nice to add a "create description" link, we first need to add suggested edits for tags (https://github.com/codidact/qpixel/issues/325), so that we don't have to check abilities before displaying tag hovertext (which sounds both expensive and confusing).  So for now, just show the text or an indication that there isn't any.

**Comment by cellio** [comment]
@b-Istiak-s did you submit a PR for that?  Has it been tested?  What stands in the way of merging this?

**Comment by b-Istiak-s** [comment]
> @b-Istiak-s did you submit a PR for that? Has it been tested? What stands in the way of merging this?

Simple answer : my PR was merged. 

But we are currently showing normally (no design like how SO shows). I was thinking to do that. But I had gone somewhere else so I Couldn't look. You can check the feature now, go to Meta CD and hover on status-completed, status-declined tag than some texts will show up. Those are tag wiki (I dont remember if it is called something else for I am going to use short description  of tag). So we are showing short description of tag now but no behaviour like SO. When a tag doesn't have short description than nothing will show when u will hover that tag.

**Comment by cellio** [comment]
Thanks!  I think if we can show something like "(no description yet)" for the case where there's no short description, so people always get *some* tooltip, that would be sufficient for now.

**Comment by b-Istiak-s** [comment]
I think "no short description yet" might be better than "no description yet". Cause there's two kind of description, short wiki and detailed wiki.
