### ISSUE TITLE
Allow OP to close own question

### ISSUE THREAD

**Issue by cellio** [codidact/qpixel#397]
https://meta.codidact.com/posts/280220

*If it is easy*, let's allow the OP to close a question regardless of abilities, same as you can edit or delete your own post without regard to abilities.  If someone suggests a duplicate and the OP agrees (the case described here) let's make that self-serve, but also, if the OP just realizes that a question is too broad or something but wants to work on it rather than deleting it, let's allow that.

If this is not easy, then let's hold off because we're eventually going to rework both closing and duplicate-marking anyway, so no sense investing heavily now.  I'm filing this because I think it's probably an "|| self" in the "can this person vote to close?" check.  Asking @luap42 for an opinion (not urgent).

**Comment by ArtOfCode-** [comment]
Should be relatively easy: change the view to show the close button to post authors, and change the controller to allow authors to close their own stuff.
