### ISSUE TITLE
Linking an SE account for a site that doesn't have an SE pairing produces a cryptic error

### ISSUE THREAD

**Issue by cellio** [codidact/qpixel#40]
This issue was reported here: https://meta.codidact.com/questions/74780

Codidact Meta does not have a matching SE site, but it's still possible to try to link an account.  If you do, you get the error "Couldn't parse client_id".

If we offer the "link SE account" option on all sites, it would be better to catch this and report back something like "This site does not have a matching SE site so you can't link an account".

Even better would be to only offer the "link SE account" interface on sites that have associated SE sites, but I don't know how hard that is.  (n.b.: I'm aware of a possible "native" Codidact community, one not coming from SE, so this would apply to them if they move forward.)

**Comment by ArtOfCode-** [comment]
Fixed by 5cae6a8
