### ISSUE TITLE
Make search box more obvious

### ISSUE THREAD

**Issue by cellio** [codidact/qpixel#403]
https://meta.codidact.com/posts/280298

Search changed fairly recently from being a link to another page to being a pop-out search box.  That's a great improvement.  This post requests that we make it more obvious that it's an in-page search, which, now that it's pointed out, I agree with -- it's not a link any more but it still *looks* like one.

Could we style it in a way that conveys "type in me here" more clearly?

**Comment by ArtOfCode-** [comment]
What would you suggest?

**Comment by cellio** [comment]
I was thinking of something like this: 

![mockup](https://user-images.githubusercontent.com/5557942/103686690-37b39180-4f5d-11eb-888d-d24b3f55952f.png)

"Search hint text" could just be "search", or it could also provide hints for common searches like "terms "exact match" [tag]" or whatever hints we want to provide.  (I don't think [tag] works yet, now that I think about it.)  The search icon (magnifying glass) would appear on the right when you click into the box.

By having a bounding box we draw the eye to it in a way that says "type in me".  Everything about the pop-out search we have now would be the same except that it would happen in place instead of popping out.

**Comment by ArtOfCode-** [comment]
The reason it's a pop-out is so it can be responsive - at medium screen widths, the top bar hasn't yet condensed to mobile view, but there wouldn't be space for a usable text input there. Are there text or icon changes we could make that would use a similar amount of space as it does now, but still convey "not a link, in-page"?

**Comment by cellio** [comment]
Oh, responsive!  Ok, that makes sense.  Would putting a thin bounding box around the word "search" convey it, I wonder?  Should we replace the word "search" with a magnifying glass, which on some other sites means "click here and type"?

There might be a broader design question here (@mattjbrent ): currently the things in the top bar are a mix of pop-outs and links, and there's no clear indicator for which is which.  Search is styled the same way as Users, to its immediate left, but Users is a link to another page.  Over on the other side, the inbox is a pop-out but mobile sign-in is a link.  Those are the *behaviors* we want, but how do we convey the non-obvious cases?  People expect an inbox to be a pop-out (every site out there that has inboxes does that), but the expectations aren't as clear for the word "search" by itself.

**Comment by luap42** [comment]
I don't think adding an icon only to search is going to look good.

But we could add an icon to *every* icon in the header. They are all important enough to get the extra visual trigger.

Something like this:

![screenshot of a header with all text menu points having icons](https://user-images.githubusercontent.com/21335202/103699036-9c450f80-4fa2-11eb-85f4-b8801d904639.png)

(FWIW the icons are all fas fa-fw and then fa-users, fa-search, fa-wrench and fa-question-circle)

I would refrain from using a down caret at all header popups, because that's conflicting with the communities dropdown. I don't think there is really a possible way to identify "is popup" and "isn't popup" without harming the design. We could mark those with a drop down differently on hover (for example a dark bar at the bottom of the menu point),  to indicate "that something is hiding there", but that's not intuitive either.

**Comment by ArtOfCode-** [comment]
Those icons work for me. I don't think there's any real intuitive way to convey link vs popout, but my question is how much it really matters. If you want to search, you're going to click search either way, and after you've done it once you know what to expect.

**Comment by cellio** [comment]
This works for me.  And Art has a good point that maybe the people who are surprised now are surprised because they were here when it was a link.  Let's add the icons (and on small devices, this means we can condense down to icons when words don't fit) and leave the rest as-is.

**Comment by manassehkatz** [comment]
> 
> 
> I know the question isn't directed to me, but I'd imagine something colourful and blinking, with huge arrows pointing to it and a paperclip explaining how to use it and attempting to draw your attention to it.

Don't, forget, a, generous, helping, of, commas,! :-)

**Comment by manassehkatz** [comment]
> Those icons work for me. I don't think there's any real intuitive way to convey link vs popout, but my question is how much it really matters. If you want to search, you're going to click search either way, and after you've done it once you know what to expect.

There **is** a way to do that. Underline all links. That is very clear. But also very much not done these days.

**Comment by manassehkatz** [comment]
I definitely like @luap42 Font-Awesome icon solution. I am very much against "icons all by themselves" because that can be confusing. But words + icons works very well, without taking much more space than words by themselves.

**Comment by cellio** [comment]
@manassehkatz I'm not a fan of icons only when there are alternatives; the web is full of cryptic symbols.  However, when the alternative is nothing at all, because the word won't fit, I'd rather have the icon than not.  On my phone, the top bar contains the logo, inbox, my gravatar and rep, the switcher, and the hamburger menu.  (The next thing that drops out if the viewport gets smaller, last I checked, is rep, which IMO is the right decision.)  If the viewport were a little bigger it could show a search icon even if it couldn't show the word "search".
