### ISSUE TITLE
Add a "save draft" button when creating/editing posts, to supplement or replace autosave

### ISSUE THREAD

**Issue by cellio** [codidact/qpixel#409]
We now have a preference to disable autosave, which has been requested on rendering-heavy communities.  This doesn't mean that people never want to save drafts; they just don't want us to interrupt them with it.  Could we add a "save draft" button to the editor?  Clicking it should trigger the same save action as autosave does.  Even people who use autosave might want to save explicitly right after finishing a gnarly bit of Mathjax, so the button should be available for everyone.

To prevent confusion (people saving when they meant to post), the button should be separate and/or visually distinctive somehow.  I recommend putting the button flush-right under the post and changing the wording of "save post in $category" to "post in $category" (or even just "post").

**Comment by cellio** [comment]
I see there's been a deploy since this was closed (and the auto-save pref moved from global to per-community), but I'm not seeing this.  I turned off auto-save on one site (Math), then edited one of my answers, and I don't see a "save draft" button.

**Comment by ArtOfCode-** [comment]
@cellio I'm seeing the button on prod, and there's nothing that would restrict it by user. End of the toolbar:

![Screenshot from 2021-01-13 08-40-52](https://user-images.githubusercontent.com/10406565/104427425-20872c00-557b-11eb-9202-288a517f977d.png)

**Comment by cellio** [comment]
Oh, I was looking in the wrong place!  I didn't think to look at the toolbar, which you're right is the obvious place for it.  I was looking for a new button below the editor, alongside post and cancel.
