### ISSUE TITLE
Make category descriptions collapsible (especially on phones)

### ISSUE THREAD

**Issue by cellio** [codidact/qpixel#415]
Raised as part of https://meta.codidact.com/posts/280405#answer-280405

The question list for a category includes a category description.  A typical length is Meta Q&A: "General Q&A about the Codidact instance hosted at codidact.com or the software that runs it."  On my phone, even that runs to three lines, and some are longer.

Can we make this collapsible, and remember that state for a user and device?  I'm saying "collapsible" not "dismissible" because I want people to still see *something* that lets them expand it again.  Maybe we can draw a faint bounding box around it, anchored at the base of the category stripe, and put an expander/collapser control on one of the top corners?  (Visual design isn't my strong suit; maybe there's a better way.)

Also consider shrinking the font size; it's larger than question titles right now, and maybe that's bigger than it needs to be?

**Comment by ArtOfCode-** [comment]
Did the work to make the description collapsible, but in practice it wasn't possible to implement smoothly enough. It's doable, but it has to be client-side, which means that state isn't remembered until document-ready, so the page jumps after loading when the JS kicks in and hides it, and there's no real way of avoiding that jump.

As a compromise, I've just made the text smaller for now. That on its own has a fairly big impact on both the visual bulk of the description block, and how much space it actually takes up, so we'll go with this for now and see if it needs changing further later on.

**Comment by cellio** [comment]
Smaller text should help, thanks.  What is it about the dismissible notice on Meta that's different?  That seems to be sticky, and I don't see any display glitches as it loads.

**Comment by ArtOfCode-** [comment]
That's cookie-based, which is accessible to the server so we can just not load it. I suppose it'd be _possible_ to do the same for categories, but not as easy given the number of them - lots of categories, whereas the notices are max one per site.

**Comment by cellio** [comment]
Ah, ok -- didn't realize that was a cookie.  I don't know a lot about conventions for using cookies, but it sounds like this would be messy.

**Comment by cellio** [comment]
I just saw this comment on the linked post, the second part of which caught my eye:

> A simple solution would be to put a close or collapse button on the text. If the categories page hadn't been removed, I'd say it's enough to list the descriptions there (as an aside, I actually miss a way to get a quick overview without clicking on all categories; if anything, I would have increased the utility of the page by adding information to it). — celtschk‭ 

Is making category descriptions available in tooltips on the category names easy?  This would support the "exploration" case mentioned here.  (I can write a new issue to avoid scope creep here -- just wanted to ask first, 'cause if it's not easy we probably aren't going to do it.)

**Comment by ArtOfCode-** [comment]
Tooltips don't support HTML formatting, so while _most_ category descriptions would work fine, some have Markdown in them (like links) that would just display as raw HTML... not really what you want
