### ISSUE TITLE
Group posting date, edit date, and license together on left

### ISSUE THREAD

**Issue by cellio** [codidact/qpixel#419]
https://meta.codidact.com/posts/280482

Current layout:

![screenshot](https://user-images.githubusercontent.com/5557942/104664382-12c9c780-569d-11eb-8d85-b41248cfb910.png)

I've been thinking for a little while that the edit indicator being off by itself on the left looks a little odd.  Posting date and edit date are both relevant when evaluating the currency of something, and I'd like them to be closer together.  Could we do something like this instead?

![mockup: on left, post time, license, edit time](https://user-images.githubusercontent.com/5557942/104664424-312fc300-569d-11eb-941e-792db2102a5b.png)

This has the benefit of separating the metadata about the *post* from the info about the *user*.  Currently the post time and license are included in the gray box, visually connecting them to the user, but that info really belongs to the post.

**Comment by cellio** [comment]
Is this (a) easy and (b) a good first issue?

**Comment by ArtOfCode-** [comment]
Easy with some familiarity with the application, yes, but not for a first issue - there's existing CSS that we should be using here, which someone unfamiliar won't know of.
