### ISSUE TITLE
Show asker name in question list along with last activity

### ISSUE THREAD

**Issue by cellio** [codidact/qpixel#430]
https://meta.codidact.com/posts/280602

Users have asked for a way to see who asked a question and when in the question list, even if it was later modified by somebody else.  Especially since we don't yet show *what* the latest activity is, just that there was some, some find our current approach confusing.

Can we find a way to add something like "asked by Ploni 3 days ago" to the summary information on the question list, along with "last activity 13 hours ago by Someone"?  A simplistic approach would be to add to the existing text line (and if it wraps it wraps): 

> 2 answers - asked by Ploni 3 days ago - last activity 13 hours ago by Someone

We might need to drop some info out on smaller viewports.  I would first drop when it was asked, then drop who did the last activity, so a reduced version would be:

> 2 answers - asked by Ploni - last activity 13 hours ago

Which occupies about the same space as what we have now.  But it'd be better to not drop the user from "last activity" if we can avoid it, since (currently) this doesn't tell us or link to the actual activity.

We can also reclaim a little space by never including "about" -- just say "13 hours ago", not "about 13 hours ago".  "13 hours" is an approximation anyway; maybe it was 12:49 or maybe it was 13:23... it's already "about", in other words.  When we get to days we drop the "about", so we can drop it for hours and minutes too.

**Comment by cellio** [comment]
I marked this low priority to start, but the Meta question is also +9/-0, so there's non-trivial support for this request from the community.

**Comment by kevinmmansour** [comment]
Just feedback, If that is fine, so I will create a pull request:

![image](https://user-images.githubusercontent.com/71846550/127607502-e1710fc8-ee16-47fe-b5b7-4770f0f18696.png)

**Comment by cellio** [comment]
Could you show what it looks like on mobile with longer user names?  I don't mean ridiculous ones, but names like yours or mine are pretty typical in length and we don't want that to throw off the spacing too much.  Thanks.

**Comment by kevinmmansour** [comment]
OK. my username is 19 characters. here is an exampe of how it will look on mobile:

![Preview](https://user-images.githubusercontent.com/71846550/127735379-c7d201f3-1d11-41f7-a3e1-aeed1cab6350.png)

**Comment by Istiakshovon** [comment]
> OK. my username is 19 characters. here is an example of how it will look on mobile:
> 
> ![Preview](https://user-images.githubusercontent.com/71846550/127735379-c7d201f3-1d11-41f7-a3e1-aeed1cab6350.png)

Would it be better if you decrease title width for mobile?
