### ISSUE TITLE
Clarify in close dialogue that duplicates need to be local

### ISSUE THREAD

**Issue by cellio** [codidact/qpixel#432]
https://software.codidact.com/posts/280607

Somebody tried to close a question on site A as a duplicate of one on site B.  Cross-site duplicates aren't supported, but the user was able to enter the URL and then got this response:

> {"status":"failed","message":"Invalid input for other post."}

I guess that was in the console; when I try I get "400: error".

I tried some other test cases: leaving the duplicate field blank or entering an off-network URL (I used XKCD) also produces the same error.

Can we change the hint text for the duplicate link to clarify it's a post on *this* community?

(The linked question also asks about validation, which I'll spin off into a different issue because it's probably harder -- but UI text should be easy.)

**Comment by ArtOfCode-** [comment]
Added some text in there to indicate it has to be on this community.
