### ISSUE TITLE
Validate close form client-side

### ISSUE THREAD

**Issue by cellio** [codidact/qpixel#433]
Related: https://github.com/codidact/qpixel/issues/432

https://software.codidact.com/posts/280607

If you try to close a question and don't choose any of the options, you get a pink "404" pop-up (no further information.)  If you try to close a question as a duplicate but the duplicate link is missing or not on the local community, you get a pink "400: failed" pop-up.

These both seem like things we could catch client-side.  We could then leave the person in the close dialogue but add some text about *what* was wrong -- choose a reason, supply URL on this community, etc.  Or even keep the pink pop-up, but with better information.  Note that if you try to *flag* a post and don't choose a reason, you get a pink pop-up that says "must choose a reason", so we're a little inconsistent here.

Ideally a malformed request wouldn't even *get* to the server.  Of course there could still be server-caught errors; the client can't catch everything.  But it could catch some, and apparently does for flags already.

**Comment by BoxedFruits** [comment]
I have two solutions that I think we can do. 
1) Make the `Close this post` button default in the disabled state and re-enable when a radio is checked.
- Would mean adding a click listener for the each of the radios.
- Might be confusing when closing a duplicate and a user only fills out the URL and doesn't click the radio button. I guess we can also have that input appear when you click the radio for `duplicate`

2)See if there is a radio is checked before trying to close the post (not doing this currently and is why we get a 404 error) and render an error message
- Don't know if it is possible to render a RoR error with jquery.
- Upside is that there won't be as many changes/adding a bunch of click listeners

Let me know which one would be better.

**Comment by cellio** [comment]
What do we do for the flag case (where you get a more meaningful error message if you don't choose a reason)?  Is it 2 by any chance?  I'm not qualified to choose between these options, but if one of them is what we already do in another case, I'd lean toward consistency.  (But I can also be overruled by Ruby-competent team members, since I am not.)
