### ISSUE TITLE
Can we prevent collisions between Markdown and Mathjax?

### ISSUE THREAD

**Issue by cellio** [codidact/qpixel#435]
See https://github.com/codidact/docs/issues/26 and the meta posts linked there.  Some Mathjax apparently has to be escaped because it's within Markdown, which confuses people periodically.  We can document it (the linked issue is in the docs repo), but if we can make it behave the way people are expecting, that'd be better.

**Comment by MoshiKoi** [comment]
Another edge case has occurred: https://math.codidact.com/posts/285594

**Comment by MoshiKoi** [comment]
https://math.codidact.com/posts/285613
