### ISSUE TITLE
Allow to filter tags by "not having usage guide"

### ISSUE THREAD

**Issue by Alexei000** [codidact/qpixel#438]
**Is your feature request related to a problem? Please describe.**
As tag pool for a category increases, it is getting harder to find the tags without usage guidance, in order to fill it. It would be useful to quickly find such tags.

**Describe the solution you'd like**
Add a checkbox filter named "no usage guide" or similar in the Tags used in <category name> page.

**Describe alternatives you've considered**
No alternatives considered.

**Additional context**
Example view to apply this filter: https://software.codidact.com/categories/38/tags

**Comment by cellio** [comment]
We might want to do this via search syntax.  We need to add negation syntax anyway, and that plus "has description" (for things that have descriptions, i.e. tags) would address this request too.
