### ISSUE TITLE
Editing comment and exceeding character limit breaks post functionality

### ISSUE THREAD

**Issue by sarahmccuan** [codidact/qpixel#44]
Steps to reproduce: 

1. Post a comment to a post or answer. 
2. Edit the comment to be longer than 500 characters.
3. Click the Post button. 

Expected behavior: alert should notify user that comment is over character limit.
Actual behavior: nothing happens. Comment remains unposted, no notification to user.

**Comment by ArtOfCode-** [comment]
Fixed by 1c10592
