### ISSUE TITLE
Unable to move question between categories

### ISSUE THREAD

**Issue by MoshiKoi** [codidact/qpixel#443]
The question https://languages.codidact.com/posts/280869 is unable to be moved. Neither I (mod), Hanika (mod), or Cellio (admin) were able to move it, so I believe it is not a permissions issue.

I tested on Edgium and Firefox; no new errors appear in either console upon hitting the 'Move' button.

In a comment, Hanika mentions

> Silently fails for me, too. BTW the post appears "partly moved". Go to meta, to tags, tag named translation-golf (tag 4806 in category 37 which is Meta), and inspect it. You'll see 1 post (this one), with one post type and one tag on it, the tag belonging to category 36, which is Q&A. I assume that that tag 4806 in category 37 may have been created by your first move action. OR maybe the 2 tags of the same name existed independently, which alone would explain why you can't move.

**Comment by ArtOfCode-** [comment]
So this is actually failing for a valid reason; you're trying to move a post into a category with required tags without the post having any of those tags. That fix just above just makes sure we surface these errors correctly.

**Comment by cellio** [comment]
Interesting case.  If we fail with an error, we have a bootstrapping problem -- those tags don't exist in Q&A, so requiring that they be there before moving is kind of strange too.  (And we don't want to *create* them in the source category just for the sake of the destination category.)

What should we do when a migration moves a post between tag sets?  I think any of these would be reasonable:

- drop all tags, move the post, and remind the moderator to tag it in an edit (can violate required tags)
- drop tags, move the post, and assume somebody will apply tags (can violate required tags)
- drop tags, move the post, and apply a default required tag (would need a way to specify which is the default)

I'm ok with moving the post and dropping tags.  The first edit in the new category will force tag compliance.  I think that'd be better than spurious tags on either side.
