### ISSUE TITLE
Search by post type

### ISSUE THREAD

**Issue by cellio** [codidact/qpixel#444]
Followup to https://github.com/codidact/qpixel/issues/429.

Search returns all matching posts, but if you were trying to search questions by tags, you probably don't want all the answers showing up too.  (That's exactly the use case in the meta post in the linked issue.)  Can we add some search syntax for post types?

We can't hardcode types, because new post types can be created.  And sometimes we're going to use post types to implement something like "articles, but with more rep" (e.g. EE's papers).  I don't know that we want to expose all that complexity to users.  From *their* perspective, we have things that look like questions, things that look like answers, and things that look like articles.  I suggest that we build our search syntax around that, and if we want to add additional qualifiers later (like "is:broadly-editable" or "has:voting"), we can tackle that then.  We could then have three options with the following underlying implementations:

- type:question: any top-level post that accepts answers
- type:answer: any non-top-level post
- type:article: any top-level post that does not accept answers

I'm open to other approaches, of course -- just want to record the issue before I lose track of it in that other one.

**Comment by ArtOfCode-** [comment]
Closed by #554
