### ISSUE TITLE
Could not delete question even though it had no non-deleted answers.

### ISSUE THREAD

**Issue by cellio** [codidact/qpixel#446]
https://meta.codidact.com/posts/280946 (now deleted) was +0/-0 with a +0/-0 deleted answer.  Attempting to delete the question produced the error: "This post cannot be deleted because it has responses."  It looks like the code that checks for answers doesn't check for *non-deleted* answers.

ArtOfCode restored the deleted answer, downvoted it, deleted it again, and then successfully deleted the question.  (Along the way, somebody downvoted the question too.)

**Comment by ArtOfCode-** [comment]
Fixed with #447
