### ISSUE TITLE
Unable to nominate a post for network promotion

### ISSUE THREAD

**Issue by cellio** [codidact/qpixel#449]
https://meta.codidact.com/posts/280846

A moderator tried to nominate https://languages.codidact.com/posts/279224 but it did nothing.  The post includes a screenshot of the web console.  I tried to reproduce and it didn't work for me; I see "javascript.void(0) at the bottom of the browser window when hovering over the button, and nothing changes when I click it.

The post is an article, but the reporter has been able to nominate articles before.  The post is in a category other than Q&A, but other moderators have been able to promote challenges before.  I don't know what it is about this particular post, and whether it's a weird data error with one post or a combination of circumstances that could affect other nomination attempts too.

**Comment by ArtOfCode-** [comment]
_May_ be fixed by 94e168a62c12d68f9921f1a57f472bcf87f4bf13; needs verification once deployed

**Comment by ArtOfCode-** [comment]
Verified fixed.
