### ISSUE TITLE
Options in "confirm cancellation" modal are confusing

### ISSUE THREAD

**Issue by cellio** [codidact/qpixel#451]
https://meta.codidact.com/posts/280861

Problem statement and request are clear, so I'll just quote:

> After hitting the "Cancel" button when writing or editing a post, a prompt shows up that says
>
>> Any unsaved changes will be lost. Are you sure?  
>>[Okay] [Cancel]
>
> Hitting [Okay] will kick you out of the editor (as expected).
>
> However, hitting [Cancel] will also kick you out of the editor, and will erase your save data.
>
> While the second behavior is actually pretty useful[1], it isn't exactly intuitive – I would expect the Cancel on the prompt to mean "I didn't intend to click the Cancel button, let me continue editing."
>
> If possible, I suggest using a three-button prompt instead, such as
> 
>>Would you like to keep your saved draft?
> [Keep draft] [Discard draft] [Continue editing]
>
> This would make the choices much clearer from a user standpoint.

**Comment by luap42** [comment]
Fixing the underlying bug, but the three-button prompt is unfeasible without a lot of effort: the "OK", "Cancel"-question button is implemented into browsers by default and can be simply called via the `confirm()` function, if we wanted to change that we'd have to implement our own confirm modal with behavior, style, ....

Now the behavior will be more intuitive:

* Clicking "OK" will discard the draft and bring you to the page you were before (new toplevel-post -> category page, editing post -> back to the post, new answer -> reload)
* Clicking "Cancel" will do nothing.

Unfortunately, the name "Cancel" is a little bit confusing here. We might want to add "OK to abort, Cancel to do nothing" or something similiar to the dialog.
