### ISSUE TITLE
Ad templates don't work with articles

### ISSUE THREAD

**Issue by cellio** [codidact/qpixel#454]
https://meta.codidact.com/posts/280973

Ad templates, when used with articles, produce images that emit 500 errors instead of displaying.  This also happens for category ads if the category uses articles.  For example: https://languages.codidact.com/ca/category/40.png, https://judaism.codidact.com/ca/category/43.png.

**Comment by cellio** [comment]
I'm now getting "error" (no details) when I visit those links.

![Screen Shot 2021-03-20 at 10 28 32 PM](https://user-images.githubusercontent.com/5557942/111891769-b00de880-89cb-11eb-8066-084f64f31672.png)

**Comment by ArtOfCode-** [comment]
Kind of intended? Be better as a 404, but either way. That category has no posts that meet the criteria set for hot posts, so there's no posts to advertise.

**Comment by cellio** [comment]
Oh, there are additional criteria.  Ok thanks.
