### ISSUE TITLE
Provide visual indicator for categories I can see but that aren't public

### ISSUE THREAD

**Issue by cellio** [codidact/qpixel#455]
It's possible to restrict category visibility at several levels (mod-only, only registered users, some things in between).  To people who can see the category, it would be very helpful to have some visible reminder that not everyone can.  A reminder that what you're posting (or seeing) is restricted in some way informs how people use the category, and a reminder that not everyone can see this reassures moderators that the category isn't leaking.

For deleted content we have a visual indicator for those who can see, in the form of a colored background (and a notice, for posts).  Maybe we can take a cue from that and shade the background of the category tab somehow?  (Not that pink, which indicates "deleted", but maybe a graying effect?)  We should also add an icon or some text, for accessibility, rather than just relying on color.

I realize that admins can change the color scheme for a category, but (a) that doesn't clearly convey meaning (it's just a different color), (b) it's hard-coded, and (c) that doesn't allow for further signal like an icon or tooltip.  It should, instead, be derived from the category state.

**Comment by luap42** [comment]
Resolved.

![Lock icon now shown before category name](https://user-images.githubusercontent.com/21335202/111317079-1c06ee80-8664-11eb-9736-3c97e76e0a20.png)

I think adding a sign in the category "tabs" would be too noisy. When you hover the lock it will say:

> The access to this category is restricted, but you are exempt.
