### ISSUE TITLE
Can't create new tags

### ISSUE THREAD

**Issue by cellio** [codidact/qpixel#46]
I tried to tag a question on Codidact Meta as status-completed.  The tag doesn't exist, but the tags section allowed me to add it as usual.  When I submitted the edit I got this error:

![Screen Shot 2020-04-28 at 11 55 49 AM](https://user-images.githubusercontent.com/5557942/80509498-824d2a80-8947-11ea-9bb0-4bb657ca5c12.png)

Ok, I get that my new tag isn't in a tag set yet (and doesn't even exist), but until we have tag sets, can we allow tag-creation in the usual way?  Or if that's hard, I guess we need to raise the priority of the new "create tag" workflow.

Until we have the new workflow (and maybe even after that), it seems reasonable to assume that any new tag being created is to be added to the current category's tag set.  A category has only one tag set, so we don't have to worry about resolving ambiguities there.

We could also mitigate my specific problem by creating the status tags on Meta, but with the new Outdoors site we might have people wanting to create new tags there, too.

**Comment by luap42** [comment]
That seems to be a problem because of the Meta -> Q&A migration and probably needs to be fixed by @ArtOfCode- going to the DB and changing the tag set for those in "Meta" to "Q&A".

**Comment by ArtOfCode-** [comment]
> That seems to be a problem because of the Meta -> Q&A migration and probably needs to be fixed by @ArtOfCode- going to the DB and changing the tag set for those in "Meta" to "Q&A".

Done. Try again, @cellio?

**Comment by cellio** [comment]
Works now, thanks!

When I went back to the page the status-completed tag was there already; maybe I succeeded in creating it before but just couldn't add it.  To test, I added status-this-is-a-test to one of your posts and then removed it.  Feel free to blow away the tag; I needed to create something in order to test the fix.

**Comment by ArtOfCode-** [comment]
I'll count that as a win... didn't really expect it to be that simple.
