### ISSUE TITLE
Soft deletion for users

### ISSUE THREAD

**Issue by cellio** [codidact/qpixel#471]
User deletion is rare, but when it does happen, all the user's activity gets assigned to the System user.  For moderation purposes, it can be very useful to be able to examine a user's posts etc, particularly when users can self-delete.  (We don't have self-deletion yet, but we should address this before we add that.)  Somewhere else, we sometimes saw users try to hide abuse behind strings of deleted accounts, and eventually we're going to need tooling for that -- which means being able to keep the stuff from deleted-user-A from mixing with the stuff from deleted-user-b etc.

Instead of outright deleting users, let's do the following:

- Normalize the user name where it appears on posts and unlink.  (User#### is fine.)  Remove or generify rest of usercard (no stats or personal avatars on deleted accounts).
- Remove the entry from the users list.
- Treat the profile page the way we treat deleted posts, *except* that access is mod-only (not curate).  Note: styling should be slightly different, so mods can see which posts on that profile are deleted vs not (which wouldn't work if we made the whole page background the same pink).
- Add a link to the deleted account to the moderation audit log or any other convenient mod-only history.
- Helpful but not strictly required: for moderators, the link still works from posts/comments.  (Not essential *if* the normalized name provides enough info to reconstruct the URL by hand (or by userscript), but nice to have.)

PII?  I think it's useful to be able to connect re-created accounts to their deleted ancestors, but we could probably hash the email address or something instead of keeping the real one if we're concerned about keeping this data?

**Comment by ArtOfCode-** [comment]
Done a while ago
