### ISSUE TITLE
Flag text length is too limited

### ISSUE THREAD

**Issue by ArtOfCode-** [codidact/qpixel#473]
https://meta.codidact.com/posts/281311

The 500 reported here when trying to flag a post is an `ActiveRecord::ValueTooLong` error, i.e. the flag reason is too long for the database field.

This type needs changing to a text type instead of a short string.

**Comment by cellio** [comment]
Also seems like a front-end issue: if we limit the length of a field, shouldn't we check the input client-side and complain if it's too long?
