### ISSUE TITLE
Hebrew calendar widget on Judaism is wrong for a few hours a day

### ISSUE THREAD

**Issue by cellio** [codidact/qpixel#477]
This began happening after the fix for Sunday showing as "undefined" was deployed.

At a bit after 8PM local time (last night), this is what I saw: date and day of the week had rolled over to the correct ones for Monday night/Tuesday, but the day-of-week part hadn't:

![Screen Shot 2021-04-19 at 8 06 01 PM](https://user-images.githubusercontent.com/5557942/115455562-1e72e000-a1f0-11eb-982e-cd5228ba7268.png)

(Earlier in the day it said 7 Iyyar and also Sunday night/Monday, which was correct.)

At 9:30PM, the day rolled over -- *and so did the date again* (wrong):

![Screen Shot 2021-04-19 at 9 39 25 PM](https://user-images.githubusercontent.com/5557942/115455646-38acbe00-a1f0-11eb-9db9-d823170089b4.png)

I wasn't online at midnight.  The following morning, the day and date were both correct:

![Screen Shot 2021-04-20 at 9 39 22 AM](https://user-images.githubusercontent.com/5557942/115455720-4febab80-a1f0-11eb-814e-9b7602381126.png)

The sequence seems to be: increment date at 8PM, increment day *and date* at 9PM, reset date (decrement date?) at midnight.

Originally everything turned over at the same time, once, and I think that time was 9PM (local time).  I remember a discussion of 9PM vs 8PM but don't recall the details.  It doesn't really matter which we choose because the day indicator disambiguates.  But they should be aligned. :-)

I *suspect* that there is some phantom code that's doing stuff at 8PM and causing problems.  The original version of the widget didn't show the day, just the date, and I wonder if that code came back in the day fix?  If the 8PM change hadn't happened then the 9PM change would have been correct (increment both) -- though what's happening overnight is still a mystery.

**Comment by cellio** [comment]
This is happening because the Date class is *mostly* local time but getISOString() isn't and we rely on that.  After a lot of trial and error using a userscript, I believe I have a fix -- but I can only test it as a userscript, not in a deployed environment, right now.

**Comment by ArtOfCode-** [comment]
@cellio has your PR fixed this?

**Comment by cellio** [comment]
The true confirmation will come when we deploy, but that's the expectation.
