### ISSUE TITLE
Add revision numbers to history entries

### ISSUE THREAD

**Issue by cellio** [codidact/qpixel#479]
This suggestion is related to my answer here: https://meta.codidact.com/posts/281466#answer-281466.

It's sometimes useful to be able to refer to a specific revision of a post -- this answer applies to revision 5 (before the asker made a large change), or there's a meta question asking about an edit, or a flagger wants to point out something problematic.  Could we number the history entries when displaying them?

**Comment by cellio** [comment]
Priority lowered because there *are* timestamps; they're just a little less friendly.

**Comment by razetime** [comment]
Add a pull request for the fix in #484.
