### ISSUE TITLE
Terms of service on user-generated content mentions Writing-specific contact e-mail address

### ISSUE THREAD

**Issue by 1ec2466** [codidact/qpixel#48]
The terms of service at /policy/tos on any Codidact site, under User-Generated Content, suggests that permission to use design elements can be obtained by emailing `writing@codidact.com`.

I suggest that this is changed to a general address, such as `legal@codidact.com`.

**Comment by ArtOfCode-** [comment]
Fixed, reset to our generic contact `info@codidact.com`. Thanks!
