### ISSUE TITLE
2FA Codes suggested with Autocomplete

### ISSUE THREAD

**Issue by Dani21** [codidact/qpixel#482]
**Describe the bug**
When submitting a two-factor authentication codes, previously submitted codes may show up in a desktop browser because there is no autocomplete attribute on the element or form. These are obviously useless because these codes are for one-time use.

**To Reproduce**
Steps to reproduce the behavior (on Firefox):
1. Go to the following page and ensure 2FA is turned on: https://meta.codidact.com/users/two-factor
2. Log out and log back in, submitting your username and password.
3. On the 2FA form afterwards, it'll ask for a code. Double click the field to reveal the autocomplete suggestions.

**Expected behavior**
Upon double clicking the field, nothing should be revealed and it should just let you input a new code.

**Screenshots**
![Visible autocomplete code](https://user-images.githubusercontent.com/1804643/116138944-13f69180-a69b-11eb-8f86-ef6c11817381.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox
 - Version: 88

**Additional context**
The following two pages ask for a two factor authentication code and should be modified:
- https://meta.codidact.com/users/two-factor/enable/code -- [app/views/two_factor/enable_code.html.erb](https://github.com/codidact/qpixel/blob/develop/app/views/two_factor/enable_code.html.erb)
- https://meta.codidact.com/users/2fa/login -- [app/views/custom_sessions/verify_2fa.html.erb](https://github.com/codidact/qpixel/blob/develop/app/views/custom_sessions/verify_2fa.html.erb) 

My recommendation would be to set an `autocomplete="off"` attribute on the `<form>` element and `autocomplete="one-time-code"` on the `<input>` element for a balance of compatibility and empowering browsers to insert a 2FA code. The following documentation provides full `autocomplete` attribute guidance: https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete

**Comment by ArtOfCode-** [comment]
Thanks!
