### ISSUE TITLE
Closing as a dupe requires a link, but flagging doesn't

### ISSUE THREAD

**Issue by cellio** [codidact/qpixel#488]
https://meta.codidact.com/posts/281617

If you vote to close a question as a duplicate, you must supply a link:

![screen shot of close menu](https://user-images.githubusercontent.com/5557942/117496668-60688980-af45-11eb-86ad-68ca4c010d29.png)

If you *flag* as a duplicate, however, there's no such requirement:

![screen shot of flag menu](https://user-images.githubusercontent.com/5557942/117496731-75451d00-af45-11eb-95cc-12c726c90545.png)

Is it feasible to have a duplicate flag inherit this requirement from the duplicate close reason?

If that's too hard, can we at least add some text to the description directing the flagger to supply the link in the textbox?  All flag types can use that textbox, not just "other".

**Comment by Istiakshovon** [comment]
This should be closed
