### ISSUE TITLE
Comment posting hits a Cloudflare error if it contains restricted HTML

### ISSUE THREAD

**Issue by cellio** [codidact/qpixel#489]
https://meta.codidact.com/posts/281208

A user tried to post a comment containing `<script>`.  We don't allow that as HTML, so the post failed.  The user got a Cloudflare error, which was confusing.  Is there anything we can do to either detect bad input and give our own error message, or transform bad input into acceptable input (escaping the angle brackets, for example)?

There is a workaround and this is an infrequent problem, but I'm not prepared to say it'll never come up again on our software communities, so I'm filing this.

**Comment by ArtOfCode-** [comment]
This _should_ already be fixed - I spent a while tweaking the Cloudflare firewall rules and this shouldn't happen any more.
