### ISSUE TITLE
Page footer links point to writing.codidact.com also on other sites

### ISSUE THREAD

**Issue by 1ec2466** [codidact/qpixel#49]
The links to "Terms of Service" and "Code of Conduct", in the page footer on outdoors.codidact.com, point to writing.codidact.com. They should probably be site-relative; for example, `/policy/tos` instead of `https://writing.codidact.com/policy/tos`.

**Comment by ArtOfCode-** [comment]
This one is [status-bydesign] - to avoid having to manually re-create ToS and CoC documents on every new site that we create (and then keeping them all up to date), I've opted to use Writing as the master source for both of them. Good eye, though!

**Comment by cellio** [comment]
Let's see if we can move those to a site-agnostic location on codidact.com.
