### ISSUE TITLE
Deleting a question changed attribution of answer deletions

### ISSUE THREAD

**Issue by cellio** [codidact/qpixel#503]
https://meta.codidact.com/posts/281907

A question had deleted answers.  (In case it matters, they were deleted by System.)  A moderator then deleted the question, and the "deleted by" notices on the answers updated as if it were a current deletion -- deleted by that moderator on the new date.  That's wrong.  (This is the question, for those who can see it: https://scientific-speculation.codidact.com/posts/231643 .)

We've had problems with deletions and answers before (https://github.com/codidact/qpixel/issues/342).  That issue's closed, but I'm guessing we didn't actually get the logic quite right.  Here's what I think we should be doing:

- Deleting a question changes the deletion record for the question *only*.
- Answers that were explicitly deleted have their own deletion records (question deletion is irrelevant).
- Answers that were not explicitly deleted, but the question was, are *treated as* deleted for things like links in user profiles and search results; they're not themselves deleted but they "inherit" the deletion state of the question.
- Therefore, if a deleted question is later undeleted, its answers are in the same state as they were before the question deletion: answers that were explicitly deleted are still deleted (with the original deletion notices), and answers that were not explicitly deleted are again visible.

**Comment by cellio** [comment]
This issue is high *severity* but medium *priority* -- it happens rarely, but when it does happen it's bad.  Rather than adding a batch of severity tags I just used priority here, but want to explain why.  Please feel free to adjust tagging however it makes sense.

**Comment by sau226** [comment]
I've put up a potential PR (linked above) to potentially fix the key holding here (that existing deleted answers' deletion status is overwritten by question deletion, to be fixed such that only undeleted answers have the new status applied) as a stop gap solution, pending full implementation of this request or other action.

**Comment by cellio** [comment]
@ArtOfCode- how much of this does the merged code fix?  Should I create another issue for the "inherit deletion state, don't edit the answer state" part of this?

**Comment by ArtOfCode-** [comment]
The merged PR fixes part of it, my close commit fixes the rest of it. We don't inherit state for answers, because that's complicated to do and doesn't actually gain us anything, but answers that were deleted with the question are restored with the question.

**Comment by cellio** [comment]
Sorry, missed that there was a second commit with that closure.  Thanks.
