### ISSUE TITLE
OpenSearch provider support

### ISSUE THREAD

**Issue by Victor239** [codidact/qpixel#509]
**Is your feature request related to a problem? Please describe.**
Many sites like YouTube natively support OpenSearch which enables users to add the site as a search provider for their browser. I use Firefox with lots of search provider plugins that allow me to search sites like StackOverflow, YouTube, GitHub etc with 1-click directly from my navigation bar, and would like to search Codidact with 1-click too. 

**Describe the solution you'd like**
When going to https://codidact.com or any webpage on the site, I should be able to add https://codidact.com as a search provider. 

**Describe alternatives you've considered**
Going to the Codidact.com directly and using the search bar, which I'm less likely to do since StackOverflow I can search in just 1-click. 

**Additional context**
N/A

**Comment by cellio** [comment]
Looks like this is the relevant interface doc: https://developer.mozilla.org/en-US/docs/Web/OpenSearch

**Comment by ArtOfCode-** [comment]
Seems easy, seems useful... why not. Done, pending next deploy.
