### ISSUE TITLE
Be consistent with "sign in" or "log in"

### ISSUE THREAD

**Issue by 1ec2466** [codidact/qpixel#51]
The button near the top right of the page (on desktop) says "sign in".

The page you get to when you click on it says "log in".

The button near the top right of the page (again, on desktop) says "sign up".

The page you get to when you click on it says "sign up".

The recently added notice on the sign up page says "sign in".

The "forgot your password" page has links "log in" and "sign up".

Once you're logged in, you can "sign out".

**Can either please be changed so that it is consistent?**

Compare here on Github, which uses "sign up" and "sign in" but does so consistently.

Personally I prefer "sign up" and "log in"/"log out", because even at a glance they actually *look* different, but either's fine with me.

**Comment by ArtOfCode-** [comment]
Fixed by 084f269
