### ISSUE TITLE
Flagging as a duplicate should require a link

### ISSUE THREAD

**Issue by cellio** [codidact/qpixel#510]
https://meta.codidact.com/posts/281617

If you vote to close a question as a duplicate, you must supply a URL to the target.  However, if you *flag* a question as a duplicate, you don't.  This has led to dupe flags that moderators don't know what to do with.  A user has to have the extra insight to use the "other" field to report the dupe.

Can dupe flags please prompt for a link, same as dupe closes?

**Comment by ArtOfCode-** [comment]
Fixed in the comments branch as part of that rework.
