### ISSUE TITLE
On profile, change "Votes" heading to "Votes cast" and "Flags" to "Flags raised"

### ISSUE THREAD

**Issue by cellio** [codidact/qpixel#511]
https://physics.codidact.com/posts/281633

The poster was confused and thought the "Votes" section in the user profile referred to votes *received* rather than votes *cast* (which is what it is).  There's room there to be a little more verbose; can we change the header there from "votes" to "votes cast"?  

Also: https://meta.codidact.com/posts/281642

Here a user was confused about "flags" and I guess didn't realize that you can't see flags raised against you so it has to be flags you've raised instead.  Again, we have room to be a little more clear: "flags" -> "flags raised".

Small changes to these two strings would increase clarity.

**Comment by ArtOfCode-** [comment]
Closed with #530.
