### ISSUE TITLE
404 on ability pages if not logged in

### ISSUE THREAD

**Issue by cellio** [codidact/qpixel#514]
https://meta.codidact.com/posts/281910

If you visit the help page for a specific ability (like https://meta.codidact.com/abilities/unrestricted) and are not logged in, you get a 404.  This is probably because of this part of the page (when logged in):

!["You have already earned this ability"](https://user-images.githubusercontent.com/5557942/121454406-b8dddd00-c970-11eb-9205-6d9e8e6f2078.png)

Could we instead omit that part if there's no current user and still show the rest of the page, which is general information about what the ability is and how to earn it?

**Comment by cellio** [comment]
(Guessing the content is assembled server-side, hence the ruby tag.  If that's wrong, please fix.)

**Comment by NateEag** [comment]
I think [this is the logic explicitly triggering the 404 if there's no logged-in user](https://github.com/codidact/qpixel/blob/8f36e90346ce1413cab8e6973620381a184c0153/app/controllers/abilities_controller.rb#L28).

I believe if that 404 clause were removed, and [this block were made an else-if that requires a logged-in user](https://github.com/codidact/qpixel/blob/8f36e90346ce1413cab8e6973620381a184c0153/app/views/abilities/show.html.erb#L112), then the abilities pages would likely work for people who aren't logged in.

Disclaimer: I'm a drive-by commenter who's never looked at this project before and has only used Ruby in `Vagrantfiles`. I could be way off-base. Just noticed the issue poking around the project, found a plausible answer in a minute or two, and thought I might as well add my two cents.

**Comment by sau226** [comment]
You would need to also rectify the abilities [index page](https://github.com/codidact/qpixel/blob/develop/app/views/abilities/index.html.erb) to account for the missing user ID if you made the changes described above

**Comment by cellio** [comment]
Is that the page behind the "abilities dashboard" button (https://meta.codidact.com/abilities)?  Since that's a help topic, we can't easily just omit the button there, so we need to make the page behave reasonably for the logged-out case.  There's not much there that's of additional value to a logged-out user (who came via the help page), so it would be ok with me if a logged-out user saw "log in to view your dashboard".

**Comment by Istiakshovon** [comment]
>If you visit the help page for a specific ability (like https://meta.codidact.com/abilities/unrestricted) and are not logged in, you get a 404.

Not only for specific page. It happens for abilities page either. https://meta.codidact.com/abilities/

**Comment by cellio** [comment]
Ah, good point.  We also need to exclude the "earned" column on that page when there is no current user.  So a logged-out user would just see the column of abilities (with links), and on visiting one of those links, would see the static text but not the "progress" info that's user-dependent.

**Comment by cellio** [comment]
People checking us out keep bumping into this (heard another complaint today).  Can we please figure out how to apply some "check for current user else exclude" logic?  Our abilities system is one of the things that differentiates us and people can't learn about it.
