### ISSUE TITLE
500 error on policy pages on Linux Systems and Power Users

### ISSUE THREAD

**Issue by pxeger** [codidact/qpixel#517]
**Describe the bug**

Visiting the `/policy/tos`, `/policy/code-of-conduct`, or `/policy/privacy-policy` on `linux.codicact.com` and `powerusers.codidact.com` produces a 500 Internal Server Error.

**To Reproduce**
1. Go to any of the policy pages above
2. See error

**Expected behavior**
The policy is viewable as on all the other sites.

**Screenshots**
[On the Internet Archive](https://web.archive.org/web/20210614164432/https://linux.codidact.com/policy/tos) or as a screenshot: 

![2021-06-14_17-56](https://user-images.githubusercontent.com/67427173/121930092-dd9fcf00-cd39-11eb-8781-5f7f8a0e2e77.png)

**Desktop (please complete the following information):**
Firefox 90.0b5 on Linux

**Comment by cellio** [comment]
The policy section is also missing from the help page on these communities.  Looks like a community seeding issue -- @ArtOfCode- or @luap42 does that sound right to you?

**Comment by ArtOfCode-** [comment]
Seeded and fixed.

**Comment by cellio** [comment]
@ArtOfCode-  do we need to change anything in new-community creation (code or process)?

**Comment by ArtOfCode-** [comment]
I just need to remember to run a full seed instead of part seed, that's all
