### ISSUE TITLE
Answer link didn't work with pagination

### ISSUE THREAD

**Issue by cellio** [codidact/qpixel#518]
I followed a link from the user's profile to [this answer](https://codegolf.codidact.com/posts/282241#answer-282241), but it instead took me to the question.  The answer is not on the first page, so I assume we loaded the page, looked for the answer, failed, and defaulted to the question.  Is there a way to make it handle pagination without a big performance hit for the non-pagination cases (most of them)?

**Comment by ArtOfCode-** [comment]
Not easily. We'd need to get the row's position in the result set, which would involve running two extra queries (full set of answers, count of results before target, in addition to the existing paginated answers query) and probably around 250% runtime.

**Comment by kevinmmansour** [comment]
Are you sure? It works for me well. :)

**Comment by cellio** [comment]
Just tested using the link in the description here and it didn't take me to an answer.  What are you seeing @kevinmmansour ?  (I forget -- is it your answer?  It would be interesting if it behaves differently for the owner than for others.)

@ArtOfCode-  when we follow the link and fall back to going to the top of the page because the answer ID isn't there, can we *tell* that that's happened?  If so, in that unusual case, could we give the user an option to "try other pages" and only do the extra work on that request?  (I was going to ask if we could, in that case, proceed to the next page and try again, but that would be bad if a challenge got dozens or hundreds of answers.)

**Comment by kevinmmansour** [comment]
When I click the link you addec to the GitHub Issue Description, it took me to the answer normally and this is what I see:

![Image](https://user-images.githubusercontent.com/71846550/125629156-3b42c3d4-1843-483a-a9be-15f828fc61a7.png)

When I go to [Mark Giraffe's Account](https://codegolf.codidact.com/users/54114) and I scroll down to the question (which is [ "Hello, World!"](https://codegolf.codidact.com/posts/279147#answer-282241) and I click on it, it took me to [the answer](https://codegolf.codidact.com/posts/279147#answer-282241) and see is what I see:

![image](https://user-images.githubusercontent.com/71846550/125630706-8a47de52-2a4c-4539-8bfb-42013f22617f.png)


I am also not the answer owner or the question owner.

**Comment by cellio** [comment]
Ah, it must be the random ordering.  When you are taken straight to the answer, is it on page 1?

Mark's answer and several others all have the same score, and the page break is in the middle of them.  Posts with the same score are ordered nondeterministically.  For me his answer came out on page 2 just now, not page 1.  (It certainly did when I first posted this, as it was new and unvoted at the time.)  You should be able to reproduce the issue by using the answer link for the lowest-scoring answer on a multi-page question, assuming that score is low enough to guarantee it won't be on page 1.

**Comment by kevinmmansour** [comment]
I could reproduce with lowest scoring answer on that question, which is [this answer](https://codegolf.codidact.com/posts/282584#answer-282584).

**Comment by Istiakshovon** [comment]
I guess it is working fine now. When I had clicked on an answer (from profile). I saw that it was bumped to top. But, that answer was actually in second page (when I visit that question and looking for that answer). Seems like the bug is fixed (with new bug :rofl: )

**Comment by MoshiKoi** [comment]
@ArtOfCode- Would "floating" the requested answer be less resource intensive? That is, it would grab the requested answer and put it at the top, and then sort the remaining posts normally. It already needs to grab and sort the answers anyway.

**Comment by ArtOfCode-** [comment]
@MoshiKoi Yes, it would... problem there is that the server doesn't have access to the anchor, so it doesn't actually know which is requested. Doable if we change our answer permalink structure, but non-trivial.

**Comment by MoshiKoi** [comment]
@ArtOfCode- I mocked up https://github.com/MoshiKoi/qpixel/tree/issue-518 which uses a query string. What do you think of it? Is it a viable strategy?

**Comment by ArtOfCode-** [comment]
@MoshiKoi I like your implementation of the query. We should keep the current link format for back-compat, but in addition I think we should also change answer permalinks to a `/posts/:id/:answer` format pointed at the same action so that we can avoid an extra request and redirect on new links (and change post permalinks to use it).

**Comment by MoshiKoi** [comment]
@ArtOfCode- What do you mean by back compatibility? We are currently using `/posts/:answer_id#:answer_id` as the permalink format. Those will continue to work, since that's the same format I use (though i don't use the fragment, instead adding the fragment on redirect).

As for `/posts/:id/:answer`, I originally wanted to do it that way, but it conflicted with the `/posts/:id/history` route and I don't know how to work around that

**Comment by ArtOfCode-** [comment]
@MoshiKoi yep, `/posts/:answer_id#:answer_id` should continue to work, as you have done. I'd also like `/posts/:parent_id/:answer_id` (with optional anchor) to work, because that avoids the extra redirect. As long as you put that in the routes file _after_ any named routes like history, it shouldn't conflict with them.

**Comment by MoshiKoi** [comment]
@ArtOfCode- Done. "Copy Link" on answers now also uses the `/posts/:parent_id/:answer_id` path.
