### ISSUE TITLE
Can't edit old question; error "Not all of this question's tags are in the correct tag set."

### ISSUE THREAD

**Issue by 1ec2466** [codidact/qpixel#52]
I'm trying to edit a question on Writing Codidact tagged: *editing world-building psychology-of-writing*.

When I have made the edit and click "Save Changes", I get an error message back:

> The following errors prevented this post from being saved:
> 
> * Not all of this question's tags are in the correct tag set.

This looks like the same error as in #46, but whatever was done to fix that doesn't seem to have worked for this other question on main Q&A.

Desktop Firefox 68.7.0 on Debian GNU/Linux.

**Comment by ArtOfCode-** [comment]
Should be fixed now.
