### ISSUE TITLE
Investigate SciSpec load times

### ISSUE THREAD

**Issue by ArtOfCode-** [codidact/qpixel#521]
Loading the SciSpec homepage is repeatably taking 3+ seconds server time to load. MiniProfiler is identifying the main posts query and count query as the source of that, but it's not entirely clear why. Needs looking into.

**Comment by cellio** [comment]
Slow but not as slow on Writing, fast on Photo.

SciSpec has 10k questions, Writing 5K, Photo 17.

This doesn't mean there's causation and maybe not even correlation -- just observations, worth what you paid for them. :-)

**Comment by ArtOfCode-** [comment]
Investigated and fixed.
