### ISSUE TITLE
Indicator of new posts in other categories

### ISSUE THREAD

**Issue by cellio** [codidact/qpixel#53]
When categories are updated infrequently (blogs, resources, sometimes meta), it's easy for new posts to fly under the radar.  Could we have some sort of indicator in the category tab that there's new stuff, since your list visit, over there?  This could be either a count (like"Meta (2)") or just a toggle if there's anything (like "Meta (*)").  This should trigger on new posts but not new comments.  Visiting the category should reset it, even if you didn't click through to read the new posts.

**Comment by luap42** [comment]
Additional idea: What about subscriptions per category?

**Comment by ArtOfCode-** [comment]
Closed by 9fee23dd6f142ddb2cd02f0ed2c0dfc9d02a5e08 and previous.
