### ISSUE TITLE
Add post content to comment threads

### ISSUE THREAD

**Issue by MoshiKoi** [codidact/qpixel#531]
GitHub issue for https://meta.codidact.com/posts/282397#answer-282397

Many people have requested that the post content of the post being commented on be put somewhere on the page for easy reference when commenting.

**Comment by cellio** [comment]
I *think* this isn't too hard, but I'm leaving complexity for someone who knows more to assess.

**Comment by luap42** [comment]
IMO complexity low, should just be a combination of two already existing implementations:

1. the code for rendering a post is shown in https://github.com/codidact/qpixel/blob/develop/app/views/posts/edit.html.erb#L40-L41 already,
2. for accessing the post of the thread, there's already the global variable `@post` available in [the thread view](https://github.com/codidact/qpixel/blob/develop/app/views/comments/thread.html.erb)

**Comment by Istiakshovon** [comment]
@luap42 I had tried to copy-paste 

```
<% if @post.parent.present? %>
  <h2 class="h-m-t-8">Responding to:</h2>
  <%= render 'posts/expanded', post: @post.parent %>
<% end %>
```

But, I noticed I can't see any changes that's why I didn't pull request. 

Location I pasted : comments/thread.html.erb

**Comment by luap42** [comment]
@Istiakshovon yeah... would be too easy if you just had to copy it, wouldn't it? :smiling_imp: 

Hint: you don't want to check the parent of the thread post.

**Comment by Istiakshovon** [comment]
> @Istiakshovon yeah... would be too easy if you just had to copy it, wouldn't it? smiling_imp
> 
> Hint: you don't want to check the parent of the thread post.

Ow! Thanks! I don't know ruby-on-rails much more. But, I was trying to solve it lot of way. And, I just remember your words in my mind. Now, it's working. Again, Thank your :D

**Comment by Istiakshovon** [comment]
@MoshiKoi What if a thread has more than 50 comments? Of course, thread will become too big in `comments/thread/`. But, if we implement post also than, the page will become bigger than usual.

**Comment by cellio** [comment]
If a thread has 50+ comments the page is already going to be long, but that's ok because the reader chose to go there.  I don't think adding the post to the top makes that particularly worse and it's often helpful.

We want to leave the reader positioned at the beginning of the comments to avoid confusion, not the top of the page where, with a long post, the comments might be out of view.  If we can't do that, consider showing the first part of the post and then putting the rest behind an in-page "expander".

**Comment by Istiakshovon** [comment]
https://github.com/codidact/qpixel/pull/537
