### ISSUE TITLE
searching "create" doesn't work properly

### ISSUE THREAD

**Issue by Istiakshovon** [codidact/qpixel#532]
![Screenshot from 2021-07-04 23-31-21](https://user-images.githubusercontent.com/58106197/124414467-cf354980-dd20-11eb-8f64-35c23918ebb0.png)

>the search `score:>=0.5 created:<1y grammar` would return only posts mentioning "grammar" that have a `score >= 0.5` and were created less than a year ago.

But, when I used `create:>1y moderator choosing` I got some questions which was posted less a year also. I had tried the opposite also `create:<1y moderator choosing`. It was also returning those post which was posted less a year (Somehow I got a question/answer which was posted 1 year ago).

**Comment by cellio** [comment]
Reproduced.  I tried adding a score argument to the last query (to match the working one), but it didn't change the results.  I also tried putting the search terms first and the filters after -- again, no change.

**Comment by ArtOfCode-** [comment]
@cellio @Istiakshovon Just to confirm - the screenshots here show "create:>1y", but the documentation specifies "created:>1y". Which are you both using?

**Comment by Istiakshovon** [comment]
@ArtOfCode- documentation specified `created:<1y` not `created:>1y`

**Comment by ArtOfCode-** [comment]
@Istiakshovon either way, but are you using `create` or `created`?
