### ISSUE TITLE
If a tag wiki is long don't show all of it by default on the tag page

### ISSUE THREAD

**Issue by cellio** [codidact/qpixel#536]
https://meta.codidact.com/posts/282086

If a tag wiki is long (and there are good reasons for them to be long), you have to skip past the whole description to get to the list of questions.  Sometimes you want the description, but often you just want the list of questions.  Can we show only the first paragraph or so of a long description and put the rest behind an in-page expander like the HTML `details` element?  We don't want people to have to go to a separate page, but maybe the first, say, 500 characters plus a thing to click would be good enough?

We should always show the full *summary*; this is about the longer description.

Here's an example case: https://software.codidact.com/categories/38/tags/3296

**Comment by Istiakshovon** [comment]
I have seen [a tag](https://stackoverflow.com/tags/python/info) (in SO) which wiki is too large. I want to add some context also. 

When you look at our tag you will notice that there's no context like `Tag Info` or something just like this. I guess, we should add something like this
![Uploading Screenshot from 2021-07-17 11-57-39.png…]()

**Comment by cellio** [comment]
The sections aren't labeled, if that's what you mean -- there's a box with the summary and then another box with the longer description, and after that the list of posts (with two options, tag-only and tag+children -- we have hierarchical tags, unlike Somewhere Else).

My suggestion would be to always show the summary (the first part) and, if a longer description exists, show it behind an expander (same idea as the "Post" link at the top of a comment-thread page).  If there is no longer description, then keep the current behavior, which is to show text saying there isn't one and inviting you to create one.  (Example: https://software.codidact.com/categories/38/tags/4015)

**Comment by Istiakshovon** [comment]
![Screenshot from 2021-07-22 12-01-11](https://user-images.githubusercontent.com/58106197/126670856-8bde72a2-f77f-4936-b286-078de93bf0ad.png)

Is it OK? If length of tag wiki is over than, 500 then it will show like this. What do you think of the design?
