### ISSUE TITLE
Posting sometimes doesn't clear the saved post

### ISSUE THREAD

**Issue by cellio** [codidact/qpixel#538]
https://meta.codidact.com/posts/280046

This is an old meta post so I would think we had an issue for it already, but I can't find it.  Sometimes -- and I've experienced this recently -- after I post an answer and then open the question page again, the textbox to add an answer is filled with my draft -- even though that draft was posted in a separate answer.  This can lead to double posting, as reported recently here: https://meta.codidact.com/posts/282157.  (On that post, the prompt for image alt text was also involved.)

We of course want to err on the side of keeping a draft too long as opposed to discarding it prematurely.  Is there a timing thing going on, where the answer is "in flight" but not yet visible at the time the decision is made about whether to show the draft?  Can we do anything about it?

**Comment by Istiakshovon** [comment]
Could you please add some context how the notification should look like? I have written some context.

```
There are new comments in a followed thread $thread_title on $post_title
You were mentioned in a comment to $comment_thread.title on $post.title
```

And, another one is OK. `New comment thread on $post.title: $comment_thread.title`

**Comment by cellio** [comment]
@Istiakshovon this issue is about posts being saved but the draft not being cleared.  The commit you linked seems to be about comments.  Did you mean to connect it to a different issue?

**Comment by Istiakshovon** [comment]
@cellio Oh! I am really sorry. I mistakenly mentioned it. I will find the correct one when I will on my laptop
