### ISSUE TITLE
"Not Found" page says to contact administrator at invalid email address

### ISSUE THREAD

**Issue by 1ec2466** [codidact/qpixel#54]
I noticed that on Writing Codidact, the "Hot Posts" sidebar has one Meta question, three Q&A questions, and one untagged "Terms of Service" which points at `https://writing.codidact.com/questions/39221`

Following that link (at least without having signed in) leads to a "Not Found" page.

That page, in turn, includes this sentence:

> If you believe you encountered this page in error, or you want to report a fault, you can contact the administrator at contact@example.com.

While `example.com` is good for, well, examples (it's reserved for the purpose by RFC 2606), it doesn't make a particularly useful email address for someone to use to try to contact a live human.

I believe that, if it's to be there, the email address should be changed to a valid one which reaches a live human being.

**Comment by ArtOfCode-** [comment]
Fixed, thanks!
