### ISSUE TITLE
Still see "Suggest Edit" after earning or being granted the Edit ability

### ISSUE THREAD

**Issue by cellio** [codidact/qpixel#540]
https://meta.codidact.com/posts/282165

The user earned the Edit ability but continues to see "Suggest Edit" instead of "Edit" under posts.  I just tested on the dev server by granting the ability to a user and was able to reproduce.  I don't know if this eventually flushes some cache and fixed itself or if it stays this way forever.

**Comment by sau226** [comment]
Easy fix, there was a missing "s" in a conditional check

**Comment by cellio** [comment]
One-character fix - nice
