### ISSUE TITLE
Starting a thread with a comment that's too short returns 422

### ISSUE THREAD

**Issue by cellio** [codidact/qpixel#541]
https://meta.codidact.com/posts/282480

I've reproduced this in production.  On that question I started a new thread, entered "too short" as the comment text, didn't enter a title, and clicked the post button.  I got a 422.  I expected to get "Content is too short (minimum is 15 characters)", like I do when adding a comment to an existing thread.

The 422 is kind of baffling; it suggests logging out and back in, which isn't going to help in this case.  It seems like there's one error-checking call we've missed specifically in the "create new thread" case.

**Comment by kevinmmansour** [comment]
Done! with at least of 15 characters.
