### ISSUE TITLE
Vote (up minus down) calculation error

### ISSUE THREAD

**Issue by Istiakshovon** [codidact/qpixel#550]
https://software.codidact.com/users In this page, Vote (up minus down) showing -1 for [pnuts](https://software.codidact.com/users/19944/posts?page=1). While he got only 16 downvotes and his upvote is greater than downvote. I think there's something wrong with calculation.

![Screenshot from 2021-07-10 03-22-34](https://user-images.githubusercontent.com/58106197/125155489-507c4a00-e12e-11eb-8224-67d6a4fde54c.png)
 
Same thing happened for me also. I think it is happening for deleted questions/answers.

**Comment by ArtOfCode-** [comment]
No error here. That count is votes _received_, and pnuts has received 51 upvotes and 52 downvotes.

**Comment by FoggyFinder** [comment]
I think it would be better to document it somewhere somehow. I'm sure current implementation isn't totally obvious

**Comment by ArtOfCode-** [comment]
@FoggyFinder It says in the tooltip on that icon that it's a sum of votes _received_, up minus down. We also have a change going in shortly that will display that on the profile page.

**Comment by FoggyFinder** [comment]
yeah, I know but I, as well as TS, thought that removed Qs aren't counted. Also, what happens with migrated Qs? Are they included in stats for both communities?

**Comment by cellio** [comment]
It seems to be counting all questions including deleted ones?

**Comment by Istiakshovon** [comment]
@cellio https://github.com/codidact/qpixel/issues/564#issuecomment-881794924

**Comment by Istiakshovon** [comment]
> yeah, I know but I, as well as TS, thought that removed Qs aren't counted. Also, what happens with migrated Qs? Are they included in stats for both communities?

Actually, I haven't find any way migrate post to another community. I only found "migrate to another category" system
