### ISSUE TITLE
Add search syntax for category, post type, and user

### ISSUE THREAD

**Issue by cellio** [codidact/qpixel#554]
Search syntax is documented in the help center.  You can search by tag, score, votes, creation date, and several other things.  To this we want to add three search keywords:

- category: the argument is the category _number_, not name, which users can get from the URL.
- user: also a user number, not name.
- type: post type (question, article, etc).  @ArtOfCode- said in chat that searching by literal string (like "question") is problematic for various reasons, _but_ it should be easy to do auto-complete like we do with comment pings.  So you start typing "type:ar" and it pops up "article" as a suggested completion.

To use category names we would have all the parsing issues that we'd have with types, plus we'd have to add the current community to the lookup because names aren't unique (everybody has Q&A and Meta).  User names, similarly, are not unique even within a community.  For these, the expedient thing to do is to use the numeric IDs.  We can't do that for post types, though, because those numeric IDs aren't exposed anywhere in the UI.  But there also aren't a lot of them, so ping-style auto-completion shouldn't be a burden.

When we implement this we can:
- mark https://meta.codidact.com/posts/280584 as status-completed (this was the last piece of https://github.com/codidact/qpixel/issues/429, which is otherwise closed)
- resolve https://github.com/codidact/qpixel/issues/384
- resolve https://github.com/codidact/qpixel/issues/444 (the solution here will be different than the one proposed there but this works for that)

And while this doesn't resolve it, we'll make some progress on https://github.com/codidact/qpixel/issues/534.

**Comment by cellio** [comment]
Art said this is a good first issue.  I'm guessing on complexity; if it's easy please adjust.

**Comment by manassehkatz** [comment]
As I understand it, the current search is **inside the currently selected Community**. Assuming that is always the case (I can see some use for cross-Community searches, but *generally* speaking it doesn't make much sense and would absolutely raise some scaling issues if/when we switch to DB-per-Community, plus some UI complications), then some of the complications regarding searching by Category and Post Type should disappear as those lists are short and "simple obvious text" when used within an individual Community.

**Comment by cellio** [comment]
The issue is actually the string parsing.  Many categories have names with spaces and/or special characters, so that means quoting and maybe escaping, and string-parsing always ends up being messier than it should be, so Art and I figured that since the category number is readily available, it wouldn't be unreasonable to use that.  I suppose we could do ping-style completion on those too, but... let's get a basic version working first and then decide what else we need?

**Comment by cellio** [comment]
Apparently we already have user:####, so this is to add category and post type.
