### ISSUE TITLE
On user profile, add a link to Discord user

### ISSUE THREAD

**Issue by cellio** [codidact/qpixel#562]
Our network uses Discord for chat and will for the foreseeable future.  It would be helpful for users who want to be able to discuss posts more casually, and really helpful for moderators who want to be able to have a private word with somebody, if profiles supported a Discord link alongside blog and twitter.  We'd still need to ask people to fill it in, but it removes one barrier.

I'm not sure what form the link should take -- name#number?  (That's what I got when I copied from my profile link at the bottom.)  Is there a URL?  I'm looking for a path for a user (or moderator) to say "I'd like to chat with so-and-so and I have this Discord thing -- let's do it".

**Comment by kevinmmansour** [comment]
Well, It is called "Discord Tag". Something like Username#0000. So we have to say: "Discord", "Your Discord Tag , if you've got one you want to share.".

**Comment by ArtOfCode-** [comment]
Closed with 89fe7a2dfc680579e5bd1406a57aa17e3c45022f

**Comment by Istiakshovon** [comment]
No! That's not.. 
![Screenshot from 2021-07-27 03-44-21](https://user-images.githubusercontent.com/58106197/127116076-2d4b9553-a235-48dc-9de0-395224676926.png)

discordapp.com/users/ID

**Comment by Istiakshovon** [comment]
You have to visit discord.com to access those keywords. My above comments gives direct link to user. :)
