### ISSUE TITLE
When signing in, didn't redirect to the page I was on but to the "new post" page

### ISSUE THREAD

**Issue by cellio** [codidact/qpixel#569]
I was viewing https://software.codidact.com/posts/282752 while logged out.  I logged in, and it redirected me to https://software.codidact.com/posts/new/1/38.  I expected to be back on the original page or, failing that, the main page for the community, but not the "create new post" page.

**Comment by ArtOfCode-** [comment]
Is this reproducible? Sounds odd - I've never had it do something like this to me...

**Comment by cellio** [comment]
Huh, weird!  I just tried on a different browser (and in incognito mode), and it redirected me to the question list, not the "ask" page.  It'd still be nicer if it redirected to the page I was just on, but at least the question list doesn't leave me completely scratching my head.
