### ISSUE TITLE
Changing your email boots you to /users (doesn't exist)

### ISSUE THREAD

**Issue by MoshiKoi** [codidact/qpixel#571]
If you change your email address on the /users/edit page and click Update, it redirects you to /users which doesn't exist (404)

**Comment by cellio** [comment]
Could you share the full URL of the page that returned the 404?  For example https://meta.codidact.com/users exists, so I gather that's not what you meant.

**Comment by MoshiKoi** [comment]
Hmn, that's odd...
![image](https://user-images.githubusercontent.com/54333972/127758130-755d2bc1-1e1a-4912-aef5-a10323d45ed1.png)

Refreshing doesn't give me the page either.

However, when I manually go to the url, it works, so I guess it's something my browser is sending with the update request that's bugging it?

**Comment by Istiakshovon** [comment]
The error message : `ArgumentError: No :access_key_id provided`

**Comment by ArtOfCode-** [comment]
Fixed
