### ISSUE TITLE
Discord ID not shown on profile if it's the only link

### ISSUE THREAD

**Issue by cellio** [codidact/qpixel#575]
(Reported by @kevinmmansour in chat and I reproduced.)

If you edit a profile to add a Discord ID, and do not also have either a website link or Twitter ID, the change is correctly saved but it is not displayed.  If a website or Twitter ID is provided, Discord is shown. 

The Discord ID is saved; it's just not being displayed.  I suspect that in the front-end code the Discord div (or whatever we use) accidentally depends on the others.  It's possible to have a website without twitter or twitter without a website, so whatever we did to make those stand alone we should also do for Discord.

**Comment by MoshiKoi** [comment]
One line fix: Just add discord to the if statement here
https://github.com/codidact/qpixel/blob/e96dcecebc5d215dd67626083c5b26d97330587b/app/views/users/show.html.erb#L27

**Comment by MoshiKoi** [comment]
To be honest, you might as well delete that if statement. There are individual ones for each item anyway.

**Comment by kevinmmansour** [comment]
@MoshiKoi Good, same as what I thought. Pull Request has been done. I removed `if` statement at all.
