### ISSUE TITLE
Username is editable from both Account and Edit, and with different security

### ISSUE THREAD

**Issue by MoshiKoi** [codidact/qpixel#576]
On the user page, you can edit your username on both the Account and Edit tabs.

When editing from the Account tab, you must provide your password to confirm changes. When editing from the Edit tab, you don't need to provide your password.

I think either both of them should require the password or neither of them should, right now it seems like an oversight and one of them is too strict or too lax.

**Comment by kevinmmansour** [comment]
I think it should be in one place only and I would suggest to be in "Account" Tab with the need to provide your password in order to continue.

**Comment by Istiakshovon** [comment]
While username is available in `account` management. So, I think it won't affect if we remove it. Or, label it instead of `EditText`

**Comment by sau226** [comment]
I think we should remove it from the account page, as we don't want to fragment things by removing the username field from the page where you set your avatar, bio and social links.

If we can come to a consensus on this issue, happy to see if I can implement a result.

**Comment by cellio** [comment]
I agree -- leave it (editable) on the regular edit page with everything else, and remove it from the "account" page.  It's just a display name; it's not part of your account identity (email + password).

**Comment by sau226** [comment]
I filed a PR that should remove the duplicate field. It was briefly tested on the dev server as well.
