### ISSUE TITLE
Can't sign in if 2FA is enabled

### ISSUE THREAD

**Issue by kevinmmansour** [codidact/qpixel#578]
**Describe the bug**
Today, I have just enabled 2FA and I have just signed out from my account manually when I sign in, I get:

![Preview](https://user-images.githubusercontent.com/71846550/127457198-e69c73f2-aa92-47cc-979e-62e438340255.png)

Looks it just redirect to the wrong page (I would guess that it should redirect to the page where you enter 2 factor code). also I see the alert says: "Signed in successfully" but clearly I am not signed in and I cannot sign in.

**To Reproduce**
1. Enable 2FA.
2. Sign out.
3. Try to sign in.
4. You will see 404 (Same as screenshot above).

Thanks for snail_ for reporting this bug and I have reproduced.

**Comment by ArtOfCode-** [comment]
Fixed with b4b6acf9804d86623def3dbb2bd9a3d0e2fba36d
