### ISSUE TITLE
Per-category access restriction

### ISSUE THREAD

**Issue by cellio** [codidact/qpixel#58]
A user on Writing Meta suggested a category where people could post their work, either for critique or just to share.  A concern is that publishing something, even informally, can impede or even prevent selling that work to a publisher later -- some publishers won't buy what was previously publicly available for free, even if that was an earlier or unfinished draft.  The thinking is that restricting read access to the category to signed-in users would suffice.  See https://writing.codidact.com/questions/74774#answer-74810.

In thinking about this use case, I realized there's another use case for access-restricted stuff: moderator-only content.  On my sites we sometimes wanted to have a place to stash things like templates for our own mod messages, notes about ongoing investigations, and suchlike, and mod chat on SE was terrible for that (and we're not planning chat, let alone private chat, for MVP).

Note that there are two factors here: visibility of the *content* (can be gated by trust level), and visibility of the *category*, i.e. even seeing that it exists.  For the moderator case there'd be no reason for non-mods to see a tab (and entry in the category list) that they can't access.  For the Writing case that's less clear; maybe we want a tab that, if you click on when not signed in, gives you a message about how to access that content.  Or maybe it should stay hidden.  We need to think more about that part.

**Comment by ArtOfCode-** [comment]
Fixed by 15f3ef8 - a category can now either:
 * restrict _posting_ by trust level (everyone can view, only those over set level can post) 
 * restrict _viewing_ by trust level (everyone can post, only those over set level can view - not sure what the use for this is, but it's possible)
 * restrict both, though the levels can be different thresholds - say only moderators and admins can view, but only admins can post

**Comment by cellio** [comment]
Sounds great!  I agree the middle option doesn't make sense.)

Now we have to implement trust levels so we can use this. :-)

**Comment by ArtOfCode-** [comment]
There's a pseudo-trust-level implementation in there to make this work - regular users are TL1, moderators are TL5, admins are TL6.

**Comment by 1ec2466** [comment]
It seems to me that the "restrict viewing" option could be of use for submitting sensitive information for review by more trusted users. For example, an ordinary user could submit information for moderators to review, when there's too much of it to put in a flag (or it doesn't associate well with any particular post, so there's nothing obvious to flag in the first place). I'm not sure how *useful* this would be for anything like Q&A, but it's a possible *use case*.
