### ISSUE TITLE
I can see a removed thread in Linux Systems

### ISSUE THREAD

**Issue by Istiakshovon** [codidact/qpixel#580]
I can see a removed thread in Linux Systems. https://linux.codidact.com/comments/thread/3720 

![Screenshot from 2021-07-30 01-57-21](https://user-images.githubusercontent.com/58106197/127607671-eaaf82e2-678d-4d64-998b-249b7df5ab2b.png)
 The thread were created by Elgonzo. And, I guess, it was deleted by a moderator.

**Comment by kevinmmansour** [comment]
404 for me.

**Comment by Istiakshovon** [comment]
@kevinmmansour  It's only showing for me.

**Comment by kevinmmansour** [comment]
> 
> 
> @kevinmmansour It's only showing for me.

Yes, maybe since your the answer author or because you leaved a comment.

**Comment by cellio** [comment]
I believe you can always see your own deleted *posts* even if you can't normally see deleted posts, so I'm guessing some logic spilled over into threads.  I don't think participants (or creators) should be able to see deleted comments or threads; let's keep that to mod-only.

**Comment by Istiakshovon** [comment]
> I believe you can always see your own deleted _posts_ even if you can't normally see deleted posts, so I'm guessing some logic spilled over into threads. I don't think participants (or creators) should be able to see deleted comments or threads; let's keep that to mod-only.

Yes! Earlier, I couldn't see. But, when my account was deleted. Then, I can see. So, it's bug.
