### ISSUE TITLE
can't create account or, send confirmation code from Linux CD

### ISSUE THREAD

**Issue by Istiakshovon** [codidact/qpixel#587]
When I was creating an account from Linux.Codidact.com I got 404 error. When I tried to sign up again I got a message which was email already taken. But, I didn't get any mail. So, I was trying to resend confirmation code it also returned 404 error. 

![Screenshot from 2021-08-01 12-23-05](https://user-images.githubusercontent.com/58106197/127778184-804c1122-35e7-4aeb-bd16-f6435931efd3.png)

**Comment by cellio** [comment]
Is this still happening, or did the linked change fix it?

**Comment by ArtOfCode-** [comment]
Fixed
