### ISSUE TITLE
not able to create any post (only in my server)

### ISSUE THREAD

**Issue by Istiakshovon** [codidact/qpixel#590]
![Screenshot from 2021-08-02 02-08-04](https://user-images.githubusercontent.com/58106197/127812060-82ec63c8-5085-411e-b613-51767a12f106.png)

I was trying to delete an user. But, unfortunately the button wasn't working. `http://localhost:3000/users/2/mod`. `Destroy user, Delete community-profile, Delete network-wide` isn't working. Earlier, Feed to STAT was working. But, It is returning 418 error now(Operations are on pause while we attempt to recapture the codidactyl. Please hold.). I have cloned qpixel again. Although, facing the same issue. 

<hr/>

The issue is not only for those things. Currently, I can't do anything with my server. Why that's happening? I guess, it is only happening in my system.

**Comment by Istiakshovon** [comment]
I am creating Collab post...

**Comment by luap42** [comment]
Well that's kinda by-design. When you click "feed on STAT" on a user, that user is put on a special block list, which causes these random error messages appear, when you try to do anything. However, STAT doesn't relate only to a specific user, but to the email address and your IP, so apparently you have blocked your own computer locally :P

Fix: open a rails console (`rails c`) and run the following command:

    BlockedItems.all.delete_all

If I am right, this should also fix your other issue #591, as STAT also disallows registrations.

**Comment by Istiakshovon** [comment]
@luap42 Sorry! https://github.com/codidact/qpixel/issues/591 the issue is happened in Linux systems (https://linux.codidact.com) not in my server.
