### ISSUE TITLE
Auto-delete thread if all comments in it are deleted

### ISSUE THREAD

**Issue by cellio** [codidact/qpixel#592]
Prompted by https://meta.codidact.com/posts/283054 and Mith's comment there:

When all comments in a thread are deleted, please also automatically delete the thread.  People who can see deleted comments can also see deleted threads, so this doesn't make anything less accessible, and it allows users to clean up comment threads themselves without requiring mod intervention.  This can happen if somebody asks a question in a comment and then realizes the answer (and so deletes the comment), or if two people have resolved a discussion and both cleaned up their sides, or if all comments have been deleted through flags.

I think we could do this by modifying the "delete comment" code to, after deletion, check if surviving comments = 0 and if so delete thread too.

**Comment by Istiakshovon** [comment]
But, there's a problem. Everyone had requested that there should be a general comments thread by default which contains 0 comments by default. If we delete a thread if that is empty than, General comments will disappear(since, there's no general comments by default now. So, you can ignore the message  also)

**Comment by cellio** [comment]
We don't currently auto-create a "general comments" thread.  Threads are started by new comments.  If there's a "general" thread that gets deleted by having all its comments deleted, then someone can start a new "general" thread with a new comment.  We don't check for uniqueness in thread names; in fact, you could have duplicate names in live threads now.

**Comment by cellio** [comment]
@ArtOfCode-  one problem: the thread does get auto-deleted now (good!), but as a moderator I can't see the deleted thread under the post like I should be able to.  Haven't tested yet whether this is a problem with the auto-delete case specifically or a broader problem with deleted threads (need to find or make another).
