### ISSUE TITLE
I can vote after account also

### ISSUE THREAD

**Issue by Istiakshovon** [codidact/qpixel#593]
I said earlier that i could do everything after account deletion also. Then, @ArtOfCode- had made some changes. So, now i can't visit those site. I noticed that i couldnt write answer. But, i could vote on post. I thought fake vote was showing. So, i had moved to new tab and, checked that post. Then, i noticed i truly upvoted a post. I can create new question also. https://software.codidact.com/posts/283057 but, i can't remove it or, edit it. So, please remove it  now

**Comment by ArtOfCode-** [comment]
Fixed by 9bfc5e44b1d5f5f3e20e8e6d0b3fe7ffdd3b07e4
