### ISSUE TITLE
`users/edit` returns 500 error

### ISSUE THREAD

**Issue by Istiakshovon** [codidact/qpixel#595]
`/users/edit` gives me 500 error. I had earlier changed my email. But, completely messed up. After seeing a bug, I was going to test that (That bug was saying that if I try to update email then, `/users` gives 500 error maybe (I am not sure of the error message)). I didn't get any mail to confirm that. So, after 4-5 days I was trying to create a new account with that same email address. https://github.com/codidact/qpixel/issues/587 (I had got another error there either). So, I stopped. Then, I visited Software Development then, requested a email confirmation from Software Development since, creating a new account was returning email already exists. I got email but, I didn't notice. Later that day, I had seen that email. Then, confirmed that email. Now, I got the error. Not only meta every community is returning the same error including Linux systems (where my account was deleted). **Incognito returns same error (I didn't sign in) which proves that the problem is happening with everyone.** (I didn't delete earlier contents cause, I don't know if someone else is facing the issue.)

![Screenshot from 2021-08-03 11-30-58](https://user-images.githubusercontent.com/58106197/128043381-c10b2d74-6a07-40b1-a08e-8f16d491056e.png)

**Comment by ArtOfCode-** [comment]
Fixed by 89c0aaa324df8781ac5debdc81d92296d2f93fce

**Comment by Istiakshovon** [comment]
@ArtOfCode- https://meta.codidact.com/users/edit Still available.... I had tried in Incognito again. I am getting same error there either.

**Comment by ArtOfCode-** [comment]
Haven't deployed that commit yet, so the fix isn't live.
