### ISSUE TITLE
keyboard shortcuts for comment @-mentions, search categories, and anywhere else we use that style of selector

### ISSUE THREAD

**Issue by cellio** [codidact/qpixel#600]
https://meta.codidact.com/posts/283041

> When writing a comment, you can type @so-and-so and a little popup will show you the mentionable people that match so-and-so. The new search options seem to use the same dropdown. However, for both, there doesn't seem to be a way to select them without using your mouse and clicking on the one you want.
> 
> Suggestion: Make the choices selectable by arrows keys and auto complete using the enter key, just like the tag dropdown when creating posts.

Further suggestion: do this wherever we define that style of selector widget (which might be in CoDesign or might be here; I don't know), so that if we have similar selectors in the future, up/down arrow and enter will do the same thing without extra work.

**Comment by ArtOfCode-** [comment]
Completed with 096506aa7630f1477a34896ac2356dee31a08468
