### ISSUE TITLE
draft not deleted after editing post maybe

### ISSUE THREAD

**Issue by Istiakshovon** [codidact/qpixel#602]
The bug was earlier available also (Draft not deleted after saving post). @ArtOfCode- had fixed the problem. But, later I noticed when I posted a question and, edited that post from `post/id/edit/` I noticed the post had came to `/post/new`. I am not sure if it's the problem. But, I have faced it. Today, when I was going to ask a question in Math CD than, I noticed my earlier question is showing as draft loaded. When I first faced it I thought the problem was on my browser. But, today I have faced it again.

**Comment by cellio** [comment]
To confirm: you started a draft question, cancelled it, started a new question, and saw your previous draft?

**Comment by Istiakshovon** [comment]
@cellio I don't know what was happening. Some time, draft isn't deleting. Some time it is deleting. Since, I exactly don't know what was happening. So, I am closing it.

**Comment by Istiakshovon** [comment]
It was happening in Physics CD site. Maybe, working fine in other sites (Tested in Math, Meta).
