### ISSUE TITLE
I can see deleted thread in Math CD

### ISSUE THREAD

**Issue by Istiakshovon** [codidact/qpixel#603]
I can see deleted comment thread in Math CD. The thread wasn't created by me. 

![Screenshot from 2021-08-06 06-58-12](https://user-images.githubusercontent.com/58106197/128500633-5a0af974-0041-407b-b630-9ceaacf3b737.png)

**Comment by ArtOfCode-** [comment]
Link?

**Comment by Istiakshovon** [comment]
https://math.codidact.com/comments/thread/3881

**Comment by ArtOfCode-** [comment]
Yep, that's because it's your post. Authors have all privileges on their own posts.
