### ISSUE TITLE
Selecting a mention only replaces the first three characters

### ISSUE THREAD

**Issue by MoshiKoi** [codidact/qpixel#619]
When mentioning someone in a comment, typing `@xxxyyyy` and selecting a result replaces it with `@#<id>yyyy`; that is, it only replaces the first three characters with the proper id.

-----

Meta Issue: https://meta.codidact.com/posts/283668

**Comment by cellio** [comment]
Reproduced: https://a.dev.codidact.org/comments/thread/47
