### ISSUE TITLE
Help edits pushed to all communities even if the box is unchecked

### ISSUE THREAD

**Issue by cellio** [codidact/qpixel#620]
Last week (?) one of our admins edited a help topic on one community, unchecked the "push to all sites" box, and nonetheless pushed the change to several sites (ones where the topic was not locally modified).  I cleaned up the affected pages (fortunately it was just changing $sitename in a few places) and we had a conversation in chat but I never filed a ticket (oops).

I was about to edit a help topic tonight on Meta and stopped at the last minute.  I don't think we found and fixed the problem, so here's a ticket now.

**Comment by ArtOfCode-** [comment]
Fixed

**Comment by ArtOfCode-** [comment]
61a2015ab86b5ae69264bb294bbbad09badb0f88
