### ISSUE TITLE
When trying to return request to server it returns 500 error later it automatically saves those process to database

### ISSUE THREAD

**Issue by Istiakshovon** [codidact/qpixel#626]
Look at [the thread](https://physics.codidact.com/comments/thread/4019), when I was trying to add comments it was returning 500 error. I had reported it in [Discord](https://discord.com/channels/634104110131445811/634104110131445815/876134744478335036). I had refreshed my page few times also. Although, I couldn't see any comment. Now, I have revisited that page again. Now, I noticed 7 comments were created by me. Even, I had flagged a post in Meta. I got 500 error. So, I reflagged when I had flagged again it worked. Later, I noticed I had flagged the same post twice. It's looking like server problem to me rather than qpixel.

**Comment by ArtOfCode-** [comment]
The error is trying to insert into the notifications table with a notification that's too long for VARCHAR.

**Comment by Istiakshovon** [comment]
still happening... https://meta.codidact.com/comments/thread/4174

**Comment by ArtOfCode-** [comment]
@Istiakshovon Yes, it will still happen until the update is deployed. You can check whether it's been deployed yet with the commit hash in the footer on every page.
