### ISSUE TITLE
Create Post button appears even when you don't have permission to post there, and you can still draft posts there

### ISSUE THREAD

**Issue by MoshiKoi** [codidact/qpixel#630]
Even though I do not have permission to post in the [Meta Blog category](https://meta.codidact.com/categories/30), the "Create Post" button still appears, and I can click on it to create a draft of a post in that category.

When clicking "Save post in Blog", it gives a red warning notice that says

>The following errors prevented your post from being saved:
>
> - You don't have a high enough trust level to post in the Blog category.

If I do not have permission to post in that category, could the button be removed so that it's more obvious before that notice is given?

**Comment by cellio** [comment]
I *think* this is easy but I'm not sure.  If it's easy let's prioritize it; it's an infrequent case but can be very frustrating for those who hit it.

We do a check on submit (and still should, in case of shenanigans), but can we *also* do a check either on page view (gray out the button) or, if that's too expensive, on button click, so somebody doesn't write a whole blog post only to find out *after* that the blog category is restricted?
