### ISSUE TITLE
Can we downplay linking SE accounts?

### ISSUE THREAD

**Issue by cellio** [codidact/qpixel#632]
https://powerusers.codidact.com/posts/283324

This question comes up pretty much every time we launch a community.  If a Codidact community does not have an associated SE site from which we've imported data, the profile edit tab shows the following:

> You can't link a Stack Exchange account to your account on this site because there is no associated Stack Exchange site from which to transfer your content.

*Most* of the time we don't do data import any more, but we need a place to add the link for the few cases where it matters.  I propose the following changes:

1. Add an optional SE link to the "regular" part of the profile, along with Twitter etc.
2. *If* a community has imported data, use that link to match up people.
3. If a community doesn't have imported data, it's just an informative link.  Some of our users want to be able to link to their profiles over there anyway, just to identify themselves, and this fills that need.

This also has the advantage of making that link editable.  I can't see my SE link on Writing; the UI doesn't show it, and if I wanted to edit it, I couldn't (except via support ticket + dev with DB access).

If I recall correctly, you only have to enter a link once and then, on any other community you're on, you'll get your imports.  For example, I think I associated Writing.SE and got Worldbuilding.SE for free.  It therefore seems like we accept any SE link and we navigate to the network profile and thence to other accounts as needed.  If that is correct, then I'd like to accept any SE account link including the network profile directly.

**Comment by ArtOfCode-** [comment]
I don't think letting people claim content just based on a link is the best way to do it: anyone could claim anyone else's content, with no oversight (which also presents copyright headaches). That's why it runs through SE OAuth so that we _know_ you're claiming content that you own (or have previously claimed to) elsewhere. We can still add a SE link to the profile if we want it, just not to use for content claim. We could also just not show a "link your SE account" section at all for sites that don't have a linked SE site.

**Comment by cellio** [comment]
Oh!  Yes, I forgot about the OAuth part, and I agree that's important.  Let's not show that section of the profile on communities without data import (which will be most of them).  Either that, or show it everywhere and adjust the text to say that this will be used if any data is imported, but that's going to be very rare going forward, so I think omitting it is better.

**Comment by cellio** [comment]
This was completed (as indicated on the linked post) but this issue didn't get closed then.
