### ISSUE TITLE
Minor: now that we have category subscriptions, drop the subscription links from right column

### ISSUE THREAD

**Issue by cellio** [codidact/qpixel#64]
The right column includes subscription links for "new questions" and "interesting questions".  I'm not sure those links still work with the change to categories, but since each category has a "subscribe" link at the top, even if they work they seem redundant.  Can we remove them?  It seems odd for subscription stuff to be in two different places on the page like that.

**Comment by ArtOfCode-** [comment]
Those links do different things to the category subscribe link - new questions gives you everything new, and interesting questions gives you random stuff over a score threshold (kind of like getting the lottery tab by email). I'm not so sure the category subscribe link makes them redundant.

**Comment by cellio** [comment]
Oh, I see.  Might want to change the first one to "all new questions on this site" or some such; I went through and subscribed to individual categories because I thought the global subscription links were deprecated.

**Comment by ArtOfCode-** [comment]
Aye, that'd make sense.
