### ISSUE TITLE
Unable to use shortcut tools for Answers

### ISSUE THREAD

**Issue by Istiakshovon** [codidact/qpixel#647]
I was trying to edit a post using shortcut tools. `t` it automatically selects question https://math.codidact.com/posts/283210. I was trying to use tools for answer by scrolling down. But, it also selected questions.

**Comment by ArtOfCode-** [comment]
Not sure what you mean here. What are you doing, what _should_ it do, and what _does_ it do?

**Comment by Istiakshovon** [comment]
I would like to go to edit page of answer. But, when I click `t` it selects question by default. But, I want to select answer. Hence, I think there should be a way to select answer.

**Comment by ArtOfCode-** [comment]
Yep, that makes sense. There already is a way to do this. Press `?` for help with keyboard shortcuts. You can use `j` and `k` to select previous/next item, then press `t` when you have the post you want selected to get the tools menu.
