### ISSUE TITLE
Mathjax support

### ISSUE THREAD

**Issue by cellio** [codidact/qpixel#65]
It's been pointed out to me that the Speculative Science site (most immediately), and math/science sites in general, will need support for math.  (I know we've discussed this, but I don't remember if we reached any conclusions.)  Speculative Science wants to import data that already uses Mathjax, and other sites might also import such content from SE, so it will probably be easiest if we support Mathjax specifically rather than picking some other tool and then having to deal with conversion.

**Comment by ArtOfCode-** [comment]
Completed
