### ISSUE TITLE
Add some indication, after a user clicks "Post" for a comment, that it's being worked on

### ISSUE THREAD

**Issue by ghost** [codidact/qpixel#66]
When a user leaves a comment on a post, the workflow includes typing up the comment and then clicking the "Post" button next to the "Your comment" field.

However, upon clicking "Post", there is no clear indication that the comment is being posted. Especially if the user is on a high-latency connection, there can be a noticable delay during which there is no indication that anything is happening.

I propose that, **when clicking "Post", something visible in the UI indicates to the user that the comment is in the process of being posted.** I don't have an exact suggestion for how to indicate that; it could be a donut spinner, animated dots, or simply changing the button text to "Posting" while disabling the button for the duration, or something else.

**Comment by galegosimpatico** [comment]
@1ec2466 you might have felt it different through September.

**Comment by cellio** [comment]
I just tested this on a dev server with a throttled network, and we now do the following on comment submission:

- gray out the button
- change the mouse cursor

I think this change probably came with threaded comments a while back -- not sure.
