### ISSUE TITLE
Unable to upload picture from profile

### ISSUE THREAD

**Issue by b-Istiak-s** [codidact/qpixel#672]
Visit https://meta.codidact.com/users/edit/profile .Then, try to upload any image from that field. But, picture modal won't be open. Seems like profile page is unable to fetch JavaScript of post.

**Comment by kevinmmansour** [comment]
I could update my profile photo without any problems, Windows 10, Firefox 92.

**Comment by Istiakshovon** [comment]
Try to upload a image in description box (where your bio is included)

**Comment by kevinmmansour** [comment]
Oh, yes, it doesn't work.

**Comment by cellio** [comment]
I assume that whatever we do for posts we could do for the "about" block?  (Is that a post under the hood?)

**Comment by Istiakshovon** [comment]
>whatever we do for posts we could do for the "about" block?

As far as I know, we are currently doing the same for "about" either. But the body field is in post page. That's why most of JS code in posts.js. I think profile page is unable to fetch that JS file. Even, the modal is coming from TS (CoDesign) I don't know why it doesn't work properly.
