### ISSUE TITLE
Unable to visit user list in writing

### ISSUE THREAD

**Issue by b-Istiak-s** [codidact/qpixel#673]
Go to writing CD in mobile. Then logout. Then visit user list https://writing.codidact.com/users

500 error. Not sure if it happens in PC. For now, i have faced the problem in mobile (in chrome browser)

**Comment by MoshiKoi** [comment]
I'm facing the same issue, even while logged in

**Comment by cellio** [comment]
Worked for me just now but with a *lot* of lag.  (3373ms load time.)  I just checked on Cooking and there wasn't as much lag, but the page loaded more slowly than category pages.  (I don't know if that's normal.)

**Comment by Istiakshovon** [comment]
Obviously that's not normal. Something is happening in server (I don't have any idea of server so I am not anything about that). 

Rechecked the page again : 

- In laptop (signed out): not working.
- In laptop (signed in): not working.
- I think it's only working for mod

**Comment by cellio** [comment]
I suspect you're right about mods: I just tried in an incognito window (signed out) and got the 500.

9dbf67db-11de-42bc-8d3f-c5538f83cc9b

**Comment by cellio** [comment]
Maybe a data error?  I'm not sure what component to set.  Assigning to @ArtOfCode- for further evaluation.

**Comment by cellio** [comment]
This is still happening for me.  On mobile, when logged in it was *really* slow and finally loaded with broken images; when not logged in it timed out.  On desktop, it loads fine for me whether logged in or out, in Chrome, Firefox, and Brave.

**Comment by ArtOfCode-** [comment]
Getting norepro now

**Comment by cellio** [comment]
Also norepro now @ArtOfCode- .
