### ISSUE TITLE
Bad YouTube link breaks application script

### ISSUE THREAD

**Issue by MoshiKoi** [codidact/qpixel#676]
GitHub Issue for https://powerusers.codidact.com/posts/284346

When there is a bad youtube link in a post, the site's application script throws an error and this breaks the site.

**Comment by cellio** [comment]
I set "area:markdown" on the guess that what we need is some sort of fencing around YT embeds and that those are done via Markdown rendering.  If I'm wildly off, please fix the labels.

**Comment by MoshiKoi** [comment]
Basically only need to change these lines

https://github.com/codidact/qpixel/blob/16a882d62843450bcfe9fd5f6c825d3709b9d3ec/app/assets/javascripts/embed.js#L10-L16

If you notice, if `videoId` is null, then it throws on attempted access of `videoId[1]` Easy fix is to just add videoId to the if statement.
