### ISSUE TITLE
Show reaction usage data

### ISSUE THREAD

**Issue by luap42** [codidact/qpixel#678]
To enable moderators to assess the usage of reactions, which were recently introduced in #553, it is probably a good idea to show the number of times the reaction has been used in the moderator tools (/posts/reactions).

Possible implementations (just ideas):

- as a new column in the main table ("usage")
- as a new table (with columns, such as "usage overall", "usage last week" and "usage last month"?)

Complexity consideration:

adding some frontend markup (column or new table), some level of DB-access (likely all in frontend code), some query complexity -> should be a good easy issue to get along with the QPixel structure

**Comment by cellio** [comment]
The report is there now, but it's a 500 so I guess something in the back end isn't happy yet.

**Comment by ArtOfCode-** [comment]
Where are you seeing the 500, @cellio? I'm getting norepro.

**Comment by cellio** [comment]
Hmm.  I was consistently getting 500s when I left that comment, but it's working for me now (just tried on Meta).  I guess whatever happened was transient?

**Comment by ArtOfCode-** [comment]
Possibly a data error, or possibly fixed by something else without realising. Closing this for now.
