### ISSUE TITLE
Remove "react" control if there are no enabled reactions

### ISSUE THREAD

**Issue by cellio** [codidact/qpixel#679]
Currently on Languages & Linguistics the three default reactions are disabled and there are no new ones.

But the "react" control is still there, creating this confusing interaction:
![screenshot](https://user-images.githubusercontent.com/5557942/135925306-1aa166c9-c42d-475b-b3b2-fe4447f75dc8.png)

We see "mark this answer as...", but there's no menu, and then there's a place to type a comment.  I don't want to experiment on a live site, so I don't know what happens if you type a comment and click the "add reaction" button.

**Comment by cellio** [comment]
I think the logic is similar to "don't show react control if not logged in" (https://github.com/codidact/qpixel/issues/689), which I think was considered easy.  (The PR that fixed it isn't attached, though, so if the answer isn't what was suggested in a comment, it'll require a little more digging.)

**Comment by b-Istiak-s** [comment]
Isn't there possible way to remove reaction from post type. We are checking if [post has reaction](https://github.com/codidact/qpixel/blob/develop/app/views/posts/_expanded.html.erb#L65), like as- react button doesn't show for question but for answers what if we disable reaction for answer ("post_type=answer") also, can't we?

I don't have any Linux distro right now so I can't give it a try :(
