### ISSUE TITLE
"Unread" notifications for new answers stay unread forever?

### ISSUE THREAD

**Issue by mattdm** [codidact/qpixel#68]
**Describe the bug**

I have two "unread" notifications. They don't go away.

**To Reproduce**

I'm not sure if this is reproducible at all, but here's what I did

1. Observe new notifications on https://meta.codidact.com/
2. Click on the inbox and on each notification one by one.
3. Notice that the counter is still "2"
4. Reload the page.
5. Try it again.
6. Notice that the counter is still "2"
7. Click on "See all your notifications"
8. Try it from there.
9. Notice that the counter is still "2"
10. Reload page.
11. Notice that the counter is still "2"

**Expected behavior**

Number of unread items goes down as I click each one, eventually to 0.

**Screenshots**
![image](https://user-images.githubusercontent.com/123367/80984594-0e55cb00-8dfc-11ea-92e1-4ff58f47c52e.png)

**Desktop (please complete the following information):**
 - OS: Fedora Workstation
 - Browser: Firefox
 - Version: 75.0

**Comment by ArtOfCode-** [comment]
Notifications are a little bit temperamental, but these can usually be solved by clicking once on the inbox icon to open it, then again to close it. That should mark all your notifications as read.

**Comment by mattdm** [comment]
They're gone now. I think I did the above but I'm not sure. I'll pay closer attention next time to see if that does it. I agree that this is lower priority than many other things, but having notifications feel accurate and responsive _is_ ultimately important.

**Comment by ArtOfCode-** [comment]
No disagreement there :)

**Comment by sarahmccuan** [comment]
Possibly related, possibly not - the number of unread notifications is not always the same as the actual list of unread notifications.
![image](https://user-images.githubusercontent.com/35535105/87857886-1fd94a00-c8f8-11ea-92fe-1f1a01dfbd0d.png)

**Comment by galegosimpatico** [comment]
> Possibly related, possibly not - the number of unread notifications is not always the same as the actual list of unread notifications.
> ![image](https://user-images.githubusercontent.com/35535105/87857886-1fd94a00-c8f8-11ea-92fe-1f1a01dfbd0d.png)

But that's fixed now, right?

**Comment by ArtOfCode-** [comment]
All of the above has been fixed
