### ISSUE TITLE
no error message when you click react button while not logged in

### ISSUE THREAD

**Issue by b-Istiak-s** [codidact/qpixel#689]
>Failed: You must be logged in to vote. (403)

The above error message shows when you click on upvote or downvote while not logged in. But when you click on react button then nothing shows. We should show error like as vote.

**Comment by cellio** [comment]
Also raised here: https://meta.codidact.com/posts/284506

**Comment by sau226** [comment]
For the record, this was handled in PR #692.

**Comment by cellio** [comment]
Now that we've done this, I'm guessing it'd be easy to also do #679.
