### ISSUE TITLE
On-hover timestamp is missing in edit notices

### ISSUE THREAD

**Issue by cellio** [codidact/qpixel#694]
Reported in a comment here: https://meta.codidact.com/posts/283571/283572#answer-283572

Also https://meta.codidact.com/posts/284764

If you hover over the "edited X days ago" notice on a post that has been edited([example](https://meta.codidact.com/posts/283569), the timestamp isn't displayed like on other dates.  I assume we missed one and the same code that works for other dates would work here too.

**Comment by b-Istiak-s** [comment]
I believe it is happening right here (https://github.com/codidact/qpixel/blob/develop/app/views/posts/_expanded.html.erb#L186-L192)
