### ISSUE TITLE
Renaming a tag causes misleading post history

### ISSUE THREAD

**Issue by cellio** [codidact/qpixel#697]
https://meta.codidact.com/posts/283823

A third-party edit added tag A.  Later, someone renamed A to B, and now the post history shows that user as having added tag B.  That's not what happened, though.

Can post history record the state at the time of the edit?   Or at least show the original tag along with the current name, since tag renames also don't show up in the history of posts that use those tags?

**Comment by ArtOfCode-** [comment]
I'm going to decline this one - excessively complicated for minimal gain. I can see there's some confusion there, but displaying state at time-of-edit or just original tag would both require us to create and keep track of tag history, which we don't do at all at the moment, and would complicate the view code.
