### ISSUE TITLE
lots of bug tag while editing

### ISSUE THREAD

**Issue by b-Istiak-s** [codidact/qpixel#705]
I believe it's not the only problem with tag. As far as I know, we are fetching tag wrong that's why we are facing all these things. 

In the page : https://meta.codidact.com/posts/283614/edit I could see 3 bugs tag but after saving or in posts page there's only one bug tag. So the bug is only in edit page.

**Comment by cellio** [comment]
I think https://github.com/codidact/qpixel/pull/1458 and https://github.com/codidact/qpixel/pull/1463 fixed most of the weird behavior we were seeing with tags in the editor.  I can't reproduce duplicate tags now in a dev environment.
