### ISSUE TITLE
Automatically generated reactions keep on being generated

### ISSUE THREAD

**Issue by MoshiKoi** [codidact/qpixel#716]
Here is a web capture of [the reactions on the dev server](https://a.dev.codidact.org/posts/reactions)

<details>

![Web capture_29-10-2021_95457_a dev codidact org](https://user-images.githubusercontent.com/54333972/139474133-879e6cc2-f279-4c3e-a2ba-afc34bf822a4.jpeg)

</details>

As you can see, there are way too many "Works for me", "Outdated", and "Dangerous" reactions. The same is happening on Languages and Linguistics. I am not sure when it happened, but I didn't edit any of them so it seems to have occurred on its own.

**Comment by sau226** [comment]
Should be resolved by #717, but looks like deletion requires a further code change/rails command/manual mass delete
