### ISSUE TITLE
Edit history diffs don't show the actual diffs

### ISSUE THREAD

**Issue by cellio** [codidact/qpixel#72]
This screenshot is from this edit history: https://writing.codidact.com/posts/38328/history

![Screen Shot 2020-05-07 at 9 44 20 AM](https://user-images.githubusercontent.com/5557942/81301864-9c71c180-9047-11ea-8e84-61e714a75092.png)

Can you find the change?  I couldn't until I scanned both in parallel looking for changes in word wrap and narrowing from there.

It's the URL in the first paragraph.

**Comment by ArtOfCode-** [comment]
[status-bydesign] right at the moment, I haven't added proper diff detection yet. It's on the list to do, but not a high priority at the moment.

**Comment by galegosimpatico** [comment]
I can use the site with ease. For my use, differences get highlighted by getting underlined.

Maybe already fixed?

**Comment by galegosimpatico** [comment]
Still. Can't. Reproduce.

<img width="1110" alt="Screenshot 2020-08-29 at 01 14 05" src="https://user-images.githubusercontent.com/53513496/91621868-fa2e6e80-e994-11ea-91fa-e3b7d80e8331.png">

[Use Opera][0].

[0]: https://youtu.be/nXAzctXGEeg?t=2034

**Comment by cellio** [comment]
That's a diff in the history.  I don't know why that one is being overly diff-y, reporting the whole thing when it looks like it's just a URL.  Here's a more normal (in my experience) history entry:

![Screen Shot 2020-08-28 at 7 30 00 PM](https://user-images.githubusercontent.com/5557942/91622390-ecf98b80-e964-11ea-992b-05dea24265f9.png)

(From https://meta.codidact.com/posts/277208/history.)

Compare that to a pending edit, one that hasn't been made yet, reached through the "review edit" button on a post:

![Screen Shot 2020-08-28 at 7 27 48 PM](https://user-images.githubusercontent.com/5557942/91622425-0a2e5a00-e965-11ea-8bbd-a76f6496f93a.png)

(From https://software.codidact.com/posts/suggested-edit/107 -- there's more, but that's as much as I could fit in a screencap.)

There is no highlighting anywhere in the latter, just a block of pink for the old and a block of green for the new.

**Comment by ArtOfCode-** [comment]
Fixed
