### ISSUE TITLE
Reactions reports is broken (500)

### ISSUE THREAD

**Issue by MoshiKoi** [codidact/qpixel#722]
The mod view for reactions statistics at https://languages.codidact.com/reports/reactions gives a 500 server error

**Comment by cellio** [comment]
Where did you find that URL?  The link for the "reactions" mod tool is https://languages.codidact.com/posts/reactions.

**Comment by MoshiKoi** [comment]
Mod > Reports > Reactions

![image](https://user-images.githubusercontent.com/54333972/141047294-905cd769-b241-46c8-bd6c-61e9b0485060.png)
![image](https://user-images.githubusercontent.com/54333972/141047333-faaf6e1e-9379-465d-ae5a-8e2d9c7d9168.png)

**Comment by cellio** [comment]
Oh, *those* reports!  Thanks; I forgot reactions were in there.  Well, half-there, it looks like.

**Comment by ArtOfCode-** [comment]
Should be fixed by 4bb1116025d01e599f13323ae886400f8bc33161
