### ISSUE TITLE
Donations form: add optional name for public acknowledgement

### ISSUE THREAD

**Issue by cellio** [codidact/qpixel#729]
We would like to be able to publicly thank and acknowledge donors.  Some donors will want to remain anonymous, so this has to be optional.  We should allow people to choose the name that appears, since "current user name on Codidact" might not be what people want.

My proposal: after the donation is processed, show a "thanks" page (we might do this already; can't remember) and include something like: "If you would like to be publicly thanked on our web site, please provide the name you want us to use (amount is private)" and a textbox.  Log the answer such that an admin can get all the new names in reverse-chronological order (so a human can go back to "where we left off" from the last update).  If Stripe allows us to record a note with a transaction, we could do it there and wouldn't need to record in and query from our database.

Human review is important in case there are any problems in the submitted names, so I am imagining a manual update process, not an automatic one that adds submitted names directly to the public donors list.

I am suggesting that we ask for this *after* the donation, not on the same page with the credit card number, to avoid any confusion where people might think they need to use their legal (credit card) name.  Payment with your credit card and submitting a name for public thanks are separate transactions, so let's separate them.

When https://github.com/codidact/landing-page/issues/89 is addressed, "our web site" should be a link to that page.

**Comment by cellio** [comment]
I'm marking this high priority because the sooner we start collecting the information with the donations, the less backfill we'll have to sort through later.  I realize that until we have the public page, we're not posting those thanks yet.

**Comment by ArtOfCode-** [comment]
Done as of today, pending deploy
