### ISSUE TITLE
Deleted answers are shown to anonymous users (but not logged-in ones without curate)

### ISSUE THREAD

**Issue by cellio** [codidact/qpixel#730]
https://meta.codidact.com/posts/284937

Like it says on the tin: we're currently showing deleted answers when not logged in.  Logged-in users without Curate cannot see them (I confirmed this with a sock), but logged-out users can.  Possibly introduced in https://github.com/codidact/qpixel/commit/19ed348a4e6b4aed6ea7afb52ae9256b892966bc, according to the report.

**Comment by ArtOfCode-** [comment]
Confirmed fixed.
