### ISSUE TITLE
No image for deleted user in history

### ISSUE THREAD

**Issue by b-Istiak-s** [codidact/qpixel#732]
> https://linux.codidact.com/posts/282548/history

A person (me :P ) had edited that post currently the user is no more (the account was deleted). We are showing an image for deleted user (<i class="fas fa-user-times"></i>), it's not available in history.

**Comment by cellio** [comment]
Presumably, we do whatever we do for posts to identify that image.  If I'm wrong and this isn't easy, please update the labels.

**Comment by cellio** [comment]
Still getting a bad-image marker after this was deployed:

![Screen Shot 2022-04-11 at 9 03 55 PM](https://user-images.githubusercontent.com/5557942/162857959-12664f10-01b2-47f0-b230-20de58a044d4.png)
