### ISSUE TITLE
No word wrap for initial revision in post history

### ISSUE THREAD

**Issue by MoshiKoi** [codidact/qpixel#733]
Basically the title. The initial revision of a post in the post history has no word wrapping, so the text goes way off the screen.

![Screenshot of the text going off screen](https://user-images.githubusercontent.com/54333972/143406469-8172468a-e738-4011-93fe-cf1da25e5819.png)

**Comment by b-Istiak-s** [comment]
link?

**Comment by cellio** [comment]
Here's an example: https://meta.codidact.com/posts/284937/history
