### ISSUE TITLE
It's possible to visit deleted post's history if you aren't logged in

### ISSUE THREAD

**Issue by b-Istiak-s** [codidact/qpixel#736]
https://software.codidact.com/posts/284206/history

not sure if it's visible to who is logged in also. But I could visit the history not post while not logged in. A similar problem  (https://meta.codidact.com/posts/284937) was solved recently, but I can't find that right now...

**Comment by cellio** [comment]
The related issue (fixed) is https://github.com/codidact/qpixel/issues/730.  We probably need to do the same check for history pages that we do for the post itself.  I confirmed that the entire post is visible via its history to logged-out users.
