### ISSUE TITLE
Warn that replying to an escalated flag replies to the flagger, not the escalating mod

### ISSUE THREAD

**Issue by luap42** [codidact/qpixel#742]
I just handled my first flag escalation and added a short reply to the action. From the form, I'd have presumed, that the reply goes to the *moderator who escalated the flag*, but instead the reply goes to the user who flagged initially. While this will hopefully only cause some mild confusions about why I mentioned an "escalation" in my reply, there should be a warning shown that you are replying to the flagger, not the mod, because otherwise staff might accidentally leak sensitive information intended for the mod.

Suggested text:

> Attention: The reply to the flag will be shown to the flagger, not the mod escalating this flag. Do not share sensitive, mod-only information.

**Comment by cellio** [comment]
I'm assuming this isn't too hard?  I didn't want to presume; @luap42 please change the complexity label as appropriate.
