### ISSUE TITLE
Make the donation functionality optional in QPixel, in particular do not require a Stripe API key for running

### ISSUE THREAD

**Issue by Trilarion** [codidact/qpixel#747]
**Is your feature request related to a problem? Please describe.**

I wanted to setup a QPixel instance but it keeps erroring and asking for a Stripe API key. For more details see [here](https://collab.codidact.org/posts/285410).

**Describe the solution you'd like**

It should be possible to run QPixel without the donation functionality. In particular QPixel should not require a Stripe API key. For example, the donation functionality could be a configured in the QPixel config with a general on/off toggle and optional a Stripe API key.

**Describe alternatives you've considered**

I could probably get a Stripe API key, but I don't want that.

**Additional context**

This here is the feature request to make it optional. This https://collab.codidact.org/posts/285410 is more like the bug report.

**Comment by cellio** [comment]
There is a place in the admin dashboard (`admin/settings/global`) for global site settings.  There's currently nothing there (or at least I can't see anything).  This seems like the right place to hook it in.

**Comment by b-Istiak-s** [comment]
Perhaps we should have a test API. (I believe Stripe provides test API also)

**Comment by Trilarion** [comment]
I wonder how the CI  from [circlci](https://circleci.com/gh/codidact/qpixel) is able to run all the tests? It seems that currently all tests are passed there and it has a configuration file [here](https://github.com/codidact/qpixel/blob/develop/.circleci/config.yml). How does circleci deal with the donation Stripe API key?

Documentation from [Stripe](https://stripe.com/docs/keys) suggests that there might be test API keys available and they probably should be used to run the tests.

But I would still prefer if in production the donation part can be completely optional.
