### ISSUE TITLE
Posting restrictions are checked only after submitting a post

### ISSUE THREAD

**Issue by cellio** [codidact/qpixel#75]
On the dev server, I tried to post in a category where I apparently don't have sufficient trust level to post.  I was able to compose my post without being alerted to the impending problem:

![Screen Shot 2020-05-08 at 3 40 17 PM](https://user-images.githubusercontent.com/5557942/81442898-70873680-9142-11ea-9ffa-569fe17f97e7.png)

When I clicked the "post" button I got the following error message:

![Screen Shot 2020-05-08 at 3 40 32 PM](https://user-images.githubusercontent.com/5557942/81442920-7a109e80-9142-11ea-93fc-f0942c7942f6.png)

It's good that it left me in the editor with my stuff, so if I wanted to save my post for later I could.  (It's not like "go get more trust and try again in a few minutes" is going to work most of the time. :-) )  But it would be better if we could intercept this case earlier.  *Ideally* we'd catch it at the time you click the "post" button and not offer you the post editor, but if that's hard, we should at least show a "you aren't actually going to be able to post this because..." message in the original composition window.

The (eventual) Codidact use case calls for button click (when not allowed) to directly emit a "no can do" message, meaning it wouldn't even take you to the "create post" page.  I realize we might not get there in one step; for QPixel's current stage, complaining any time before you've written and submitted a post is good.

**Comment by ArtOfCode-** [comment]
Fixed by 699c8f1eafa0a4c9b64f690241008c723ba15791
