### ISSUE TITLE
Enable comment flagging

### ISSUE THREAD

**Issue by Mithrandir24601** [codidact/qpixel#76]
As the userbase grows, it's only a matter of time before we get to the point where someone's going to write a rude (etc.) comment.

While a mod can be alerted and deal with it, it would be more efficient (and easier to alert a mod) if such problematic comments could be dealt with via flags. A such, comment flags would be a useful feature.

Alternatively, flagging the post the comment is under, detailing that the problem is in the comments is doable and works, although is (a small amount) more effort on the part of both the flagger and the mod(s) reading the flag.

**Comment by cellio** [comment]
Use case: https://github.com/codidact/feature-development/blob/master/scoped/flag/flag-comment.md

**Comment by cellio** [comment]
Flag text available on GH: https://github.com/codidact/docs/blob/master/User-Help/CodidactCommentFlagTexts.md

**Comment by luap42** [comment]
This is likely one of the more complex requests. Requires changes to the flagging system, including finding a good way to have *one system* for posts and comments. 

Maybe better to defer until the comment revamp?

**Comment by cellio** [comment]
Depends on https://github.com/codidact/qpixel/issues/237.

**Comment by cellio** [comment]
Fixed with https://github.com/codidact/qpixel/commit/a8a933b77a91494a4bec314b1628e05b3990fe89.
