### ISSUE TITLE
Don't notify me of my own actions

### ISSUE THREAD

**Issue by cellio** [codidact/qpixel#77]
I just posted an answer to a question I had asked previously -- and got a notification of a new answer.  This has happened before, but if I reported it I can't find it now.  This is a low-level nuisance, not critical, but if it's easy it would be nice to catch this case and not light up the notification widget with old news.

**Comment by cbortz** [comment]
@ArtOfCode- It looks like this may have already been resolved in ba6f9ab6e08b721aacad60b780515b55ded944ab, specifically in [L23 - L26](https://github.com/codidact/qpixel/blob/ba6f9ab6e08b721aacad60b780515b55ded944ab/app/controllers/answers_controller.rb#L23:L26)

**Comment by galegosimpatico** [comment]
> ArtOfCode- It looks like this may have already been resolved in [ba6f9ab](https://github.com/codidact/qpixel/commit/ba6f9ab6e08b721aacad60b780515b55ded944ab), specifically in [L23 - L26](https://github.com/codidact/qpixel/blob/ba6f9ab6e08b721aacad60b780515b55ded944ab/app/controllers/answers_controller.rb#L23:L26)

came here to read it beco I was suspecting the same (but didn't investigate thoroughly)
