### ISSUE TITLE
Comment count includes deleted comments (user confusion)

### ISSUE THREAD

**Issue by cellio** [codidact/qpixel#783]
https://meta.codidact.com/posts/285825

A thread link includes the number of comments in the thread.  This number includes all comments, but should not include deleted comments for people who can't see them.  The linked post includes screenshots where the thread said 4 comments, the user expanded the thread, and it shows one comment + "showing 4 of 4 comments".  Only on the full thread page do we show "skipping 3 deleted comments".

Ideally, we would show a number that reflects what *you* can see, and include those "skipped deleted" steps in the in-page view. For people who can see deleted comments (mods/admins), we would either show the true number or show something like "1 (+ 3 deleted)".

**Comment by MoshiKoi** [comment]
Is this still an issue? #875 fixed this in favor of including the "skipping 3 deleted comments" message on the in-page view.
