### ISSUE TITLE
Site logo is squished horizontally on iPhone/Safari

### ISSUE THREAD

**Issue by cellio** [codidact/qpixel#80]
This was reported to me by a casual user (someone I shared a link with but who doesn't have an account).  In Safari on iPhone 8 running iOS 13.31, the user sees a site logo that is horizontally squished:

![iphone](https://user-images.githubusercontent.com/5557942/81629787-0258a300-93d2-11ea-9c2f-7f4c5c7b458f.png)

I don't have an iPhone to test on.  This doesn't happen on my Android phone.

Is there something about how the buttons and hamburger (don't) flow -- are they somehow grabbing most of the width and the logo gets what's left?  I'm not clear why that should be platform-dependent, though.

**Comment by manassehkatz** [comment]
I use browserstack.com (single subscription, not a team, so I can't share, sorry) to test iOs (and other stuff) and have confirmed this happens with writing and photo as well. The logos are fine when the screen is rotated (i.e., landscape).

**Comment by galegosimpatico** [comment]
me norepro for iphon 6 ios 12.4.8 outdoors nor writing nor photo

**Comment by kevinmmansour** [comment]
This is what I get in iPhone 8 - iOS 13.7 - Safari.

![Preview](https://user-images.githubusercontent.com/71846550/127616449-48809d2d-0348-4ac7-bcbb-bbb53e4be2eb.png)

**Comment by ArtOfCode-** [comment]
Aye, pretty sure this got fixed somewhere and we just missed it.
