### ISSUE TITLE
Ability to choose multiple post types for a reaction

### ISSUE THREAD

**Issue by MoshiKoi** [codidact/qpixel#808]
Currently, reactions are limited to either belonging to all or only one post type. This is inconvenient for when one wants to have a reaction that applies to more than one post type, but doesn't apply to *all* post types (the example that prompted this was the [citations needed] reaction on L&L, which I would like to apply to both answers and articles, but not questions)

**Comment by cellio** [comment]
The reaction model itself enforces "only one", so this isn't just a matter of changing a selector to a multi-selector in the UI.  (Hence the "ruby" tag instead of the "html" tag.)

**Comment by MoshiKoi** [comment]
[From the discord some time back (June 29th)](https://discord.com/channels/709567671087136829/709570728822833153/991736099003174972)

> Database reason. Querying for one v. all is way easier and faster than querying for many (one column v. one reference table)

Unless anything has changed since then, this can probably be closed as not planned
