### ISSUE TITLE
"Push to network" checkbox is shown to mods when editing help (but only admins can do this)

### ISSUE THREAD

**Issue by cellio** [codidact/qpixel#809]
When editing a help topic, there's a checkbox for "push to network" to propagate a change.  Only network admins can actually do this, but a moderator informed me that moderators can see it too.  Testing on a dev server confirmed that a moderator checking that box doesn't actually propagate the change, but it would be better for the UI to not offer it in the first place, just like we don't show admin tools to non-admins.

Can we put an admin check around the display of that part of the help editor?

**Comment by MoshiKoi** [comment]
Has this been fixed? The PR that says it fixes it has been merged, but this is still open.
