### ISSUE TITLE
Tags list

### ISSUE THREAD

**Issue by cellio** [codidact/qpixel#83]
Add a page showing all tags in the current category's tag set.  "Tags" link goes in the category banner, with "Posts", not in the top bar.  We don't need a global list of all tags in all tag sets.

Wireframe for a simple presentation: 
https://www.figma.com/file/IVapqyDbGUkfciwL4l500f/tags-list?node-id=0%3A1

I suggest a medium priority.  The sites obviously work without this, and people can search *by* tag, but it's only a matter of time before somebody notices that you can't *browse* tags.  I'm surprised it hasn't come up yet on Writing.  This should come after data import and mathjax and a couple other things because those are actual blockers, but let's not lose track of it.

**Comment by galegosimpatico** [comment]
I don't understand anything. Is this finished?

**Comment by cellio** [comment]
Oh yeah, this is there -- example: https://meta.codidact.com/categories/3/tags

I guess closing this issue got missed.
