### ISSUE TITLE
Search instructions in search-slide

### ISSUE THREAD

**Issue by Taeir** [codidact/qpixel#830]
**Is your feature request related to a problem? Please describe.**
A lot of powerful features are available in the search, as explained on https://meta.codidact.com/help/search. However, the user does not get presented with these unless if they actually open the search page.

**Describe the solution you'd like**
StackOverflow solves this by showing a very short version of useful search features in the dropdown when you click on the search bar.
![Display as shown by StackOverflow](https://user-images.githubusercontent.com/668952/184509698-a1e31329-8a3b-4b8c-a521-89a329931821.png)

Perhaps we could do something similar.

**Describe alternatives you've considered**
`-`

**Additional context**
Adding this is not hard, since the search is already a slide there is a panel where this information can be added. The question is how similar it can/should be.

**Comment by MoshiKoi** [comment]
> A lot of powerful features are available in the search, as explained on https://meta.codidact.com/help/searching.

You mean https://meta.codidact.com/help/search, right? If there is a link to that incorrect url (it returns a 500), could you tell us where you found it?

**Comment by Taeir** [comment]
@MoshiKoi indeed, I meant /help/search, I updated it in my comment. Sorry for the confusion
