### ISSUE TITLE
ERROR: Service 'uwsgi' failed to build : Build failed

### ISSUE THREAD

**Issue by cgaz90** [codidact/qpixel#832]
**Describe the bug**
When attempting to pull images to build uwsgi from docker-compose a mirror required is now 404'ing

#7 2.663 2022-08-14 11:51:58 (6.99 MB/s) - ‘node-v12.18.3-linux-x64.tar.xz’ saved [14700900/14700900]
#7 2.663
#7 5.696 --2022-08-14 11:52:01--  https://imagemagick.org/download/binaries/magick
#7 5.706 Resolving imagemagick.org (imagemagick.org)... 50.251.58.13
#7 5.844 Connecting to imagemagick.org (imagemagick.org)|50.251.58.13|:443... connected.
#7 6.182 HTTP request sent, awaiting response... 302 Found
#7 6.289 Location: https://download.imagemagick.org/archive/binaries/magick [following]
#7 6.290 --2022-08-14 11:52:02--  https://download.imagemagick.org/archive/binaries/magick
#7 6.290 Resolving download.imagemagick.org (download.imagemagick.org)... 50.251.58.13
#7 6.376 Connecting to download.imagemagick.org (download.imagemagick.org)|50.251.58.13|:443... connected.
#7 6.694 HTTP request sent, awaiting response... 404 Not Found
#7 6.792 2022-08-14 11:52:02 ERROR 404: Not Found.
#7 6.792
------
executor failed running [/bin/sh -c wget https://nodejs.org/dist/v12.18.3/node-v12.18.3-linux-x64.tar.xz &&     tar xf node-v12.18.3-linux-x64.tar.xz &&     wget https://imagemagick.org/download/binaries/magick &&     chmod +x magick &&     mv magick /usr/local/bin/magick]: exit code: 8
ERROR: Service 'uwsgi' failed to build : Build failed

**To Reproduce**
1. Docker-compose up

**Expected behavior**
It should complete and build the the uwsgi container without error

**Desktop (please complete the following information):**
 - OS: Windows 10 
 - Latest version of docker for windows and docker-compose using WSL

**Additional context**
Same problem on my Ubuntu docker server

**Comment by Taeir** [comment]
This is fixed in PR #820, but that has unfortunately not been merged yet. If you merge those changes into your branch it should work (and I recommend also merging in #822, otherwise the instance you get in docker will be quite broken).

**Comment by cellio** [comment]
I've just merged PR #820 .

**Comment by cgaz90** [comment]
yes, those merges fixed this issue, thanks
