### ISSUE TITLE
Suggested edits

### ISSUE THREAD

**Issue by cellio** [codidact/qpixel#84]
At a certain rep/privilege level you can edit directly.  People below that level can suggest edits.

The MVP spec is pretty sparing: a post indicates that there's an edit pending, and the author gets notified, but there's nothing like review queues.  (We might consider a single page of links to all posts with pending edits, linked in the right column for people who can approve them, but even that is more than we specified.)  The backend is probably more complicated because we have to store that pending edit, prevent other pending edits while one's in flight, and do the notifications.  I don't have a sense of how hard this is but I suspect there's some significant work here.

Wireframe for suggested edit, which is for the full MVP but could devolve, for now, to just the current edit interface plus the notice at the top about it being a suggestion if it will be: https://www.figma.com/file/4oiLQnt5Au9p54fUyQWsHX/edit?node-id=0%3A1

Wireframe for reviewing a suggested edit: https://www.figma.com/file/QdUzSRBb6thmjpynDTvJUS/review-suggested-edit?node-id=0%3A1

**Comment by luap42** [comment]
Yeah. I’m working on it, but I don’t have that much time right now.

**Comment by cellio** [comment]
Sorry @luap42 -- lost track of that, so when I didn't see an issue tracking it I created one.  Not meant as a nag, just getting info linked together (like wireframes).

**Comment by luap42** [comment]
No problem. That wasn't how I meant it. It's more a notice for others not to start working on it.
