### ISSUE TITLE
Indicate that, and when, a post was edited

### ISSUE THREAD

**Issue by cellio** [codidact/qpixel#87]
Feature request from Meta: https://meta.codidact.com/questions/74966

If a post has been edited, showing the timestamp of the most recent edit will help people figure out what changed when a post gets bumped.  Right now you have to check the history for the question and each answer until you find it.

**Comment by galegosimpatico** [comment]
related: schema inconsistency 
* never edited post woud have creation date and update date in UTC while last activity date in local time .
* edited post would have creation date and update and activity all in UTC

**Comment by cellio** [comment]
PR was merged; closing.
