### ISSUE TITLE
Able to see who declined a flag.

### ISSUE THREAD

**Issue by not-a-ethan** [codidact/qpixel#913]
**Describe the bug**
When you go to your flags pages (https://a.dev.codidact.org/users/id/flags) you can see who handled the flags including who declined flags even when you are not a mod.

**To Reproduce**
1. Raise a flag and get it declined
2. Go to https://a.dev.codidact.org/users/id/flags and look who declined the flag

**Expected behavior**
It would only show what the decision on the flag was and not who handled it.

**Screenshots** 
![image](https://user-images.githubusercontent.com/92686703/202185444-c89ba806-7430-4d4b-950c-2e315de17183.png)

**Desktop (please complete the following information):**
 - OS: Chrome and windowns
 - Browser chrome and Firefox dev edition.
 - Version 106.0.5249.112 of Chrome

**Comment by not-a-ethan** [comment]
@cellio Can you change the complexity to easy since it looks like you only need to delete lines 25-27 to get rid of who handled the flag? ([This file](https://github.com/codidact/qpixel/blob/077302476e83d9100409eac0f2d8cba7c5ef0682/app/views/flags/_handled.html.erb))

**Comment by cellio** [comment]
@not-a-ethan done.

**Comment by not-a-ethan** [comment]
@cellio Didn't think of that. It seems like that would happen though. I think the condition would be `current_user.privilege? 'mod'` thought I am not 100% sure.

**Comment by trichoplax** [comment]
I'm going to pick this one up as a `complexity:easy` `area:ruby` issue to get me used to the language.

**Comment by trichoplax** [comment]
I'm going to make 2 assumptions:

1. The same should apply to flags marked helpful as to declined flags
2. Both admins and mods should be able to see who processed a flag (other users should not, for helpful or declined flags)

**Comment by cellio** [comment]
@trichoplax both correct, thanks.

**Comment by trichoplax** [comment]
I'm also going to assume that when a flag is escalated to the admin team the name of the admin that processed it is only visible to other admins, not to mods. I'm not so sure of this one though - let me know if it should be visible to mods too.

**Comment by cellio** [comment]
> I'm also going to assume that when a flag is escalated to the admin team the name of the admin that processed it is only visible to other admins, not to mods. I'm not so sure of this one though - let me know if it should be visible to mods too.

Hadn't really thought about that one before.  I think it's fair for mods to know who is resolving flags on their communities, including admins.  An escalation is basically passing a flag along for handling, so I think people who can see flag resolutions should be able to see this flag resolution.

**Comment by trichoplax** [comment]
> I think the condition would be `current_user.privilege? 'mod'` thought I am not 100% sure.

@not-a-ethan I went with `current_user.is_moderator` which includes the check you suggested as one of several, so hopefully that covers all relevant cases:

```ruby
  def is_moderator
    is_global_moderator || community_user&.is_moderator || is_admin || community_user&.privilege?('mod') || false
  end
```

Let me know if not.

**Comment by not-a-ethan** [comment]
@trichoplax Looks right but does that need to be in a return statement (the second line)? Dont now ruby

**Comment by trichoplax** [comment]
@not-a-ethan I don't know Ruby either (I picked this up to learn). In Ruby the value of the last expression in a function is implicitly returned.

There is a `return` keyword in Ruby, but it is only used for early return, or to suppress returning the value of the last expression where necessary.

**Comment by trichoplax** [comment]
(Just to clarify: I didn't write that function - it already existed and I just called it from the handled flags template.)
