### ISSUE TITLE
Clicking on inbox icon or communities button doesn't work; clicking outside them but in the container does

### ISSUE THREAD

**Issue by cellio** [codidact/qpixel#923]
I thought we had an issue for [this problem](https://meta.codidact.com/posts/287466) already, but I can't find it.  Clicking on these two items in the top bar doesn't work, but clicking in the whitespace around the icon does.

There's a lot of debugging information in a comment thread: 
https://meta.codidact.com/comments/thread/6993 .  It appears that the problem is with nested image elements on in-page panel:

- mod menu and help have text and no images and work (also navigate to new page so maybe a red herring)
- search has text and an image; clicking on the text works but clicking on the image does not (in-page panel)
- inbox and community switcher have image, no text, and clicking on the image doesn't work (in-page panel)
- dashboard and mobile sign-on have image, no text, and clicking works (goes to a new page)

Conclusion: if clicking on one of these images triggers javascript (to show an in-page panel), it doesn't work.  If clicking doesn't involve javascript (plain old link-following), it works.

**Comment by cellio** [comment]
I'm marking this high priority because it's a user frustration that especially hits new users (who haven't learned the workaround yet).

**Comment by trichoplax** [comment]
I believe the previous issue you were looking for is https://github.com/codidact/co-design/issues/72 (which might be difficult to search for because it is closed - I found it thanks to a link from the Meta post: https://meta.codidact.com/comments/thread/7007#comment-18865 ).

It appears to have been closed when the change was merged into the develop branch, but the bug still exists until the develop branch is deployed. Should that issue be reopened until the fix is deployed?

**Comment by cellio** [comment]
We've deployed `develop` since then, but the possible missing link is that co-design changes need to be propagated to qpixel and I'm not sure that's happened.  So closed in co-design is correct, but it's still a bug in qpixel until we pull that in.  This bug can serve for that.  (If it *was* pulled in and it's broken anyway, then we might need to reopen the co-design bug.  But the first thing to check is how far through the pipeline that fix has made it.)

**Comment by trichoplax** [comment]
Ah I see. Last time I checked, the fixed code was not showing in the browser. I've just checked again now, and the browser (Firefox on my machine) is still using the old code. So it does sound like the propagation you mention is still yet to happen.

Thanks for explaining the two different places for issues - I can see why it makes sense to leave the other issue closed now.

**Comment by trichoplax** [comment]
For prioritisation: this has been raised again as issue #965.

**Comment by cellio** [comment]
Co-design half of this issue: https://github.com/codidact/co-design/issues/80 .

**Comment by trichoplax** [comment]
Closing as I noticed this is now fixed in Co-Design by https://github.com/codidact/co-design/pull/83 and pulled into QPixel by #1035 and is now live.

**Comment by trichoplax** [comment]
Looks like this can be closed as I notice this is now fixed in Co-Design by https://github.com/codidact/co-design/pull/83 and pulled into QPixel by #1035 and is now live.
