### ISSUE TITLE
URLs for profile sub-pages should be consistent

### ISSUE THREAD

**Issue by cellio** [codidact/qpixel#928]
When viewing a profile, the URL includes the user number.  That's true for all of the sub-pages too (vote-summary, activity, etc) -- *except* preferences, which has the URL user/me/preferences.  The "me" shortcut is useful to have, for example so that help topics or answers to support questions can use URLs that work for everybody, but I expected that to be a "translation", not the real URL.  I suspect we're doing some extra, unnecessary processing here by baking the "me" into a URL reached via site navigation.

**Comment by cellio** [comment]
Actually, it's more complicated: the user number is in the URLs that are publicly available and not in the ones that you can only see for yourself when logged in, _but_ the other two don't have "me", but maybe this isn't something we care about.  Probably the last three (account, edit, preferences) should either all have or not have "me", but I don't know if it's worth disturbing anything.

**Comment by ArtOfCode-** [comment]
The `/users/me` shortcut only exists for routes that get called in the background (like for preferences), not for any user-visible URLs, AFAIK.

**Comment by cellio** [comment]
> The `/users/me` shortcut only exists for routes that get called in the background (like for preferences), not for any user-visible URLs, AFAIK.

The `me` URL is visible if you navigate to the preferences tab on your profile.  The other two "only for you" tabs (account and edit) have URLs with neither the user number nor `me` (e.g. just `users/edit`).
