### ISSUE TITLE
Give search box focus when you open the panel

### ISSUE THREAD

**Issue by cellio** [codidact/qpixel#937]
https://meta.codidact.com/posts/287030

When you click on "search", the panel opens and there's a textbox.  But you can't start typing your query yet; first you have to click into the box.  (From the keyboard, it's not a single tab, either.)  Can we give the textbox focus automatically when you start a search?

**Comment by trichoplax** [comment]
Duplicate of #829 - close this one as that one has more detail?

**Comment by cellio** [comment]
Duplicate.
