### ISSUE TITLE
Support lists in comment markdown

### ISSUE THREAD

**Issue by cellio** [codidact/qpixel#941]
https://meta.codidact.com/posts/287058

Initially comments supported only minimal markdown, but we've expanded that over time; we even have code blocks with syntax highlighting now.   We've been asked to support both bulleted and numbered lists, which seems like a reasonable request given what else we support.  Is this relatively easy?  (Is there an "allow list" for markdown we support and we just need to add a couple things to it?  Or is it more complicated?)

**Comment by trichoplax** [comment]
Consider in parallel with https://github.com/codidact/qpixel/issues/253
