### ISSUE TITLE
Can't revert to a blank profile

### ISSUE THREAD

**Issue by cellio** [codidact/qpixel#945]
https://meta.codidact.com/posts/287128
https://meta.codidact.com/posts/287130

The "about" section of a user profile starts out blank.  If you've edited it and then later want to revert to the blank state, you can't -- the "save" button is disabled.  You should be able to remove content that you added in the first place (without resorting to HTML trickery).

I *suspect* that the "about" block is a post and we have a minimum length for posts.  Can we create an exception for this specific post type and allow a zero-length body?

**Comment by ArtOfCode-** [comment]
It's not a post, but it uses the post editor (because it's Markdown). Separate logic here is fine, it just needs validations adjusted.

**Comment by cellio** [comment]
https://github.com/codidact/qpixel/issues/1092 has more detail, so I'm closing this as a duplicate of it.
