### ISSUE TITLE
Redundant server requests being made when there is no logged in user

### ISSUE THREAD

**Issue by trichoplax** [codidact/qpixel#948]
**Describe the bug**
[Mentioned in Discord](https://discord.com/channels/634104110131445811/635510793961472020/1060295856793862164):

> There's also another subtle issue there that for logged-out users, that AJAX call will be made every time the method is called, because there are no preferences to cache. Should probably fix that too - it's causing non-trivial request load.

This is referring to [the `preferences` function in `qpixel_api.js`](https://github.com/codidact/qpixel/blame/develop/app/assets/javascripts/qpixel_api.js#L179).

**To Reproduce**
~Not applicable.~ Open the network section of a developer window and visit one of the Codidact communities in a fresh browser instance with no logged in user and no localStorage (such as private browsing in Firefox or incognito in Chrome). Filter to show only URLs containing "preferences". There should ideally be no requests but there are often hundreds. [Numbers for a couple of communities can be found in a comment below](https://github.com/codidact/qpixel/issues/948#issuecomment-1375906000)

**Expected behavior**
Preferences should only be requested from the server when there is a logged in user.

**Screenshots**
Not applicable.

**Desktop (please complete the following information):**
**Smartphone (please complete the following information):**
Not operating system related.

**Additional context**
~I have not double checked that this is creating server load. Just raising this based on the Discord comment so it can be looked into.~ Now confirmed - see **To Reproduce** above.

**Comment by cellio** [comment]
Related: https://github.com/codidact/qpixel/issues/947.  If fixing this issue, please fix that one too; it's nearby and small.

**Comment by trichoplax** [comment]
I tested this in a private browsing window (Firefox) so that there would be no logged in user and no localStorage. Viewing a question doesn't appear to make any requests to `/users/me/preferences`, but viewing any Category page makes many. Each visit generally makes the same number of requests for a given Category, seeming to be more requests for Categories that have more posts.

For Code Golf:
- Challenges: 121 requests (or sometimes 122)
- Q&A: 37 requests
- Sandbox: 131 requests
- Meta: 91 requests

For Codidact Meta:
- Q&A: 161 requests (or sometimes 162)
- Site Proposals: 123 requests
- Blog: 55 requests

I don't know how many people view Codidact without logging in, but each one who does could be creating hundreds of requests in a few seconds of clicking around different communities and categories.

**Comment by trichoplax** [comment]
I've forked the repo and I'm having a go at fixing this bug to help me learn how QPixel works.
