### ISSUE TITLE
Can we make our links look better on Twitter etc?

### ISSUE THREAD

**Issue by cellio** [codidact/qpixel#95]
When I tweet a link to a blog post, news article, Medium post, SE question, etc, it comes out "oneboxed".  (I don't know if that's the right term in context.)  You get the title, a logo (for SE) or photo (from articles that have them), maybe a few words... something more than just a bare URL, in other words.

Can we do that for links to our sites?

I don't know if this is actually a QPixel request or something more general about how our webserver is configured or something else entirely.

Here's a tweet where I just noticed the link-only treatment: https://twitter.com/MonicaCellio/status/1270887171042480128.

**Comment by ArtOfCode-** [comment]
Should be done with the latest deploy, but I'm not familiar with how Twitter cards work exactly, so let me know if it doesn't work.
