### ISSUE TITLE
Show number of search matches on the results page

### ISSUE THREAD

**Issue by cellio** [codidact/qpixel#956]
https://meta.codidact.com/posts/287246

Can we add the number of matches found to the top of the page of search results?  The results are paginated, so the code knows how many results there are (in order to produce the page links at the bottom), so I'm assuming it isn't too hard to expose that information?  With this change, it's more obvious right away if you need to consider refining your search, as opposed to scrolling to the bottom and seeing that there are many many more pages.  (Yes we try to show the most relevant first, but if your search is very specific and you didn't formulate it quite right, this would help you see that.)

**Comment by duncanscode** [comment]
Working on this, should have it ready shortly.
