### ISSUE TITLE
Font Awesome icons inside of data-header-slide elements are not clickable.

### ISSUE THREAD

**Issue by duncanscode** [codidact/qpixel#965]
**Describe the bug**
Font Awesome icons inside of data-header-slide elements are not clickable. In link_to elements, they are working as intended.

**To Reproduce**
1. Click precisely on the "Show Communities" icon or Search icon (the magnifying glass) in the header.
2. Nothing will happen.
3. Click slightly outside of the icon, but still in the menu item.
4. Associated header-slide element will open.

**Expected behavior**
Icons within menu items should be clickable. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS Monterey
 - Browser Chrome 
 - Version 108.0.5359.124

**Smartphone (please complete the following information):**
Not tested

**Additional context**
So far I have identified this on the Search icon, the Communities icon, and the Inbox icon.

**Comment by duncanscode** [comment]
My bad - somehow missed this while searching through issues. Thanks for linking!

**Comment by cellio** [comment]
Please don't feel bad.  I would much rather get a bug report twice than zero times.  Thanks for the help.
