### ISSUE TITLE
Do we want to upgrade to Rack 3?

### ISSUE THREAD

**Issue by trichoplax** [codidact/qpixel#967]
**Is your feature request related to a problem? Please describe.**
We recently had a security update to Rack (#963). This is important, but takes up developer time. We are currently using Rack 2, which requires more security updates due to its structure.

**Describe the solution you'd like**
One of the changes in [moving from Rack 2 to Rack 3](https://github.com/rack/rack/blob/main/UPGRADE-GUIDE.md "Upgrade guide") is that they have separated out several optional elements into their own gems, so that only people using those additional gems need to worry about security updates to them. This reduces the "security surface area"(as they put it) for Rack so we would not see security issues as often unless we are using all of the optional extra gems.

There will be a certain amount of work involved in migrating from Rack 2 to Rack 3, depending on how many of the changes mentioned in the linked upgrade guide affect QPixel. Can we assess this to see whether the work involved would be sufficiently small to justify upgrading?

**Describe alternatives you've considered**
Not applicable.

**Additional context**
None

**Comment by Taeir** [comment]
Your suggestion is good, but there is a bit of a problem.

Rack is what is called middleware. Rails heavily depends on rack for processing requests. It builds an entire layer on top of Rack in such a way that we have no or almost no interactions with Rack itself in our codebase. We cannot update rack until rails does so.

Currently we use the following dependencies which limit us to rack 2:
* ActionPack (part of rails)
* Sprockets (asset pipeline)

I expect rails 7.1 or rails 8 to make the switch to rack 3, after which we should automatically be updated as well.

**Comment by trichoplax** [comment]
Thanks very much @Taeir.

As it's going to be automatic I'll close this issue.
