### ISSUE TITLE
Add hint about details/summary to formatting help

### ISSUE THREAD

**Issue by cellio** [codidact/qpixel#978]
https://meta.codidact.com/posts/287346 asks about adding support for spoilers, but CommonMark doesn't have spoiler syntax.  That's ok because HTML has the details/summary tags, but a lot of people don't know about them.  Let's add a small bit to the formatting help to cover this.  There is a seeded help topic for formatting in this repo, which is why I'm filing this instead of just fixing it on our network.  We'll need to apply the change in both places.

**Comment by trichoplax** [comment]
It might be worth including in the same help section that a blank line is required inside the `details` tag immediately after the closing `summary` tag before the content begins if the content contains any markdown.

There are examples in [Details tag requires an internal blank line to render markdown](https://meta.codidact.com/posts/287279). Those are separated out into individual examples to demonstrate that they are all distinct causes, but for a help section example a few of them could be combined into a single example with and without a blank line.

Without a mention of this it can be non-obvious what is causing the markdown to not render.
