### ISSUE TITLE
If posting is restricted by TL, also restrict editing

### ISSUE THREAD

**Issue by cellio** [codidact/qpixel#99]
It is possible for a category to have a minimum trust level for posting.  People who do not have the trust level to post should not be able to edit either, even if they otherwise have the editing privilege on the site.  We should allow them to suggest edits, same as low-privilege users can do elsewhere.

The motivating use case is creating a blog category on Meta for our newsletter mailings.

**Comment by ArtOfCode-** [comment]
Done with 4486bad
