### ISSUE TITLE
Edits indicator circle shown to users who cannot review

### ISSUE THREAD

**Issue by trichoplax** [codidact/qpixel#995]
**Describe the bug**
See [Edit activity show, but not allowed to approve](https://meta.codidact.com/posts/287830).

The indicator circle next to the "Edits" tab for a category is shown to users who do not have the "Edit Posts" ability.

**To Reproduce**
1. As a user without the "Edit Posts" ability:
2. Suggest an edit to a post in a category
3. Notice that the indicator circle now appears next to the "Edits" tab of that category

**Expected behavior**
Only users with the "Edit Posts" ability see the indicator circle on the "Edit" tab of a category.

**Comment by cellio** [comment]
Users can still view the pending edits if they click on the "edits" link, and I think that's fair.  Among things, it helps you find out what happened to your own suggestion, and it lets the community see if there's a problem (edits backing up) that might need to be discussed.  So I don't think we should change the availability of the page itself -- but I do agree that lighting it up when you can't do anything with that info is not helpful.
