### ISSUE TITLE
Second flag has radio button prefilled

### ISSUE THREAD

**Issue by trichoplax** [codidact/qpixel#997]
**Describe the bug**
When flagging a post, a user selects a radio button to indicate the reason for flagging (for example "it's spam"). If the user then flags the same post again, the same radio button is already selected.

**To Reproduce**
1. Flag a post, making a note of which radio button you select
2. Flag again, and notice that the same radio button is already selected

**Expected behavior**
In the unusual case that a user needs to flag the same post twice, it seem unlikely that they will have the same reason the second time. The radio buttons should start empty, as they did for the first flag.

**Comment by cellio** [comment]
I wonder if this was intended info gone astray.  I think it's helpful to remind someone that hey, you've already flagged this, but I think that would be better as information, not a pre-select.  In fact, if you've already flagged something, a second flag of the same type is almost certainly not what you want (aside from custom flags).

When fixing this to remove the pre-select, consider moving that info that (clearly) we already have here to "You have already flagged this as X", shown at the top of the modal.

**Comment by trichoplax** [comment]
It might be that the info that this has already been flagged isn't as readily available as it seems. If the same modal is hidden and then reused for each new flag it might just have the radio button selected from last time it was visible.

If it turns out that there is a way to indicate that a post has already been flagged that would be particularly useful if someone flags something a few days later, forgetting that they already have.

Would it work to have the same flag summary as in the Flag History page?

> **it's spam:** User entered flag wording — [trichoplax‭](https://meta.codidact.com/users/53890) ([history](https://meta.codidact.com/users/53890/flags))

These could be listed under a heading at the top of the flag modal, with the heading only being present if there is at least 1 previous flag to list. Something like "Your previous flags on this post".

Maybe as a separate issue if this isn't straightforward?
